### ISSUE TITLE
Warn if exporting a non-watertight mesh

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#100]
See http://solvespace.com/forum.pl?action=viewthread&parent=1665.

**Comment by whitequark** [comment]
@Evil-Spirit Can you look into this?

**Comment by Evil-Spirit** [comment]
@whitequark, ok

**Comment by Evil-Spirit** [comment]
implemented https://github.com/Evil-Spirit/solvespace/commit/05d3a7b9ac8fc49d283a5b1dfc8813f466d9a9bb

**Comment by whitequark** [comment]
Merged, thanks.
