### ISSUE TITLE
draw a ring use the lathe tool

### ISSUE THREAD

**Issue by zhulaojianke** [solvespace/solvespace#1013]
SolveSpace version 3.0~f4ad8205
Operating system: Win7 Ultimate Edition sp1

When I draw a ring, first draw a circle and a line on the plane, select the line and then click "New group rotating actives sketch", it appears as below:
![image](https://user-images.githubusercontent.com/16543111/114754727-77272080-9d8b-11eb-99e0-34056e807996.png)
It doesn't produce a solid entity.

The Revolve tool also has this problem.

I can see from YouTube videos that it looks like anyone else can draw a ring this way. 
https://www.youtube.com/watch?v=X9byxcHuins
But I have tried version 3.0-f4ad8205 and version 2.3-7c1ca460, all can not do this matter.   :(

So in order to draw a ring, I must draw one shape like below:
![image](https://user-images.githubusercontent.com/16543111/114756025-e3eeea80-9d8c-11eb-938e-2d006b619327.png)
and then rotate it:
![image](https://user-images.githubusercontent.com/16543111/114756114-fcf79b80-9d8c-11eb-969b-d92b506c3a44.png)
and then draw another one shape:
![image](https://user-images.githubusercontent.com/16543111/114756408-4b0c9f00-9d8d-11eb-9ab8-29b767c64bd6.png)
rotate and difference:
![image](https://user-images.githubusercontent.com/16543111/114757563-983d4080-9d8e-11eb-9d95-8f018df24881.png)

This is a very complicated operation! 

Am I really the only one with this problem?

And hope to improve the lathe tool and the revolve tool.

**Comment by phkahler** [comment]
Make the rotation axis a construction line. Select it and press G. Then do your lathe or revolve.

The problem is that your sketch is not a closed contour. Construction lines don't count for that.

**Comment by zhulaojianke** [comment]
Ah...really did I misunderstand!

One last stupid question, I promise this is the last one. How to fillet multiple edges at the same time? For Example, all the edges around a cubic. It seems that the "tangent arc at point" only could be use in 2D sketch, and no command can be used on solid edges.
So I also used the dumbest way to make multiple chamfered edges:
![image](https://user-images.githubusercontent.com/16543111/114765963-64671880-9d98-11eb-9956-e1eebc342bd4.png)
As you can see after the round Angle, the vertex of the cubic is sharp, not smooth.
Like this:
![image](https://user-images.githubusercontent.com/16543111/114767136-da1fb400-9d99-11eb-9978-9f3b84fdf0a3.png)

In OpenSCAD, there is a command "Minkowski" can do this work well, and how to implement such chamfering in Solvespace?

**Comment by phkahler** [comment]
That can be done by using the Revolve tool to make some of the corners. I also used a rotate group to copy the corner 4 times in the attached sketch. Have a look. The green points from the original sketch can still be dragged to change the size. All curves share the same radius.
![rounded_cube](https://user-images.githubusercontent.com/14852918/114768013-5d0f2300-9d36-11eb-8deb-bbbcf37b8c2c.png)
[rounded_cube.zip](https://github.com/solvespace/solvespace/files/6313242/rounded_cube.zip)

**Comment by phkahler** [comment]
One more tip for your lathe. You can also select a point and one of those little grey arrows to define the lathe axis. The arrow pointing down in your original image would have worked instead of drawing a line.

**Comment by zhulaojianke** [comment]
I have tried my best...
![image](https://user-images.githubusercontent.com/16543111/114776812-79967400-9da5-11eb-96ef-d1d4929edb80.png)
but there must be an easier way... I did this in the same clumsy method.

@phkahler Can you tell me about your drawing process? If it's not convenient to say it here, you can send me an email, zhu_xinyan@yeah.net.

**Comment by phkahler** [comment]
@zhulaojianke did you open the sketch I attached in a zip file? Start at the first group - check the box in the text window for it. Then move through each group.

**Comment by zhulaojianke** [comment]
Oh, sorry, I just found it.

**Comment by zhulaojianke** [comment]
Your method is much more efficient than mine.

But filling in a feature along a path is still cumbersome to implement now. I think that Solvespce already have lathe and revolve and helix commands and if the Solvespace has a stretch along the path function, then all the three commands can be merged in it, and it's more flexible. 
Then I can stretch out an entity by simply drawing a feature pattern and an curve path with its endpoint perpendicular to the workplane where that pattern is located. 
When the curve is round, closed and in a flat plane, then the lathe command is done. 
And when the curve is round, opened and in a flat plane, then the revolve command is done. 
And when the curve is spiral extened with constant diameter, the helix command is done.


I hope you can take my suggestion into consideration.

**Comment by ruevs** [comment]
There is an issue for loft already:
https://github.com/solvespace/solvespace/issues/439
