### ISSUE TITLE
Change default file filter for linking

### ISSUE THREAD

**Issue by phkahler** [solvespace/solvespace#1018]
### System information

- **SolveSpace version:** ALL
- **Operating system:** ALL

### Expected behavior

When linking a file we should set the default file filter to include types other than .slvs if they are linkable.

### Actual behavior

The filter is set to only .slvs but that is not the only option.

### Additional information

SolveSpace can currently link .emn (IDF files) and should soon be able to link .stl files. The default filter for linking should include these other options to make it quicker for users, and to make that ability more discoverable.

**Comment by kk6mrp** [comment]
I haven't checked on Linux but windows shows both options:
![image](https://user-images.githubusercontent.com/9358855/115266320-f64e8880-a0ec-11eb-81d4-3481a62001f0.png)

**Comment by phkahler** [comment]
It does support both. What I mean is to have a single option (default) that shows both slvs and emn at the same time. And when STL is added we should show all 3 at the same time. The point is to show all files that could be linked so the user doesn't have to change the filter except to narrow the scope. We would keep the more specific options too.

**Comment by Symbian9** [comment]
@phkahler, I highly recommends rename *"ALL"* to *"Supported formats"*, because *"ALL"* is commonly used in desktop software to list *just all available files in a folder path* in file chooser dialogs (aka *"All files"*).
