### ISSUE TITLE
Feature Request (UI): Dark Title- and Menu-Bar

### ISSUE THREAD

**Issue by abrac** [solvespace/solvespace#1056]
Would it be possible to make the title-bar and the menu-bar dark? I think this would make the window look much better. This is how it currently look on my system (Ubuntu 20.10).

![image](https://user-images.githubusercontent.com/55248999/121169149-fe58b800-c853-11eb-9fe1-8bb4b5e26c0a.png)

As you can see the white menu-bar and title bar are quite distracting. If I switch my global theme to a dark theme, this looks much better (see below), but I want the dark theme to be *only* applied to SolveSpace.

![Screenshot from 2021-06-08 12-21-57](https://user-images.githubusercontent.com/55248999/121169584-71622e80-c854-11eb-949a-dfbc70a7624b.png)

SolveSpace version: 2.3

**Comment by kk6mrp** [comment]
This is not an issue with Solvespace. A quick Google search results in posts like this: https://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis
