### ISSUE TITLE
Active workplane border is shown wrongly after resetup workplane in "sketch-in-plane" group

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#1069]
### System information

- **SolveSpace version:** `3.0~` https://github.com/solvespace/solvespace/commit/ddb76324afb99376c1bf5cccec2db7cb06a023dc
- **Operating system:** Debian 10 buster

### Expected behavior

*Active workplane border* should be shown in actually *active workplane* in any group with a sketching mode turned to *"Sketch > In Workplane"*.

### Actual behavior

0. Keep shown `g001-#references` group (with a `#XY`, `#ZX`, `#YZ` reference planes);
1. Initial *"sketch-in-plane"* workplane (border) in `g002-sketch-in-plane` group is set to be in `#XY` reference plane from;
2. In `g002-sketch-in-plane` group switch sketching mode to *"Sketch > Anywhere in 3D"*;
3. Select `#ZX` (or `#YZ`) reference plane and switch sketching mode to *"Sketch > In Workplane"*;
4. As a result: *"sketch-in-plane"* workplane border still shown in `#XY` reference plane, but it should be switched to be in `#ZX` (or `#YZ`) reference plane according newly set active workplane.

**Comment by ruevs** [comment]
> "sketch-in-plane" workplane border still shown in `#XY` reference plane

This is true,

>, but it should be switched to be in `#ZX` (or `#YZ`) reference plane according newly set active workplane.

No. The ""sketch-in-plane"_ workplane border" actually shows the workplane(s) of the groups that are "New Group | Sketch In New Workplane" and not the "active" workplane. To figure out what the active workplane is press `W`.

By the way one can show all workplanes for all "sketch-in-plane" groups by pressing the ![workplane](https://github.com/solvespace/solvespace/raw/master/res/icons/text-window/workplane.png) button in the text window.
