### ISSUE TITLE
Building from sources on Debian `buster-slim`

### ISSUE THREAD

**Issue by akauppi** [solvespace/solvespace#1076]
### System information

- **SolveSpace version:** git `master`, currently `a97b77c1e552c89aee873562694e7ac733056094`
- **Operating system:** Debian `buster-slim`

### Expected behavior

I followed the Linux Debian/Ubuntu instructions for [Building for Linux](https://github.com/solvespace/solvespace#building-for-linux) and found some deviations from the instructions.

"Expected behavior":

- I can compile the git `master`, for latest stable Debian, according to the instructions on the main `README`.

### Actual behavior

- I needed to add one package: `pkg-config`
- two packages listed as requirements were not missed by the compilation: `libfontconfig1-dev`, `libglu-dev`. Are these necessary? Maybe they came up indirectly through some others.

### Additional information

https://github.com/akauppi/docker-solvespace

- has the Dockerfile

I am aware of the following discussions:

- [solvespace 3..0 on Debian Linux](https://solvespace.com/forum.pl?action=viewthread&parent=3764) (SolveSpace Forum, 2021)

**Comment by akauppi** [comment]
I ended up being stuck with "Unable to create GL context" - which can be a Docker / macOS thing. https://github.com/akauppi/docker-solvespace/issues/1

**Comment by Symbian9** [comment]
@AlexanderP, may you get us your DEB-build scripts?

- https://notesalexp.org/packages/en/buster/amd64/solvespace/

**Comment by phkahler** [comment]
For the packages that are not missed, are they required to do a debug build? They are -dev packages.

**Comment by Symbian9** [comment]
FTR, It would good to make it usable via GitHub Actions, for example:

- https://github.com/nylas/build-dpkg-buster

**Comment by ruevs** [comment]
@akauppi [pkg-config](https://packages.debian.org/sid/pkg-config) sounds like a pretty "basic" package needed for development - maybe that is why it was not noticed? Everyone already had it?

And perhaps your "Debian `buster slim`" did not include it - which is untypical?

Someone more familiar with Linux distributions will have to decide whether we should add it to the README.

**Comment by Symbian9** [comment]
> Someone more familiar with Linux distributions will have to decide whether we should add it to the README.

@AlexanderP, may I ask You for help here?

**Comment by kk6mrp** [comment]
> I needed to add one package: pkg-config

It appears like pkg-config support has been required ever since the GTK port was added here: https://github.com/solvespace/solvespace/commit/2c39f259db0c6b6f1eeef7fa95125311daadc991 and my best guess is that the distribution normally pulls it in with the `build-essential` package or something like that. I couldn't find any other information on it but there is pkg-config and pkgconf, pkgconf appears to be a replacement for pkg-config. I probably wouldn't add it as a dependency for that reason and cmake does a good job of telling you when a package is missing from your system as well as what it is.

> two packages listed as requirements were not missed by the compilation: libfontconfig1-dev, libglu-dev. Are these necessary? Maybe they came up indirectly through some others.

If you noticed under the https://github.com/solvespace/solvespace#building-for-linux link, it states:

> To build the GUI, you will need **fontconfig**, gtkmm 3.0 (version 3.16 or later), pangomm 1.4, OpenGL and **OpenGL GLU**, and optionally, the Space Navigator client library. On a Debian derivative (e.g. Ubuntu) these can be installed with:

**Comment by AlexanderP** [comment]
libfontconfig1-dev and pkg-config are needed, cmake checks them, and installed as dependencies of `libpangomm-1.4-dev`
```
libpangomm-1.4-dev -> libpango1.0-dev ->  libfontconfig1-dev
libpangomm-1.4-dev -> libpango1.0-dev -> pkg-config 
```

**Comment by ruevs** [comment]
So shall we close this without adding `pkg-config` to the build instructions or should we add it?

**Comment by Symbian9** [comment]
Could be there created `build-deb.sh` script for easily compile & build DEB package locally or via CI/GitHub actions?

- https://github.com/jtdor/build-deb-action
- https://github.com/zlig/deb-builder-packagecloud

**Comment by ruevs** [comment]
https://tracker.debian.org/pkg/solvespace
