### ISSUE TITLE
Feature Request: Backwards compatibility for macOS 10.14.5

### ISSUE THREAD

**Issue by kryspetrie** [solvespace/solvespace#1086]
### System information

- **SolveSpace version:** 3.0~0e0b0252 (release)
- **Operating system:** macOS 10.14.5

### Expected behavior

Application opens under macOS 10.14.5

### Actual behavior

Popup saying Solvespace is only compatible with macOS 10.15.x

### Additional information

For organizational reasons I cannot upgrade yet would like to still use this software... Is there any way to maintain a single major OS version of backwards compatibility?

**Comment by Symbian9** [comment]
Which version are you using (could be run) now on your macOS 10.14.x?

@kryspetrie, please, try @vespakoen's DMG build:

- https://github.com/vespakoen/solvespace/releases/tag/3.0.0-alpha.5

**Comment by phkahler** [comment]
@vespakoen  I also have problems with the 3.0 stuff on my 2013 Macbook Air.  Do you know why newer builds don't run on older OSX?  I'd like them to work, but I don't even know why they don't. Any ideas?

**Comment by kryspetrie** [comment]
I don't have previous version information since this is a newly provisioned
laptop. I'll try the suggested build and will let you know.

**Comment by ruevs** [comment]
@tomsci since you are actively working on the code on macOS can you look into what is required to support old versions? I don't have a Mac (newer than 2008 :-) ), but as far as I can see in the history of [guimac](https://github.com/solvespace/solvespace/commits/master/src/platform/guimac.mm) we should be able to run on very old macOS versions if compiled "properly".

**Comment by tomsci** [comment]
On it :)

**Comment by ruevs** [comment]
Now that I have [macOS in a VirtualBox](https://github.com/solvespace/solvespace/issues/1199) I experimented a bit (did a bisect) and found that the [oldest version](https://en.wikipedia.org/wiki/MacOS_version_history#Releases) for which we can compile with Xcode 11.3.1  is [10.9 Mavericks](https://en.wikipedia.org/wiki/OS_X_Mavericks).

It runs fine on Mojave and the test suite (solvespace-testsuite) passes. Now to see if it is possible/easy to install Mavericks in a virtual machine...

Just did `cmake .. -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET="10.9"`

With `-DCMAKE_OSX_DEPLOYMENT_TARGET="10.8"` or older even the CMake configuration can not be generated.
