### ISSUE TITLE
Backport patches from LibreCAD's libdxfrw

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#1087]
### System information

- **SolveSpace version:** `master~` https://github.com/solvespace/solvespace/commit/56719415dea4de7af750227653362f4c8cad78f8 
- **libdxfrw version**: `master~` https://github.com/solvespace/libdxfrw/commit/0b7b7b709d9299565db603f878214656ef5e9ddf
- **Operating system:** all supported

### Expected behavior

Backport patches from LibreCAD's `libdxfrw` into SolveSpace's `libdxfrw`

- [ ] Fix incorrectly truncated size types in `dwgbuffer`, minor cleanups: https://github.com/LibreCAD/libdxfrw/commit/f766eb3d4bac1fcb020e43c53f40745bd75e9abe
- [ ] Complete version detection with all known versions: https://github.com/LibreCAD/libdxfrw/commit/431df398d993a0d6778c6b89458bd3a2c791a5c9
- [ ] **Check other commits & pulls which also may be useful to backport**:
  - https://github.com/LibreCAD/libdxfrw/commits/master
  - https://github.com/LibreCAD/libdxfrw/pulls

### Actual behavior

Actually LibreCAD's `libdxfrw` got few useful patches which would be good to backport into SolveSpace's `libdxfrw`

**Comment by phkahler** [comment]
Closing, as we are going to switch to LibreDWG.
