### ISSUE TITLE
0xc000007b on Windows 7 

### ISSUE THREAD

**Issue by ArmanHayots** [solvespace/solvespace#1100]
### System information

- **SolveSpace version:** 3.0
- **Operating system:** Windows 7 SP1 x64

### Behavior

0xc000007b error on start of both solvespace.exe and solvespace-openmp.exe

### Additional information

DependencyWalker shows some strange errors with linking to WinRT(?) files. Screenshot attached.
![DependencyWalker](https://user-images.githubusercontent.com/25264017/131150437-7d7f709e-74fc-448d-af4b-17b71fb81fc8.jpg)

**Comment by ArmanHayots** [comment]
@ruevs, can you provide a link to that version?

**Comment by ArmanHayots** [comment]
Installed **Microsoft Visual C++ 2005-2008-2010-2012-2013-2019-2022 Redistributable Package Hybrid x86 & x64**  and problem is gone.

**Comment by ruevs** [comment]
The Visual C++ redistributable is explicitly mentioned as a requirement for the multiprocessor (openmp) version on the download page https://solvespace.com/download.pl

**Comment by ArmanHayots** [comment]
Yes.

**Comment by kk6mrp** [comment]
@ruevs I've had to install the redistributable for solvespace.exe to work in the past. The only think I can guess is that the executable is not 100% native though it seems like it should be.

**Comment by ruevs** [comment]
I don't have any "clean" Windows machines. I'll have to meke a VM and see what is going on.
