### ISSUE TITLE
Repeated console messages during rectangle sketching

### ISSUE THREAD

**Issue by lineprinter** [solvespace/solvespace#111]
```
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
```

**Comment by whitequark** [comment]
Debug output to the console is generally normal; on Windows this used to use OutputDebugStringA, which is only visible in MSVC, but to support other environments we print it to stderr too.

The particular WithMagnitude messages indicate sloppiness in some algorithm, but are generally not a cause for concern. If you have patches that improve the algorithms in questions, they are very welcome!
