### ISSUE TITLE
16-bit color PNG gets imported as corrupted

### ISSUE THREAD

**Issue by anymouse404** [solvespace/solvespace#1110]
### System information

- **SolveSpace version:** 3.0~0e0b0252
- **Operating system:** Ubuntu 20.04

### Expected behavior

16-bit color picture imports correctly in the same way as the 8-bit (both attached)

### Actual behavior

The 16-bit colored image has weird colors, line artifacts and is cut in half (pictured right in the following picture:)
![image](https://user-images.githubusercontent.com/49173322/132983160-1fbafb96-ee95-4fd9-bb08-e0f07342869f.png)

Here are the 8- and 16-bit files:

[test-8-and-16-bit-png.zip](https://github.com/solvespace/solvespace/files/7149368/test-8-and-16-bit-png.zip)

**Comment by Symbian9** [comment]
Issue probably related to `libpng` (as SolveSpace uses it for import PNG):

- https://stackoverflow.com/questions/51309691/read-16-bit-png-using-libpng

**Comment by phkahler** [comment]
> @phkahler, any ideas?

Don't use 16bit PNG files?  Seriously.  But it looks like a valid bug.

**Comment by anymouse404** [comment]
Tbh, I feel like an error message would be plenty sufficient solution.

**Comment by Symbian9** [comment]
>  I feel like an error message

Something like next?

```
Error
 
Image is broken or this format is not supported.
Convert image to 8-bit PNG using image editor.

[OK]
```
