### ISSUE TITLE
Do not reserve space above toolbar in minumum window size

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#1130]
### System information

- **SolveSpace version:** `3.0~`https://github.com/solvespace/solvespace/commit/6bc63e92b0d908aa751ae06063b2ec00fec4cc57
- **Operating system:** Debian 11 bullseye (Fluxbox)

### Expected behavior

There should be no extra `32px` space in height reserved in minimum window size.

To allow record full window (with title & toolbar ON) at least in 720p video standard (1280x720).

### Actual behavior

Actually impossible to record full window at least in 720p even with minimalistic window decoration, due to minimum height of full window (with tittle &, toolbar ON) out of 720 px in height:

![211007_222705](https://user-images.githubusercontent.com/13188580/136452595-d0c224c5-c76a-482f-89ec-ebe0bd6e93e2.png)

**Comment by ruevs** [comment]
I like it and have implemented it.
![image](https://user-images.githubusercontent.com/15338069/140373599-62db8d85-0dc8-4e4c-abae-c36554e7b028.png)

**Comment by Symbian9** [comment]
> I like it and have implemented it.

Looks great!

**Comment by Symbian9** [comment]
> This allows the main window height to be a minimum of 688 pixels (on
Windows 10) so it is possible to capture 720P video tutorials.

Thanks, @ruevs!

 Now its possible also to capture not only full SolveSpace window, but also system panel to be captured too ;)

![slvs3x-720p](https://user-images.githubusercontent.com/13188580/141159629-1f135470-e8e3-4c66-90b3-cb35f1094dba.png)
