### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by shockergit** [solvespace/solvespace#1139]
How do i create a workspace under the pipe.
I need to add a hook below the pipe in the center how can i do that?
This is the hook
![Screenshot 2021-11-01 141202](https://user-images.githubusercontent.com/63154802/139659406-7cba0818-f9f5-489a-a3b3-8c5d2852f1a6.png)
This is the pipe.
![Screenshot 2021-11-01 141250](https://user-images.githubusercontent.com/63154802/139659467-9c32cd7f-9be4-4bf1-a816-d5b764fccb43.png)

**Comment by ruevs** [comment]
Closing since this was answered on the forum:
https://solvespace.com/forum.pl?action=viewthread&parent=3965&tt=1635846778
