### ISSUE TITLE
Solver fails to converge when applying parallel constraint to exactly perpendicular lines

### ISSUE THREAD

**Issue by henrebotha** [solvespace/solvespace#1148]
### System information

- **SolveSpace version:** 3.0~0e0b0252
- **Operating system:** Xubuntu 21.10

### Expected behavior

I imported `column.slvs` into `matrix-right.slvs` and attempted to set the normals of the centre point of the circle parallel to the same point on another circle. I expected the imported model to be rotated such that the normals are now parallel.

### Actual behavior

The solver failed to converge. If I rotate the imported model at all (in any direction) before applying the constraint, then it works as expected. Thus I suspect it is the fact that the model is imported with its centre point normal exactly perpendicular to the existing centre point normals that is causing the problem.

### Additional information

See `matrix-right.slvs` in the attached file. [matrix-right.zip](https://github.com/solvespace/solvespace/files/7692302/matrix-right.zip)

**Comment by phkahler** [comment]
@henrebotha what about the same orientation constraint?

**Comment by phkahler** [comment]
Going with a wont-fix on this one. The issue is mathematical and there isn't an obvious way to push the solver in one direction or the other.
