### ISSUE TITLE
Normals are see-through

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#115]
This is some very weird bug, probably related to depth buffer? Draw a torus (
[torus.zip](https://github.com/solvespace/solvespace/files/599891/torus.zip). You can see the normal from the circle that's used to make the torus from this angle:
![2699](https://cloud.githubusercontent.com/assets/54771/20429738/68330eb0-ad88-11e6-99ad-fbb374700617.png)
... but not from a slightly different one:
![2700](https://cloud.githubusercontent.com/assets/54771/20429742/6cf4dd16-ad88-11e6-8925-97e53e006a9e.png)

@Evil-Spirit please look into this

**Comment by Evil-Spirit** [comment]
@whitequark, yes, we have it everywhere. probably this is because tricks with depth buffer in ssglDepthRange

**Comment by whitequark** [comment]
@Evil-Spirit I'm not sure. This is not a problem in version 2.0, 2.1 or 2.2, but it is a problem with 3.0 with OpenGL 1 and OpenGL 2. It was introduced somehow during the Canvas changes I think.

**Comment by whitequark** [comment]
But 2.0 still uses the ssglDepthRange hacks.

**Comment by whitequark** [comment]
@Evil-Spirit Also, this only seems to happen to normals, and not to edges...

**Comment by Evil-Spirit** [comment]
fixed in https://github.com/Evil-Spirit/solvespace/commit/832a8bdf670f4f148415f8f30e359df972e7f3aa

**Comment by Evil-Spirit** [comment]
@whitequark, this happen because AlignToPixelGrid uses this function.

**Comment by whitequark** [comment]
Merged, thanks
