### ISSUE TITLE
"Hide shaded view of solid model" + "Hide occluded lines" broken

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#116]
I think the DEPTH_ONLY drawing of meshes is broken somehow. @Evil-Spirit please take a look

**Comment by Evil-Spirit** [comment]
@whitequark, OK

**Comment by Evil-Spirit** [comment]
@whitequark 
fixed https://github.com/Evil-Spirit/solvespace/commit/d0806ad4aafdde018098dce4b26fb761c89d481a

**Comment by whitequark** [comment]
Merged, thanks
