### ISSUE TITLE
Snap secret expired?

### ISSUE THREAD

**Issue by vespakoen** [solvespace/solvespace#1176]
The latest [CD run](https://github.com/solvespace/solvespace/runs/4685812548?check_suite_focus=true) almost succeeded, it looks like the snap secret expired (It looks like it has to be renewed every year?)

`Error fetching account information from store: The request is missing an Authorization header field containing a valid macaroon`

@jwesthues Did you setup the account over there? or do you know who did?

**Comment by ppd** [comment]
You're absolutely right. See https://github.com/solvespace/solvespace/issues/1153, I've already sent @phkahler a new token.
