### ISSUE TITLE
Rename "line styles" to "styles"

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#1177]
### System information

- **SolveSpace version:** `3.0~`https://github.com/solvespace/solvespace/commit/e07b082eb810d2088c92b97d04e864a4ab95816f
- **Operating system:** all supported

### Expected behavior

In "Property Browser" tab "line styles" should be renamed just to "styles" (or even to "styles & theme").

### Actual behavior

Actually "line styles" are misinterpreted as only styles for lines, but it assigns not only for lines, but also for closed path fills solid colors & SolveSpace UI theme (canvas background, etc.)

### Additional information

Additionally for "background color (r, g, b)" there should be color preview icon (on the left from color values string), same as for all other color styles.

**Comment by phkahler** [comment]
"styles and colors" ???

**Comment by Symbian9** [comment]
> "styles and colors" ???

Maybe. But if so then "colors & styles" (and use "&" instead of "and" for shorten)

Additionally, what You think about move "background color" to "view" tab?

**Comment by phkahler** [comment]
> Additionally, what You think about move "background color" to "view" tab?

In that case this should remain "line styles" because it's just for lines?  I did wonder about moving BG color, but if the existing tab if for colors then no?

Question: Are any of these saved as part of the sketch, or are they all general settings?

**Comment by ruevs** [comment]
@phkahler if you create custom styles they are shown in the list and are saved in the model. The default ones are in the registry/json.

Changing label is superfluous (especially considering the translations).

**Comment by Symbian9** [comment]
> Question: Are any of these saved as part of the sketch, or are they all general settings

Good question!

Guess, "background color" is not saved into `slvs` file, but other "line styles" (especially newly created custom styles) are saved into `slvs`, where there are entities with custom styles.
