### ISSUE TITLE
ScheduleGenerateALL for AddRequest

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#119]
https://github.com/Evil-Spirit/solvespace/commit/c35d2787941b4849a811ea6be24138411950dc84
Before this, the problem appear when create DATUM_POINT (persistentDirty was not set since generation was not performed).

**Comment by Evil-Spirit** [comment]
@whitequark, updated here

**Comment by whitequark** [comment]
Fixed in master.
