### ISSUE TITLE
Display a circle length in the browser

### ISSUE THREAD

**Issue by hinell** [solvespace/solvespace#1211]
![image](https://user-images.githubusercontent.com/8136158/152760009-9d2988df-af8f-497c-97f9-5c36ccaacedb.png)

I request to enable displaying a circle length in the browser window when selected.

### System information
- **SolveSpace version:** 3.0.rc2+repack1-3
- **Operating system:** Linux/Microsoft

**Comment by phkahler** [comment]
Should we also add arc length?

**Comment by hinell** [comment]
@phkahler May be useful, I'm not sure. I was making  a gear and found myself calculating its length it manually.
@EkaterinaEvdokimova Екатерина, ты из России?

**Comment by EkaterinaEvdokimova** [comment]
@hinell Да, я из России

**Comment by phkahler** [comment]
@hinell   I just checked, and you can measure lengths with Analyze->Perimeter in the menu. You select any number of lines, arc, circles (but no points, not sure why those aren't auto-excluded) and it will give the total length.

It still seems reasonable to display the length of a single selected entity in the text window though.

**Comment by phkahler** [comment]
> @hinell Да, я из России

I've looked at google search data, and some other things and it seems Solvespace is quite popular in Russia and parts of eastern Europe. Does anyone know why that might be? Just curious.

**Comment by hinell** [comment]
@phkahler It's handy to have this information listed right away in the browser data in unit-less format. I used this information to calculate the pitch for the gear (in non standard way of course). Would be best if we can have _cog tool_ for that at some point in the future though.

Regarding geographical distribution of users, well I'm not sure why. Probably because it's free. Personally I started to use it only recently. It's a good (not perfect though) alternative for Linux.

**Comment by ruevs** [comment]
There are better ways.

You can type formulas in any dimension field. If you want a circle with a circumference of 500 just type `500/(2*pi)` for the radius.

You can use `sqrt`, `square`, `sin`, `cos`, `asin`, `acos`, `pi`, `+`, `-`, `*`, `/`, `()`

![CircleCircumference1](https://user-images.githubusercontent.com/15338069/152974170-11b3c842-5244-4161-8ded-605b6fae51ff.png)
![CircleCircumference2](https://user-images.githubusercontent.com/15338069/152974181-33cc9962-2ad0-445b-87c9-d61b42984c81.png)

And don't ask for the formulas to be remembered it is the oldest and best feature request  https://github.com/solvespace/solvespace/issues/77 ;-)

**Comment by ruevs** [comment]
> > @hinell Да, я из России

А аз съм от България :-)

> 
> I've looked at google search data, and some other things and it seems Solvespace is quite popular in Russia and parts of eastern Europe. Does anyone know why that might be? Just curious.

@phkahler SolveSpace simply resonates with the proverbial Slavic soul :-D

Joke aside, my theory is that in the former eastern block there (still) are a disproportionately high percentage of geeks/DIYorselfers/makers/whatever and the minimalist and clean "ideology" of SolveSpace attracts people who do not want to pirate SolidWorks (or any of the others) or their systems simply can not meet the [system requirements](https://www.solidworks.com/support/system-requirements).

**Comment by hinell** [comment]
@ruevs [#issuecomment-1032485216](#issuecomment-1032485216)
Omg why in hell isn't this documented in the [main reference](https://solvespace.com/ref.pl)?! :smile: 

>And don't ask for the formulas to be remembered 

Omg sounds like you need a bit of fresh blood to refresh some rusty  SolveSpace gears out here!

Btw, this reminds me of the TypeScript issue that they can't solve for about 7 years now. It's constantly poping up but nobody cares. The issue is simply though....

**Comment by ruevs** [comment]
> @ruevs [#issuecomment-1032485216](#issuecomment-1032485216)
> Omg why in hell isn't this documented in the [main reference](https://solvespace.com/ref.pl)?! 😄 In which units `cos` / `sin` / `tan` functions accept value? Radians? It seems like they are working incorrectly.

It is documented a bit (exactly in the reference) ;-)

> ### Dimension Entry and Units
> All dimensions are entered in the current display units. In most places where a dimension is expected, it's possible to enter an arithmetic expression ("4*20 + 7") instead of a single number. 

But adding the supported operations is a good idea.

The trigonometric function parameters are in degrees.

**Comment by phkahler** [comment]
> Omg why in hell isn't this documented...

@hinell   And to really blow your mind, the geometric/algebraic constraint solver can use these functions in constraint equations. We don't currently support user input of constraints, only evaluation of expressions.

**Comment by Symbian9** [comment]
> Should we also add arc length?

We already has arc length in "Property Browser", but adding circle length would be good too ().

![Screenshot_2022-02-08_19-41-45](https://user-images.githubusercontent.com/13188580/153045135-4c50c358-414b-4756-ac3c-441cc01e506c.png)

**Comment by hinell** [comment]
@phkahler Not documented too, right? How can be this done?

**Comment by ruevs** [comment]
Done
