### ISSUE TITLE
Snap builds fail with "aa_is_enabled() failed unexpectedly"

### ISSUE THREAD

**Issue by ppd** [solvespace/solvespace#1229]
## What's the problem?

Snapd switched to strict AppArmor checking: https://github.com/snapcore/snapd/commit/c6011693a816f7f8a5b0c7858ddce91c6ef1a352

This check fails in containers, rendering our current pipeline useless because it relies on Docker to provide an arm64 environment for cross-builds.
The GitHub action's author has no idea how to fix this either: https://github.com/diddlesnaps/snapcraft-container/issues/8

## What can we do?
Either wait and pray, or drop the edge arm64 builds. We could still set up an arm64 outside GH actions, e.g. by syncing our repo to launchpad, which has arm64 workers or something like this. But in the short term, I propose dropping the arm64 edge build in CI.

@phkahler Does that sound reasonable to you?

**Comment by phkahler** [comment]
> Does that sound reasonable to you?

Yes it does. You've been the one getting snaps together, so if you're OK with it so am I  ;-)  It would be nice to build for everything, but sometimes that's just not possible. Looks like there are people actively trying to solve the problem, but for now we should probably just drop it.

**Comment by ppd** [comment]
I'll make a PR. Anything's possible with unlimited time, but at the moment I'm elbow deep in thesis work and don't have the mental energy to debug this complicated stack (GH actions + docker + snapd + QEMU user mode emulation).
