### ISSUE TITLE
Can't input numbers 2, 3, 9 when using GTK+3 interface

### ISSUE THREAD

**Issue by tpimh** [solvespace/solvespace#128]
The problem is that when textfield is focused the keyboard shortcuts are not disabled, so instead of inputing corresponding numbers those buttons (2, 3, 9) try to trigger their shortcuts.

**Comment by whitequark** [comment]
Yup. The GTK 3 interface is not really supported, as mentioned in README.

**Comment by Symbian9** [comment]
It could be fixed after implementation of user defined shortcuts, where user can replace default key assignments.

**Comment by whitequark** [comment]
@Symbian9 this is completely irrelevant. it's a bug with modal grabbing, and it has nothing to do with shortcuts at all.

**Comment by whitequark** [comment]
Fixed in master.

**Comment by tpimh** [comment]
Thank you!02.01.2017, 18:26, "whitequark" <notifications@github.com>:Fixed in master.
