### ISSUE TITLE
Quick dragging of sketch could broke it

### ISSUE THREAD

**Issue by mkyral** [solvespace/solvespace#1282]
### System information

- **SolveSpace version:** 3.1~c65e31be
- **Operating system:** Gentoo Linux

### Expected behavior

I've noticed, that sometimes, when I dragging sketch around workplane, sketch could break. It looks like it always happen, when I drag sketch too quickly.

### Actual behavior
1) create simple test case - rectangle with construction line inside
![obrazek](https://user-images.githubusercontent.com/155542/185757625-7f5c62f6-d14f-47e3-a8e5-4743fb1f2ea6.png)

2) click to some line and slowly drag model around workplane - all is ok
3) do it again, but this time drag it quickly down - construction line could move outside rectangle
![obrazek](https://user-images.githubusercontent.com/155542/185757898-1e79d89b-ee94-4267-938d-a75d6266bab1.png)

4) Point is still constrained to the line
![obrazek](https://user-images.githubusercontent.com/155542/185758582-c85b68b2-eb7d-420a-9adf-5e813827ee38.png)

The same issue is with arches
![obrazek](https://user-images.githubusercontent.com/155542/185758079-16b8930d-af27-412b-a147-7c8fd7b2807f.png)
![obrazek](https://user-images.githubusercontent.com/155542/185758096-75b9962a-b75f-4348-8afc-bd5c378ca5ec.png)

### Additional information

Both sketches attached in file: [slvs_drag_issue.zip](https://github.com/solvespace/solvespace/files/9387729/slvs_drag_issue.zip)

**Comment by ruevs** [comment]
Known. https://github.com/solvespace/solvespace/issues/76

As workaround:
 Temporarily `relax constraints and dimensions` from the group properties in the text window, "straighten" the sketch roughly and then turn the option off.

Or just undo ;-)

**Comment by phkahler** [comment]
Or for some cases just yank it back.
