### ISSUE TITLE
Add an API or CLI to control Solvespace (set parameters, generate exported models, ...)

### ISSUE THREAD

**Issue by hlzr** [solvespace/solvespace#129]
It would be really neat if parameters could be set from the command line or programatically thorough an API.  Also, it would be neat if exporting could be done through the command line or an API.  Parameters might then have to be named or something like that.

Here's my use case.  I am using some simulation software that has a very difficult to use solid modeler.  I'd love to kick off a script that updates a design parameter in solvespace, renders an STL, and reimports each the updated model.

Thanks for the awesome software!

**Comment by whitequark** [comment]
A CLI is actually already implemented. Try:

    solvespace-cli export-mesh --output %.stl foo.slvs

This will write `foo.stl`. Use `--chord-tol` to set the numerical precision of the generated mesh.

As for parameters, this is already planned, see #77. Of course the parameters will be exposed in the CLI once they are implemented.

I'm closing this as duplicate now.
