### ISSUE TITLE
Linked part missing when launching from command line with specified file 

### ISSUE THREAD

**Issue by DPAttila** [solvespace/solvespace#1292]
### System information

- **SolveSpace version:** 3.1~bce25bb0 (compiled from source)
- **Operating system:** Debian

### Expected behavior

I am launching SolveSpace from the command line, by specifying a previously saved assembly (that has a single linked part) as a command line parameter. (Note that I've added `~/solvespace/build/bin/` to my `$PATH`)
`solvespace asm.slvs`
I would like to get my assembly as it was saved, with `part.slvs` included.

### Actual behavior

The assembly is loaded, the linked part's name is in the object list, but the linked part doesn't appear on screen, because it's file was not found.
The text window for the linked part shows `link geometry from file: '.'`

### Additional information

If I see correctly, the path of the linked part is saved as a relative path in the assembly file.
If I launch the program without specifying a file on the command line, then I open the assembly file from inside the program, I get the correct result.

I suspect the reason is that in the buggy case, the initial working directory for SolveSpace is not the specifyed 
file's directory, but the launched binary's directory.

[demo.zip](https://github.com/solvespace/solvespace/files/9536373/demo.zip)

**Comment by ruevs** [comment]
Known. Unfinished pull request here https://github.com/solvespace/solvespace/pull/1194
