### ISSUE TITLE
Comments should link to the point they're constrained to

### ISSUE THREAD

**Issue by jkrei0** [solvespace/solvespace#1295]
### System information

- **SolveSpace version:**  `3.1~70bde63c` 
- **Operating system:** Windows 10 

### Expected behavior

When comments are selected they should show a link in the property browser to the point they are constrained to, like any other constraint does.

*(eg. equal length constraint links to the lines it constrains)*
![image](https://user-images.githubusercontent.com/51007423/193377291-1cc7d934-0fe0-4385-adcd-e94504cd67b1.png)

### Actual behavior

Comments don't show anything in the property browser when selected
![image](https://user-images.githubusercontent.com/51007423/193377327-acf68e29-5bdd-48c3-87a6-3bb03c1c9537.png)

**Comment by ruevs** [comment]
@jkrei0 This is a duplicate to #1072 and is already implemented here 1e1e6558485145f86260bd97ab863d1a59a15cd8.
