### ISSUE TITLE
Re-linking a missing linked file only lets you select .slvs files, so it doesn't let you set the new path for a linked .stl file

### ISSUE THREAD

**Issue by interfect** [solvespace/solvespace#1297]
You can create a link to a `.stl` file in an assembly, but if the link breaks because the original file moves, you can only replace it with a `.slvs` file.

The problem is that the re-linking dialog uses `SolveSpaceModelFileFilters`:
https://github.com/solvespace/solvespace/blob/bce25bb0e2811d5a1b40d305d0e35ec7252d58b1/src/file.cpp#L921
Which only lets you pick `.slvs` files:
https://github.com/solvespace/solvespace/blob/f6bb0a2d35ba6c67a72170413207d0f28bac216d/src/platform/gui.cpp#L84-L86
But when making a *new* link, you get to use `SolveSpaceLinkFileFilters`:
https://github.com/solvespace/solvespace/blob/026f9369894bd526e049ee0fbf2ee928ffdde612/src/group.cpp#L306
And that lets you pick other types, like `.stl`:
https://github.com/solvespace/solvespace/blob/f6bb0a2d35ba6c67a72170413207d0f28bac216d/src/platform/gui.cpp#L88-L93

I *think* that just changing the filters used in the open dialog might solve the problem, but I'm not sure if anything special happens when initially linking a non-Solvespace file that would need to re-run on re-linking but isn't set up to do so.

**Comment by interfect** [comment]
@phkahler You seem like you might know what the right answer is here.

**Comment by ruevs** [comment]
I merged the pull request fixing this - it is the correct behaviour. But even before that (at least on Windows) it was possible to "re-link" moved or renamed STL and EMN files by simply typing `*.*` in the file name field.
