### ISSUE TITLE
Big Red lines even if "force NURBS surface to triangle mesh" and export stl

### ISSUE THREAD

**Issue by fredOnGitHub** [solvespace/solvespace#1298]
### System information

- **SolveSpace version:** 3.1 70bde63c
- **Operating system:** win11

Hello,

from this it is ok
![bug1](https://user-images.githubusercontent.com/9338756/194626788-2aa29d4d-a816-4caa-9be1-6e05e66f2bcc.png)

but from this arc version
![bug2](https://user-images.githubusercontent.com/9338756/194627213-9ec2cebf-01cc-4585-937b-aba5cd36c133.png)

i get 
![bug3](https://user-images.githubusercontent.com/9338756/194627430-a2ba2184-2337-4a30-9bdd-94b00c83f10d.png)
and it is ok when i do "force NURBS surface to triangle mesh" => no red lines 
but when i export triangle maillage
i get
![bug4](https://user-images.githubusercontent.com/9338756/194627875-00f7058e-2f5a-4954-afd5-b6b56e2e4b4b.png)

I am furious and disappointed (LOL).

Thanks

**Comment by ruevs** [comment]
It is a known promlen.

Make the straight parts (corner) of the cutting ark sketch stick out of the part by a bit (instead of coinciding with the corner) - it will solve your problem.

**Comment by fredOnGitHub** [comment]
Hello,

if i understood i have done that 
![done1](https://user-images.githubusercontent.com/9338756/194707700-1eeb8f16-f3d0-4927-823a-84aa654d9b73.png)
that
![done2](https://user-images.githubusercontent.com/9338756/194707715-bc7719fc-292b-46de-a451-40911ad421ac.png)
that
![done3](https://user-images.githubusercontent.com/9338756/194707723-be0793f0-47af-45da-a27a-ebe90ede7cd2.png)
that
![done4](https://user-images.githubusercontent.com/9338756/194707784-95b4eaf4-c2db-4e7b-8ee2-b225f600eb47.png)

to get
![done5](https://user-images.githubusercontent.com/9338756/194707742-b6a4c74e-ecb1-4e64-a84b-09472ba56291.png)

**1st question :**
Is it the good way ? More simply ?


and finally with Windows 3d viewer
![done6](https://user-images.githubusercontent.com/9338756/194707768-1f65b96d-bdf3-4c6e-9609-b93caeaf387b.png)
But I see polygons...
 **2nd question :**
Are 'chord tolerance (in percent)' and all other parameter good ? I don't remember the default values.
How can I get nice shape without polygon mesh ?

Thanks

**Comment by ruevs** [comment]
You did it in a way that is more complicated than needed. Here is what I would do:
![FilletTestsFailuresExplined](https://user-images.githubusercontent.com/15338069/194714088-6d246e57-e2ef-4fc7-a298-e7ba486649aa.png)

The failing case asks the software to make two "complicated" (for an algorithm) decisions:
1. Does an infinitely thin (zero thickness) "sliver" of material remain in the spots marked in yellow?
2. The material being cut approaches zero thickness when approaching the points where the line segments and the arc meet tangential to each other. this poses a numerical problem.

To avoid this I just used two construction lines to position the arc and moved the two lines forming the sketch to the out side.

Another hint - make the extrusion with the "difference" operation "two-sided" to avoid asking SolveSpace to solve a similar singularity problem where the "front" faces of the two solids coincide (it does usually handle it OK).
![FilletTestsRotated](https://user-images.githubusercontent.com/15338069/194714345-5238c4fd-e0bd-41f8-a40e-b73cbfe008cf.png)

[FilletTests.zip](https://github.com/solvespace/solvespace/files/9739576/FilletTests.zip)

**Comment by ruevs** [comment]
> Are 'chord tolerance (in percent)' and all other parameter good ? I don't remember the default values.

The `export chord tolerance (in mm)` and `export max pieceise linear segments` parameters control how fine the exported meshes are. After an export operation SolveSpace displays the exported mesh until you press `ESC`. Turn on the mesh ![MESH](https://raw.githubusercontent.com/solvespace/solvespace/master/res/icons/text-window/mesh.png) to check if it is acceptable.

**Comment by fredOnGitHub** [comment]
More simply !
Thanks !
I have a nice NURBS into the form form now.
![good1](https://user-images.githubusercontent.com/9338756/194717187-e6eae0bf-06bf-481e-b994-b6dc456d819f.png)

compared to rendering before
![good2](https://user-images.githubusercontent.com/9338756/194717286-a63677d1-ce6f-47ba-a767-c489ebc7977d.png)

About the exportation, I have done that :
![good3](https://user-images.githubusercontent.com/9338756/194717362-e8d9e1c2-64db-4210-8cb8-b8b750244ec1.png)
to get
![good4](https://user-images.githubusercontent.com/9338756/194717437-9e60ee39-d152-4b60-a234-6f56a1e52b6f.png)

Thank You very much !

**Comment by ruevs** [comment]
Just for cross-reference - this is a duplicate to #1291
