### ISSUE TITLE
Hi, copy transformed fixes

### ISSUE THREAD

**Issue by ryannining** [solvespace/solvespace#13]
I try some code to fix the mirror sketch by copy transfformed and set scale -1.

So it originally fail to mirrored sketch that have constraint.

the constraint need to be scaled to, this is what i add after line 205 clipboard.cpp

```
if (c.type == ConstraintBase::Type::PT_LINE_DISTANCE) {
        if(scale < 0) {
                c.valA *= -1;
        }
        c.valA *= fabs(scale);
}
```

I have test , and looks like it work, although it will introduce  unsolvable constraint, because some constraint cannot be negative * fixes... limiting the PT_LINE only will eliminate the unsolvable constraint

thx for the great CAD software.
Ryan widi

**Comment by whitequark** [comment]
Fixed in master and 2.x.
