### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#130]
According https://github.com/solvespace/solvespace/blob/master/CONTRIBUTING.md it would be better make template for new issues (automatically added when create new issue).
* https://help.github.com/articles/creating-an-issue-template-for-your-repository/
* https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by whitequark** [comment]
Done.

**Comment by Symbian9** [comment]
Add to template info posted by @Evil-Spirit

- https://github.com/solvespace/solvespace/issues/314#issuecomment-360021915
