### ISSUE TITLE
.msi installer and perhaps submit to winget-pkgs

### ISSUE THREAD

**Issue by Wallby** [solvespace/solvespace#1309]
[winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by ruevs** [comment]
What's the point? SolveSpace is a single .exe file that just works. And this is not by random chance.

**Comment by phkahler** [comment]
This seems like work with no benefit.

**Comment by ruevs** [comment]
https://github.com/microsoft/winget-pkgs/pull/118952
