### ISSUE TITLE
FindWhichToRemoveToFixJacobian can be very slow

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#131]
See [constrainfreeze.zip](https://github.com/solvespace/solvespace/files/645378/constrainfreeze.zip)--try adding a redundant constraint.

From http://solvespace.com/forum.pl?action=viewthread&parent=1705.

**Comment by Evil-Spirit** [comment]
@whitequark, we can limit number of constraints when FindWhichToRemoveToFixJacobian should be performed, if greater, we just report an error without concrete constraints.

**Comment by whitequark** [comment]
@Evil-Spirit is there no faster way than just bruteforce?

**Comment by Evil-Spirit** [comment]
@whitequark, Yes, we can be a little bit faster now (~3 times faster with the current example) if we just rewrite SolveBySubstitution for linear complexity instead of square. I actually done this for NotSolveSpace and this is huge speedup when we have a large amount of h,v,pc. The other two hot functions WriteJacobian and CalculateRand. The first can be performed once and used for many times, and the second can be low-level optimized or replaced in future by external linear system solver functions.

**Comment by whitequark** [comment]
@Evil-Spirit OK, this sounds like something useful to be done. For now it is low priority though.

**Comment by Evil-Spirit** [comment]
@whitequark,
I've made attempt to make some optimization, mostly because we have to exclude SolveBySubstitution because of #208. But this still o(n^4)....(((((

**Comment by Evil-Spirit** [comment]
@whitequark 
One more imporvement.
But we can't avoid SolveBySubsitution because constrainfreeze.zip without it and even with optimizations is dead slow (~60sec). I think we need to analyze redundant h/v/pc not using RankTest, just comparing constraints.

**Comment by Evil-Spirit** [comment]
@whitequark 
https://github.com/Evil-Spirit/solvespace-master/commit/6584093cb3ce23ca5fb87fe39877d5448fe854ea

**Comment by whitequark** [comment]
Doesn't apply on master anymore.

**Comment by Evil-Spirit** [comment]
@whitequark, OK I am rebasing

**Comment by Evil-Spirit** [comment]
https://github.com/Evil-Spirit/solvespace-master/commits/master-131

**Comment by Evil-Spirit** [comment]
@whitequark, but this is works bad after we add forceDofCheck. try to comment forceDofCheck inside FindWhichToRemoveToFixJacobian to allow SolveBySubstitution run. It will be fast for constraintfreeze.slvs. But this will not consider some cases with double-hvpc

**Comment by whitequark** [comment]
@Evil-Spirit how to fix this?

**Comment by Evil-Spirit** [comment]
@whitequark, For now I only can suggest to limit FindWhichToRemoveToFixJacobian by time. For constraintfreeze it's over 600 equations if we don't appy solvebysubstitution, so we can just give up until we involve sparse-matix algorithms. The second way - is to find double constraints like hvpc

**Comment by whitequark** [comment]
@Evil-Spirit ok. is there any benefit from your updated patch?

**Comment by Evil-Spirit** [comment]
@whitequark, only if we choose "finding the same multiple hvpc". if we bound by time, there is no point.
only benefit is from loop unrolling, but this is something like x2-x3

**Comment by whitequark** [comment]
@Evil-Spirit ok. let's add a 1000ms time limit, and indicate in the text window if it was reached.

**Comment by Evil-Spirit** [comment]
@whitequark, acc.

**Comment by Evil-Spirit** [comment]
@whitequark, implemented here
