### ISSUE TITLE
Are there python bindings for solvespace / exposed?

### ISSUE THREAD

**Issue by jloveric** [solvespace/solvespace#1311]
Are there python bindings for solvespace / exposed?  I see python-solvespace (https://pypi.org/project/python-solvespace/), but that is not installing properly for me and may not be supported... I'm running on ubuntu.

**Comment by ruevs** [comment]
I've never used it but as far as I understand it may be deprecated:
https://github.com/KmolYuan/python-solvespace

However there is a new one that is pretty well supported and seems to be used in a university in Taiwan in a mechanical engineering class.

https://github.com/solvespace/solvespace/pull/493
https://github.com/KmolYuan/pyslvs
https://github.com/KmolYuan/Pyslvs-UI

But @KmolYuan can answer this the best.
