### ISSUE TITLE
Revolving a combined Bezier spline around a line fails - Solvespace goes down

### ISSUE THREAD

**Issue by kasorli** [solvespace/solvespace#1313]
### System information

- **SolveSpace version:** 
- **Operating system:**

**Comment by phkahler** [comment]
@kasorli  what is a "combined" Dezier Spline? Also, did you revolve around a line with sketch entities on both sides of the line? This issue report does not contain enough information to reproduce the problem.

**Comment by ruevs** [comment]
I can not reproduce this. Please attach a model with a single sketch that causes the problem when revolved.
