### ISSUE TITLE
Contraints cause crash

### ISSUE THREAD

**Issue by phkahler** [solvespace/solvespace#1316]
### System information

MASTER

### Expected behavior

Creating constraints should work

### Actual behavior

Extrude a rectangle.
Create a point entity "P" not on the box
select the point and one face
press "o" for a point-on-face constraint
Solvespace crashes

Also crashes: midpoint "M" constraints
### Additional information

This seems related to the prior commit for creating multiple constraints at once.

**Comment by phkahler** [comment]
@77maxikov

**Comment by phkahler** [comment]
@77maxikov  This seems be due to the lines:

```
            newcons.push_back(c);
            AddConstraint(&c);
```
By writing it as:
```
            newcons.push_back(c);
            for (auto&& nc:newcons)
                AddConstraint(&nc);
            break;
```
The problem goes away. So why does the former fail and the later not? What are the implications of this when c is used to create multiple constraints?

**Comment by 77maxikov** [comment]
Confirm crash. The idea behind using newcons was make it possible to add multiple constraints where it applicable. So the use of iteration on newcons for cases in switch should only be done for such situations. Trying now to find a way out.

**Comment by phkahler** [comment]
I suspect AddConstraint is modifying the constraint - perhaps adding an ID to it. But at the very end of all the constraint construction code there is a loop over newcons looking for redundant constraints. Maybe using AddConstraint(&c) prevents the copy in newcons from getting whatever update is needed and crashes that later code looping over the new constraints.

**Comment by phkahler** [comment]
Another way to fix it is to swap the order:
```
            AddConstraint(&c);
            newcons.push_back(c);
```
This is consistent with the idea that AddConstraint is modifying c.

**Comment by 77maxikov** [comment]
Yes. AddConstraint(&c)  assigns c.h, so this check `if(nc.h != cc.h && nc.Equals(cc))` in the end loop let SK.constraint.RemoveById(nc.h); which fails. So any code adding constraints should be changed

**Comment by phkahler** [comment]
I'm going over it all now. I wanted to add a new multi-constraint. I'll fix it.

Thanks!
