### ISSUE TITLE
Accept comma as decimal separator (enhancement)

### ISSUE THREAD

**Issue by Contraptionize** [solvespace/solvespace#132]
It would be nice to be able to enter dimensions on international keyboards that feature a comma on the numpad instead of a period / full stop as decimal separator. Currently this causes the Error message "Not a valid number or expression: "1,23".

The decimal point is currently hardcoded in https://github.com/solvespace/solvespace/blob/master/src/expr.cpp#L706

It might suffice to replace it just after https://github.com/solvespace/solvespace/blob/master/src/expr.cpp#L683
`if( c == ',') input[inputPos] = '.';`

although there likeley are better solutions to do this.

There could be an option to enable this behavior to avoid unexpected behaviour for people trying to use the comma as thousands-separator (e.g. 1,000.00 - one thousand), although this does is not supported anyway.

Keywords: internationalization, i18n, localization, L10n

**Comment by whitequark** [comment]
I don't see how this will work once functions are implemented. E.g.: think of `atan2(1,0)`.

**Comment by Contraptionize** [comment]
Yes, sorry, I have not really looked at the parser code and did not think of comma as argument separator.

**Comment by whitequark** [comment]
Note that I don't reject this so far, l10n is a valid concern. What do other applications do? Is this why Excel uses `;` as a separator? Do other numeric processors just force you to input `,`?

**Comment by whitequark** [comment]
Regarding thousands-separator, the way endorsed by SI/ISO 31-0 is to separate them with spaces, not commas; we can use _ in place of spaces, I think.

**Comment by whitequark** [comment]
Regarding numpad-dot/comma, I think we can just detect that key and translate it to a dot.

**Comment by whitequark** [comment]
After some consideration, and [asking](https://twitter.com/whitequark/status/808630690166099968) people using non-US keyboard layouts, I have decided that this will get handled in two ways:
  - [ ] `_` will be accepted and ignored when parsing expressions;
  - [ ] numpad `.`/`,` will be always translated to `.`.

**Comment by whitequark** [comment]
Fixed in master (not for Cocoa though since I think it doesn't expose the numpad keycodes in any way?)
