### ISSUE TITLE
regression in master when entering fractions for a Distance/Diameter/Length constraint

### ISSUE THREAD

**Issue by SebKuzminsky** [solvespace/solvespace#134]
I just switched from the 2.x branch (6802a12a) to master (3dd2fc00), and noticed a regression.  When entering a value for a Distance/Diameter/Length constraint, fractions no longer work right.  In 2.x I could enter this:

    3/4

And the constraint would have the expected value of 0.75.  But in master, entering that fraction gives me a value of 1.33 (4/3).  A couple of other fractions also gave me reciprocal values.

Bisecting shows that the bug first appeared in commit 61f2488.

**Comment by whitequark** [comment]
Fixed in master.
