### ISSUE TITLE
Crashing with upon application of symmetry constraints

### ISSUE THREAD

**Issue by IntegrativeMechanobiologyLaboratory** [solvespace/solvespace#1345]
### System information

- **SolveSpace version:** 
- 3.1~d6e97091
- **Operating system:** 
Ubuntu

### Expected behavior

Selected an edge of a rectangle, then clicked "Constraints" > "Symmetric". The rectangle should get the symmetry constraint. 

### Actual behavior

Software crashed.

### Additional information

**Error message on the terminal:**
SolveSpace!

Missing (absent) translation for 'A&ngle / Equal Angle'
Missing (absent) translation for 'E&qual Length / Radius'
connect failed: No such file or directory
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
Vector::WithMagnitude(2.3) of zero vector!
File ./src/dsc.h, line 526, function FindById:
Assertion failed: t != nullptr.
Message: Cannot find handle.
Aborted (core dumped)

**Comment by ruevs** [comment]
This is a regression, probably around 3d3d5c789d7035517bec6a4df6e7590f5f22e680 I need to bisect and/or debug it.

**Comment by 77maxikov** [comment]
https://github.com/solvespace/solvespace/blob/d6e970918f5ea77757a6d21da8b11f9c66882422/src/constraint.cpp#L583 should be exchanged with the next one

**Comment by 77maxikov** [comment]
@ruevs, should I make a PR for this?
