### ISSUE TITLE
How to constraint step-rotation (polar array) by symmetry?

### ISSUE THREAD

**Issue by temoto** [solvespace/solvespace#1346]
### System information

- **SolveSpace version:** 3.1~70bd
- **Operating system:** linux

### Task

Revolver-alike rotor, that is cylinder with holes through flat faces. Holes are placed symmetrically on a reference circle.

### Actions

- create sketch in plane
- draw circle of rotor, starting from workplane center point
- constraint rotor diameter
- draw circle of hole, starting from point on X reference
- constraint hole diameter and distance from center
- step-rotate (polar array), set number of repeats

### Expected behavior

0 DOF. Distance between holes (angle of rotation) is same, 360/N.

### Actual behavior

1 DOF, angle between holes.

### Additional information

I only found a way to constraint that DOF via distance between holes which is irrelevant to model and makes no sense in general.

Thanks to developers for this great tool. It's not easy to learn, but somehow feels right direction of UI development.

**Comment by ruevs** [comment]
- Draw a construction line segment (`S`, `G`) on the +X axis.
- Constrain it's length (`D`)
- Circle (`C`) on the end point of the line segment
- Constrain its diameter (`D`)
- Select origin and do Step rotating (`Shift+R`)
- Select two of the rotated copies of the construction line and constrain the angle (`N`)
- Enjoy 0 DOF :-)

The attached file implements the above approach 
[SepRotatingWithConstructionLineAndAngleBetwenCopies.zip](https://github.com/solvespace/solvespace/files/10847470/SepRotatingWithConstructionLineAndAngleBetwenCopies.zip)

![Clipboard03](https://user-images.githubusercontent.com/15338069/221781601-87ba1ef1-9367-4d6b-9f9c-0584fbb58522.png)
