### ISSUE TITLE
Cannot start latest git version of solvespace - assertion failed - missing resource

### ISSUE THREAD

**Issue by brucerennie** [solvespace/solvespace#1350]
### System information

- **SolveSpace version:**  3.0~25b5977.
- **Operating system:** Debian GNU/Linux 11 (bullseye)  - 5.10.0-20-amd64

### Actual behavior

File ./src/platform/platform.cpp, line 589, function LoadResource:
Assertion failed: ReadFile(ResourcePath(name), &cache[name]).
Message: Cannot read resource.
Aborted

**Comment by ruevs** [comment]
Did you build from source? Do older versions work?
