### ISSUE TITLE
Constraint a dimension of a 2d sketch to an extrusion length of another group

### ISSUE THREAD

**Issue by pocomane** [solvespace/solvespace#1358]
### System information

- **SolveSpace version:** 3.0~0e0b0252
- **Operating system:** Arch Linux

### Expected behavior

Set two dimensions to be equal (one being the extrusion length)

### Actual behavior

I can drag the lines in order to make the two dimensions equal, but if I try to make the "Equal length" constraint, it becomes unsolvable

### Additional information

Step to reproduce:

- Open solvespace
- Draw a rectangle
- Extrude it (single side)
- Make a new workplane on the new face (the one equal to the original one)
- Make another rectangle
- Extrude it (single side)
- Sketch -> Anywhere in 3d
- Select the first extrusion length and a dimension of the second rectangle
- Click on  "Constrain equal length"

![Screenshot from 2023-04-17 15-14-03](https://user-images.githubusercontent.com/14974494/232496484-cda5799d-aacb-44ac-864b-208bd83c8f04.png)

### Question

Why I can not do it in that way? When can I, and when can I not, use an extrusion length in a constrain?

**Comment by phkahler** [comment]
The purple marks indicating an equal length constraint in your image don't make sense to me. You've selected on line that is the length of the first extrusion (fine) and one that is the height of the second 2D sketch, which does not correspond to the length of the 2nd extrusion. Not only that, but the 2D sketch is probably group 4 in your group list (see the text window, not shown). A constraint will treat anything from a previous group as *constant*  within the current group, and will not be able to move that geometry to satisfy the constraint. 

Had you selected the long edge of the first box and the long edge of the second (or the green line) it should work fine.

**Comment by pocomane** [comment]
> You've selected on line that is the length of the first extrusion (fine) and one that is the height of the second 2D sketch

That are exactly the two edges that I want to be equal.

> constraint will treat anything from a previous group as _constant_ within the current group, and will not be able to move that geometry to satisfy the constraint.

It seems that this is the bit of information I was missing. I searched in the reference manual on the website but I did not found anything about it. Did I overlooked to it? Or, if actually absent, can this information be added to the reference manual?

In any case, can you confirm that the only way to set a dimension of a 2d sketch equal to an extrusion length of another group is to use a "Constrain distance" and set the the same value? (Which means that every time I change one of the two values I have to remember to change also the other one).

> Solvespace will also let you drag entities in previous groups with your mouse if they are unconstrained. This sometimes causes confusion of the type "why can I move this, but not constrain it?"

In fact that was another confusion I had. However I think the main point is to remember that, practically, the constraint can be set only in the same group, and not freely on any geometry in the space (I am simplifying here, I know that with two groups of 2d sketch on different planes I can constrain their projections).

**Comment by phkahler** [comment]
You can make the constraint you want. You have to do it when the second sketch group is active - use the check boxes at the left of the home screen in the text window to select the 2nd sketch.

When you apply the constraint between that 2d sketch and the previous 3d extrusion, the line in the 2d sketch will become the same length as the other one. You will not be able to drag the later one because it's tied to something in a previous group. You will still be able to drag the first one because its group is unconstrained, and the later will follow.

The way you tried to do it, both lines are in groups prior to the constraint, so neither can be moved. And yet you've asked them to be equal. It's like saying 3=10.

I guess a key phrase is that constraints are solved/resolved one group at a time in the order the groups were created.

**Comment by pocomane** [comment]
Thanks! In this way I got the result I wished. I had only another small issue but the solution was simple: before setting the constrain as you explained, I had to select sketch > anywhere in 3d, otherwise it would generate a redundant constraint.


> I guess a key phrase is that constraints are solved/resolved one group at a time in the order the groups were created.

Thanks again, this was enlightening too.
