### ISSUE TITLE
text tool crashes with emoji

### ISSUE THREAD

**Issue by ohsix** [solvespace/solvespace#136]
### System information
linux and windows, ~master

new drawing -> use text tool

select text and hit change, paste an emoji

the one i happened to try is http://unicode.org/emoji/charts/full-emoji-list.html#1f910 but it probably crashes on more

**Comment by whitequark** [comment]
Fixed in master. Note, emoji will only be shown when using the TTF text tool, and with a supported font:
![2784](https://cloud.githubusercontent.com/assets/54771/21597654/00335248-d146-11e6-9537-63e5ffcdfca9.png)
