### ISSUE TITLE
[Bug] Paste mirror with pt-line distance

### ISSUE THREAD

**Issue by liuxilu** [solvespace/solvespace#1372]
### System information
- **SolveSpace version:** 3.1~659215d8
- **Operating system:** Win10
### Reproduce Steps
Draw this, select all, click paste transformed, select flip, click paste now
![image](https://github.com/solvespace/solvespace/assets/53636947/5bae742b-6d53-404f-95cf-62e898ec6fe3)

### Expected behavior
Mirrored sketch
### Actual behavior
A mess
### Additional information
Attached where I found the bug.
[PasteMirrorTest.txt](https://github.com/solvespace/solvespace/files/11600124/PasteMirrorTest2.txt)

**Comment by ruevs** [comment]
Can not reproduce with the example picture. See attached [1372_PasteTransformedTest.zip](https://github.com/solvespace/solvespace/files/11610917/1372_PasteTransformedTest.zip).

However with your file (https://github.com/solvespace/solvespace/files/11600124/PasteMirrorTest2.txt) the pasted copy does "scramble".

**Comment by liuxilu** [comment]
In your file there is a pt-pt distance. I have replaced a clearer image.

**Comment by ruevs** [comment]
> it is the signed distance.

Aha! Makes sense. Point-line distances are "signed" internally, so they preserve on which side of the line the point is... I can not answer immediately how the paste transformed code works in this case and what is the right thing to do. @phkahler has looked at these parts of the code more than me and may be able to give some insight.

**Comment by liuxilu** [comment]
Seems we can just reverse the sign.
