### ISSUE TITLE
Entities outside of the selection box get selected

### ISSUE THREAD

**Issue by liuxilu** [solvespace/solvespace#1374]
### System information

- **SolveSpace version:** 3.1~659215d8
- **Operating system:** Win10

### Expected behavior
Only the horizontal line is selected by doing this
![image](https://github.com/solvespace/solvespace/assets/53636947/eb25640e-787a-4b6e-8a35-42a732bf67e3)

### Actual behavior
The two lines are selected.
### Additional information
Because only AABB is used for detection, that's rough
https://github.com/solvespace/solvespace/blob/fd25424ab5e5a1c4158c1e65b33b6568b5f9bc2b/src/draw.cpp#L220-L224

**Comment by liuxilu** [comment]
Why closed?

**Comment by vespakoen** [comment]
I thought that the conclusion was that a more precise selection method would take too many resources, and would make things too slow, but thinking about it now there might be a possibility to make an exceptions for segments.

We could check if the selection box "lines" cross with segments, in stead of checking if the boxes overlap.

However, that would still not fix selection of arcs and splines, but could be an improvement overall that doesn't take too many resources?

<img width="447" alt="Screenshot 2023-09-23 at 11 27 19" src="https://github.com/solvespace/solvespace/assets/876117/6ae9e43b-60ed-4276-85cc-9963ae1a8b4e">

So we would basically make an exception for the above only, but would still have "odd" selection for the below:

<img width="389" alt="Screenshot 2023-09-23 at 11 27 58" src="https://github.com/solvespace/solvespace/assets/876117/0f722262-ed68-4b6b-80d5-9456c566abb7">

Would that be a good middle ground?

**Comment by ruevs** [comment]
That's a reasonable sounding possibility. It will require quite a few extra calculations but will still be a linear time algorithm (on the number of line segments). Could be acceptably fast.

**Comment by phkahler** [comment]
@vespakoen   Do both.  Use the existing fast but sloppy bounding box method, and then use a more precise method just for things that pass the coarse test. Entities have to pass both to get selected.

**Comment by ruevs** [comment]
> Use the existing fast but sloppy bounding box method, and then use a more precise method just for things that pass the coarse test.

Obviously... The line intersection test should be  just to cull the selection list made with bounding boxes. Doing anything else would be rather... strange/unwise...

**Comment by liuxilu** [comment]
How about requiring one point of the object to be in the box?
One-point-selected can be the indicator for user (my) interest, I think.

**Comment by ruevs** [comment]
> How about requiring one point of the object to be in the box?

Definitely not! This is worse than even the current behaviour (before the fix).

**Comment by phkahler** [comment]
Some tools will select anything overlapping the box if you draw the box left-to-right and only things completely inside the box when drawn right-to-left.

I thought solvespace was trying to do this but maybe not. Maybe it should. ;-)

**Comment by ruevs** [comment]
> Some tools will select anything overlapping the box if you draw the box left-to-right and only things completely inside the box when drawn right-to-left.

Interesting! I never knew this existed - in any software.

> I thought solvespace was trying to do this but maybe not. Maybe it should. ;-)

This could be a pretty useful "power user" feature. I wonder how widespread it is? Apparently AutoCAD uses it https://forum.vectorworks.net/index.php?/topic/42974-marquee-select-like-autocad/  and it seems Adobe Illustrator does not :-) https://illustrator.uservoice.com/forums/333657-illustrator-desktop-feature-requests/suggestions/31863601-select-inside-marquee-window

And an example of the behaviour on the web
https://playground.babylonjs.com/#QHHXSD#1

Interesting...
