### ISSUE TITLE
Feature request: Select more than 2 features to make equal

### ISSUE THREAD

**Issue by RM250J** [solvespace/solvespace#1384]
### System information

- **SolveSpace version:**3.1 
- **Operating system:**All 

### Expected behavior
Select more than 2 features e.g. arc to make equal

### Actual behavior
Solvespace fails to do this and gives an error message

**Comment by RM250J** [comment]
Apologies, duplicate request

**Comment by phkahler** [comment]
@RM250J   Not only a duplicate request, this is implemented in the current master branch and will be in the next release.  ;-)

**Comment by RM250J** [comment]
Fantastic, is there a timeline for the next release?

**Comment by ruevs** [comment]
The CI (continuous integration/automatic builds) are [currently broken](https://github.com/solvespace/solvespace/actions/runs/5675173296), so until there is a release the only option is to [compile it from source](https://github.com/solvespace/solvespace#via-source-code) .

**Comment by ruevs** [comment]
The last successful build is [this](https://github.com/solvespace/solvespace/actions/runs/4446327039#artifacts) from March 17 and it actually contains the feature you want. You can try it.

**Comment by RM250J** [comment]
Hi, I can compile from source. Do I need to use -DMAKE_BUILD_TYPE=Edge? Thx

**Comment by ruevs** [comment]
No.
