### ISSUE TITLE
can not launch on Win7

### ISSUE THREAD

**Issue by xyont** [solvespace/solvespace#1392]
### System information

- **SolveSpace version:** 3.1 stable
- **Operating system:** Windows 7 (64bit) SP1 updated

![2023-08-12 03_41_42-solvespace exe - Application Error](https://github.com/solvespace/solvespace/assets/72367311/c2d1d3d1-6c06-4dde-85d9-a680d915363d)

### Expected behavior

the programs can not launch

### Actual behavior

error messages
### Additional information

The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by phkahler** [comment]
@xyont  do older versions of solvespace work on your Windows 7 ?

**Comment by ruevs** [comment]
Do these versions launch?
https://github.com/ruevs/solvespace/releases/

**Comment by xyont** [comment]
`solvespace_WinXPBuild_Post3_1_659215d.exe` is not working (same error messages),  some  allert notification by Windows Defender. However, version 2.0 stable is fine. 

![2023-08-20 19_41_38-Downloads](https://github.com/solvespace/solvespace/assets/72367311/81cc7d17-b1fc-4b1d-9c40-053ec788633a)

**Comment by ruevs** [comment]
Well that is just Windows defender being... Windows defender...

If you want to be extra cautious give the file (or a link to it) to https://www.virustotal.com and convince yourself that it is not a virus.

Once you do that and tell Windows defender to let it be does it work?

**Comment by xyont** [comment]
i try excluded SolveSpace.exe files from Defender but still not works.

**Comment by ruevs** [comment]
@xyont what error message do you get?

**Comment by xyont** [comment]
After several times restarting the system, it's working now. 

Many thanks for the hints about excluded software setting in Defender.

![2023-09-11 00_47_29-SolveSpace - (new sketch)](https://github.com/solvespace/solvespace/assets/72367311/34e2a976-f53c-4e8a-8b4a-99203666a8a8)
