### ISSUE TITLE
CTRL+Shift+S should SaveAs, not save.

### ISSUE THREAD

**Issue by greenfox1505** [solvespace/solvespace#1397]
### Expected behavior

"Save As"

### Actual behavior

"Save"

### Additional information

Most applications bind CTRL+Shift+S as "save as" and CTLR+S as "save". Honestly, I'd be hard pressed to name one that didn't.

**Comment by ruevs** [comment]
Already implemented in the master branch https://github.com/solvespace/solvespace/commit/7ccb0ffac46e34abdef038ee1dacab3b21adeb93

Please try an edge build and report if it does not work for you:
https://github.com/solvespace/solvespace#via-automated-edge-builds

**Comment by ruevs** [comment]
@greenfox1505 did you try it?

**Comment by phkahler** [comment]
I verified this is working on Windows with an edge build.

**Comment by phkahler** [comment]
Closing.
