### ISSUE TITLE
The Constraint value editor is keep the expresion text next time it edited

### ISSUE THREAD

**Issue by ryannining** [solvespace/solvespace#14]
I have make some change, after many hours try learning and finding where and what need to add  (my base experience is python, need time to learn cpp).

I add `string exps;` to constraint class. And when double click, it show this string, or revert to default if this string is empty.

and when editdone, the expression string saved in this exps.

its simple code i dont know if it have bugs, need to check. and i need to learn more about git so i an help you guys.

**Comment by whitequark** [comment]
And what are you expecting me to do?

**Comment by ryannining** [comment]
nothing...

i have change code locally and just inform the change,

sorry guys...
