### ISSUE TITLE
Horizontal constraint in 3D using the code (slvs_py)

### ISSUE THREAD

**Issue by Andrej730** [solvespace/solvespace#1404]
My question is regarding some code trying to constraint 3d points, code written in python using solvespace python bindings (https://github.com/realthunder/slvs_py) but I think it's more general issue I've met.

The code example is below - you probably can skip just to `case_1()` method to see the issue.

If I define two 2d points instead than constraint works fine - (0, 5), (5,3) constrained to [[0.0, 3.0], [5.0, 3.0]]. So it's fine.

In the code I'm defining two 3d Points: (0, 5, 8) and (5, 3, 24).
Then I define horizontal constraint in workplane defined by point (0,0,0) and normal (0,0,1).
When I run the solver - (0, 5, 8) and (5, 3, 24).are constrained to (0,4,8), (5,4,24). When I'd expect them to be constrained to (0,4,8), (5,4,8) (paralle to plane horizontal axis, X axis).

Am I missing something? How would I make this line parallel to workspace horizontal axis in 3d?
Is it that `LineHorizontal` assures that *line projectd on a workplane* will be horizontal for the specified workplane and not that actual line will be horizontal to the workplane / line will be parallel to workplane horizontal X axis?

And perhaps a bit similar question - how would I create a constraint to make sure two arbitrary 3d lines will be parallel or keep the same distance between them?

```python
from py_slvs import slvs
from mathutils import Vector

V = lambda *x: Vector([float(i) for i in x])

solve_status_mapping = {
    0: "Successfully solved sketch.",
    1: "Cannot solve sketch because of inconsistent constraints, check through the failed constraints and remove the ones that contradict each other.",
    2: "Cannot solve sketch, system didn't converge.",
    3: "Cannot solve sketch because of too many unknowns.",
    4: "Solver failed to initialize.",
    5: "Some constraints seem to be redundant, this might cause an error once the constraints are no longer consistent. Check through the marked constraints and only keep what's necessary.",
    6: "Cannot solve sketch because of unknown failure."
}

solvesys = slvs.System()

def get_entity_params(entity):
    if isinstance(entity, int):
        entity = solvesys.getEntity(entity)
    params = []
    entity_id = entity.h
    param_i = 0
    while True:
        param_id = solvesys.getEntityParam(entity_id, param_i)
        if param_id == 0:
            break
        params.append(param_id)
        param_i += 1
    return params

def add_point(pos, workplane=None, fixed=False):
    is_2d = bool(workplane)
    pos = pos[:2] if is_2d else pos
    point_group = group if not fixed else FIXED_GROUP

    # `solvesys.addParamV` returns index of registered parameter
    # value can be accessed later with `solvesys.getParam(index)`
    params = [solvesys.addParamV(i, group=point_group) for i in pos]

    # `solvesys.addPoint3d` also returns entity index
    # you can get it later with `solvesys.getEntity(index)`
    if is_2d:
        p = solvesys.addPoint2d(workplane, *params, group=point_group)
    else:
        p = solvesys.addPoint3d(*params, group=point_group)
    return p

def quat_from_vector(vector):
    # similarly you can get vector (normal) from quaternion
    # Vector((0,0,1)).rotate(quat)
    return Vector((0,0,1)).rotation_difference(vector)

def get_param_values(params):
    return [solvesys.getParam(p).val for p in params]

def point_coords(point_entity):
    return get_param_values(get_entity_params(point_entity))

# BASIC SETUP, note that base points, normals and workplane must be fixed (assigned to the FIXED_GROUP)
# otherwise solver might change them trying to sovle the sketch
FIXED_GROUP = 1 # index 1 is reserved to keep some entities intact
group = 3
base_workplane_point = add_point((0,0,0), fixed=True)
base_normal = V(0,0,1)
base_normal = solvesys.addNormal3dV(*quat_from_vector(base_normal), group=FIXED_GROUP)
workplane = solvesys.addWorkplane(base_workplane_point, base_normal, group=FIXED_GROUP)
# there is no base point by default, we need to create it
base_point = add_point(V(0,0), workplane, fixed=True)

def case_1():
    # horizontal constraint example
    use_2d = True
    edge = ((0,5,8), (5,3,24))
    if use_2d:
        edge = [e[:2] for e in edge]
        edge = [add_point(pos, workplane) for pos in edge]
    else:
        edge = [add_point(pos) for pos in edge]
    line = solvesys.addLineSegment(*edge, group=group)
    
    # set new param values, line is not parallel anymore
    solvesys.getParam(get_entity_params(edge[0])[1]).val = 5.0
    solvesys.getParam(get_entity_params(edge[1])[1]).val = 3.0

    # in 2d: [(0.0, 5.0), (5.0, 3.0)]
    # in 3d: [[0.0, 5.0, 8.0], [5.0, 3.0, 24.0]]
    print([point_coords(e) for e in edge])

    solvesys.addLineHorizontal(line, wrkpln=workplane, group=group)
    retvalue = solvesys.solve(group=group, reportFailed=True, findFreeParams=False)
    print(solve_status_mapping[retvalue])

    # in 2d: [(0.0, 3.0), (5.0, 3.0)] - both y equals 3 now, case solved
    # in 3d: [[0.0, 4.0, 8.0], [5.0, 4.0, 24.0]] - not parallel to horizontal axis of workplane (X-axis)
    print([point_coords(e) for e in edge])

case_1()
```

**Comment by ruevs** [comment]
> In the code I'm defining two 3d Points: (0, 5, 8) and (5, 3, 24).
> Then I define horizontal constraint in workplane defined by point (0,0,0) and normal (0,0,1).
> When I run the solver - (0, 5, 8) and (5, 3, 24).are constrained to (0,4,8), (5,4,24). When I'd expect them to be constrained to (0,4,8), (5,4,8) (paralle to plane horizontal axis, X axis).

Constraints can be in 3d or _projected_ in a workplane (when one is active). To quote from the [reference manual](https://solvespace.com/ref.pl#GeneralConstraints):

> Most constraints are available in both 3d and projected versions. If a workplane is active, then the constraint applies on the projection of the geometry into that workplane. If no workplane is active, then the constraint applies to the actual geometry in free space. 

So the horizontal constraint you are defining works exactly as intended. The line between the points `projected` in the `XY` workplane is forced horizontal in the workplane. Attached is a file with the two points to experiment with visually.
[1404_TwoPoints.zip](https://github.com/solvespace/solvespace/files/12537261/1404_TwoPoints.zip)

So your guess:

> Is it that LineHorizontal assures that line projectd on a workplane will be horizontal for the specified workplane and not that actual line will be horizontal to the workplane / line will be parallel to workplane horizontal X axis?

is correct.

> And perhaps a bit similar question - how would I create a constraint to make sure two arbitrary 3d lines will be parallel or keep the same distance between them?

Make sure that you are in 3d and apply a parallel constraint.

**Comment by Andrej730** [comment]
Thank you! It worked. Completely missed that some constraints methods doesn't require workplane argument to be provided and therefore can work in 3d.
