### ISSUE TITLE
New rectangle. The dragged point are hovered.

### ISSUE THREAD

**Issue by ryannining** [solvespace/solvespace#141]
### System information

SolveSpace version: 3.0~9148d0cb.

### Expected behavior
The dragged point should not hovered, just like new line segment.

### Actual behavior
The dragged point constantly hovered.

### Additional information
If the DRAGGING_NEW_POINT the point is not hovered, then i can add ConstrainPointByHovered(pending.point); on mouseleftdown so the rectangle is constrained with other entity that hovered (not it self). If i add this anyway it will cause solver problem.

I have use this feature on my old version (sorry havent update on git). It work nicely.

**Comment by ryannining** [comment]
Looks like the probllem is because this code is different:
old:
`        d = e->GetDistance(mp);
        if(d < SELECTION_RADIUS && d < dmin) {
            s = {};
            s.entity = e->h;
            dmin = d;
        }`

new:
`if(canvas.Pick([&]{ e.Draw(Entity::DrawAs::DEFAULT, &canvas); })) {
            s = {};
            s.entity = e.h;
        }`

something to do with min distance ?

**Comment by Evil-Spirit** [comment]
@whitequark, fixed here. +improvements.

**Comment by whitequark** [comment]
Fixed in master.

**Comment by Evil-Spirit** [comment]
@whitequark,
what about https://github.com/solvespace/solvespace/commit/31296333539d6ce5f27220aba7363c2f26dfc1b2?
This is very annoying for me.

**Comment by whitequark** [comment]
@Evil-Spirit I haven't noticed that one... you just linked one commit here.

**Comment by Evil-Spirit** [comment]
@whitequark, Oh, sorry, usually I make branch for every issue and put some other improvements realated to it.

**Comment by whitequark** [comment]
Merged in master too.
