### ISSUE TITLE
Add in README known active PPA's that support SolveSpace

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#142]
### System information

SolveSpace version: all

Operating system: Linux-based

### Expected behavior

In readme file must be at least one or two PPA that distribute latest SolveSpace builds, for example:
* https://launchpad.net/~alex-p/+archive/ubuntu/solvespace-trusty2

### Actual behavior

Now there are no any binary distribution or links where can get latest SolveSpace binary for Linux-based OS

**Comment by whitequark** [comment]
This PPA is not updated to SolveSpace 2.3, and recommending a buggy version of SolveSpace isn't good. Besides, it shouldn't live in the README (which is for the source code) but on solvespace.com.
