### ISSUE TITLE
solvespace coordinate reference system

### ISSUE THREAD

**Issue by devds** [solvespace/solvespace#1429]
First of all, I am new in Solvespace.
I draw a 2d sketch
When I switch in 3d view, I would like have a 3d coordinate reference system with Z axis pointing top/up as default ( like Autocad 3d view does).
I mean via C++ code , not from .exe file
Any suggestion?
Thanks in advance

**Comment by ruevs** [comment]
Luuk for turntable navigation on the configuration screen.

**Comment by devds** [comment]
Yes, I know,I just did it.
But,I would like have it by default, via c++ code
Any suggestion for C++ code?

**Comment by ruevs** [comment]
The code is here:

https://github.com/solvespace/solvespace/blob/94618d4ce14a984a5a02398ace853828bb32cda6/src/solvespace.cpp#L81

But we will not make turntable navigation the default.
