### ISSUE TITLE
[Web] Crashes when creating a constraint

### ISSUE THREAD

**Issue by dgramop** [solvespace/solvespace#1435]
### System information

- **SolveSpace version:** master branch ([94618d4](https://github.com/solvespace/solvespace/commit/94618d4ce14a984a5a02398ace853828bb32cda6))
- **Operating system:** Safari, and Chrome

### Expected behavior
Creating a length constraint on a rectangle should not crash

### Actual behavior
Solvespace crashes and shows a web page describing that it crashed

### Additional information
Fixed and described a little further in #1434

**Comment by ruevs** [comment]
Duplicate to https://github.com/solvespace/solvespace/issues/1349

**Comment by dgramop** [comment]
My bad, hastily opened this one after creating a PR without checking for dups
