### ISSUE TITLE
Please trigger a flatpak rebuild

### ISSUE THREAD

**Issue by gdevenyi** [solvespace/solvespace#1437]
The flatpak version of solvespace is built against an old runtime which is now out of support:
https://flathub.org/apps/com.solvespace.SolveSpace

The package hasn't been built in a year, so I think it just need a manual kick.

**Comment by phkahler** [comment]
We will hopefully get version 3.2 out soon but maybe @rpavlik can tell me how to make this happen sooner?

**Comment by phkahler** [comment]
Thanks @rpavlik !!

**Comment by gdevenyi** [comment]
Cheers thanks 👍🏻
