### ISSUE TITLE
Add a clamped distance constraint

### ISSUE THREAD

**Issue by dcousens** [solvespace/solvespace#1450]
This is a feature request/discussion.

Rather than defining an exact distance measurement as a constraint, you could define the `minimum` and `maximum` distance measurements, thereby ensuring a constraint prevents a segment from resolving to an unreasonable state; without needing the design to fall back on an over-constrained design that can be difficult to modify.

**Comment by ruevs** [comment]
This is a duplicate to, or covered by:
https://github.com/solvespace/solvespace/issues/81
https://github.com/solvespace/solvespace/issues/77
https://github.com/solvespace/solvespace/issues/76
https://github.com/solvespace/solvespace/issues/422

It is the first point in the pinned issue above:
https://github.com/solvespace/solvespace/issues/1024

**Comment by dcousens** [comment]
Thanks @ruevs, and sorry for missing that

**Comment by ruevs** [comment]
No problem :-)
