### ISSUE TITLE
Dragging points in standalone solver library

### ISSUE THREAD

**Issue by maxomous** [solvespace/solvespace#1471]
Hi,
I have a question about dragging point entities with the [standalone solver](https://github.com/JacobStoren/SolveSpaceLib) library. 
What is the functionality of:
setting Slvs_System::dragged[] to a point's parameters 
vs 
adding a SLVS_C_WHERE_DRAGGED constraint to that point?

Thanks,
Max

**Comment by ruevs** [comment]
The solver tries to keep parameters that are in the `dragged` list as close as possible to their original values. This makes dragging the (free) entities in the model "nice/unsurprising" for the user.

https://github.com/solvespace/solvespace/blob/2afabadfa5e21ad37dfcac24cf8244e2ffcdbd78/src/lib.cpp#L198
https://github.com/solvespace/solvespace/blob/2afabadfa5e21ad37dfcac24cf8244e2ffcdbd78/src/solvespace.h#L224

The constraint `SLVS_C_WHERE_DRAGGED` on the other hand forces the parameters of the constrained entity (X,Y,Z coordinates) to remain constant.
