### ISSUE TITLE
C++ STL Library, C++ Standard

### ISSUE THREAD

**Issue by gDator** [solvespace/solvespace#1484]
This is just a general question. I try to implement a light feature. As far as I can see there is barley usage of the stl library. Is there a reason for that? 
Also the C++ Standard is 11. So some features (format, numbers, optional, any) are missing
I just want to implement the features to the repository requirements. Thanks in regard.

**Comment by ruevs** [comment]
Welcome to SolveSpace!

SolvesSpace is C++11.

STL is perfectly fine with some exceptions - use it as needed. See here:
https://github.com/solvespace/solvespace/blob/master/CONTRIBUTING.md#libraries

For more development docummentation see https://github.com/solvespace/solvespace/issues/1477#issuecomment-2294917262 and follow the links...
