### ISSUE TITLE
Mouse scroll direction is reversed in Solvespace

### ISSUE THREAD

**Issue by mkyral** [solvespace/solvespace#1488]
### System information

- **SolveSpace version:** 3.1~5528da7f (compiled from source)
- **Operating system:** Gentoo, gtkmm-3.24.9

### Expected behavior

Mouse scroll direction should be consistent with other apps.

### Actual behavior

I'm using latest Solvespace compiled from git. I did not used it for several weeks. Yesterday I've discovered, that scrolling direction in Solvespace is reversed and it is really annoying.

Initially I trough that there was some change in GTK, but inkscape, that also uses gtkmm, works normally. Also Solvespace 3.1 with the same gtkmm works correctly. So change is probably in Solvespace code.

### Additional information

-- Checking for modules 'gtkmm-3.0>=3.18;pangomm-1.4;x11'
--   Found gtkmm-3.0, version 3.24.9
--   Found pangomm-1.4, version 2.46.3
--   Found x11, version 1.8.10

**Comment by ruevs** [comment]
Indeed. Someone reported the same on the forum https://solvespace.com/forum.pl?action=viewthread&parent=5835&tt=1728124046

Since you are compiling from source please change this line:

https://github.com/solvespace/solvespace/blob/5528da7ffbfe511a90c46864da40eec5305a89ae/src/platform/guigtk.cpp#L581

to `delta = -dy;` and see if it fixes the problem.

**Comment by ruevs** [comment]
For cross reference https://github.com/solvespace/solvespace/pull/1464 https://github.com/solvespace/solvespace/pull/1470 https://github.com/solvespace/solvespace/commit/31d0c27ecdc4ace0a1793191629d258cbd861826 https://github.com/solvespace/solvespace/commit/a17fb155ab807bc9d2c26a024bfc8083679ad2eb

**Comment by mkyral** [comment]
> Indeed. Someone reported the same on the forum https://solvespace.com/forum.pl?action=viewthread&parent=5835&tt=1728124046
> 
> Since you are compiling from source please change this line:
> 
> https://github.com/solvespace/solvespace/blob/5528da7ffbfe511a90c46864da40eec5305a89ae/src/platform/guigtk.cpp#L581
> 
> to `delta = -dy;` and see if it fixes the problem.

Yes, this fix the issue.

**Comment by ruevs** [comment]
Fixed here c619fa9f1f5eaaa60eea0f08770a04e703e51115.
