### ISSUE TITLE
Font texture update not working

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#151]
### System information
Windows, OpenGL2
### Expected behavior
Font texture should be updated for each OpenGL context.
### Actual behavior
Font texture updated only for context where new character appears
### Additional information
For native windows OpenGL there are possible to use the same context for different windows, or share context resources by using wglShareLists. Unfortunately, this approach can't work with ANGLE, so we have to support two contexts and update font texture for each of them.

**Comment by whitequark** [comment]
yes, I also noticed this bug, please fix it

**Comment by Evil-Spirit** [comment]
@whitequark,
I have no idea how to make this not using some hacking.
1. The best solution I know is perfrom versioning of the font texture and store it inside pixmapCache.
2. Make copy of the font for each Canvas instance

**Comment by whitequark** [comment]
@Evil-Spirit 2nd sounds OK to me

**Comment by Evil-Spirit** [comment]
@whitequark, OK!? ok :)

**Comment by Evil-Spirit** [comment]
@whitequark, ready

**Comment by whitequark** [comment]
@Evil-Spirit This crashes tests. Why do you not run tests?

**Comment by whitequark** [comment]
Fixed in master.

**Comment by Evil-Spirit** [comment]
@whitequark, I have different build directory, so I have to run tests separately and sometimes forget to do it. Sorry, I just need to reconfigure my building env to build inside repo dir.

**Comment by whitequark** [comment]
@Evil-Spirit OK
