### ISSUE TITLE
Force NURBS surfaces to triangle mesh not working when specified for translation/rotation groups

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#152]
### Version
All versions

### Expected behavior
Force NURBS surfaces to triangle mesh shourd work when specified for translation/rotation groups.

### Actual behavior
Force NURBS surfaces to triangle mesh not working when specified for translation/rotation groups. This is because it not considered when such group are generated (booleans inside group perfromed using NURBS anyway even if we specify force to triangle mesh)

**Comment by Evil-Spirit** [comment]
@whitequark, updated here

**Comment by whitequark** [comment]
Fixed in master.
