### ISSUE TITLE
looks for imesh_texr.frag that no longer gets installed

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#158]
### System information

SolveSpace commit 6c1287681df3e1d3a61e993ef48b8852c7e9300e
on Ubuntu 16.10.

### Actual behavior

When starting, looks for
/usr/local/share/solvespace/shaders/imesh_texr.frag
in vain, aborts.

This seems to have been introduced in 6c1287681df3e1d3a61e993ef48b8852c7e9300e

Note that this failure may not occur when running from the "build" directory, if a
build/res/shaders/imesh_texr.frag
file from an older build is still around.

**Comment by whitequark** [comment]
Fixed in master, thanks!
