### ISSUE TITLE
No any effects for assembled models after change chord tolerance

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#16]
Try open any assembled solid model and switch on "Show triangle mesh of solid model".
After that try change chord tolerance in property browser and you could see that it not take any effects on this meshes.

**Comment by whitequark** [comment]
That's expected behavior. Currently, imported models aren't affected by anything in the sketch they're imported into. This will be changed once we get true hierarchical sketches (not very soon).

**Comment by whitequark** [comment]
See also #233.
