### ISSUE TITLE
center-of-gravity calculation

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#160]
For design of rotating parts, it would be useful to have a centre-of-gravity calculation, with display of a point and its coordinates.

A parametric one would also be interesting. But, if placed into a group with a mesh, this creates a circular dependency. Perhaps it could be restricted to only be placed in sketch in workplane/3d groups.

**Comment by Evil-Spirit** [comment]
@whitequark, What algorithm you can suggest? I know what we have to integrate by volume... I think there is only numeric method we can implement in simple way...

**Comment by whitequark** [comment]
Sure, it can only be numeric, like volume and area calculations.

**Comment by Evil-Spirit** [comment]
@whitequark, circular dependencies is the point of exisnace of the solver...

**Comment by Evil-Spirit** [comment]
@whitequark, volume of an triangle mesh actually is not numerical but exact

**Comment by whitequark** [comment]
But I don't think it will nicely work with the centre-of-gravity constraint because of discontinuities.

**Comment by Evil-Spirit** [comment]
@whitequark, Yes, dymamic volume is quite complex task, but assembly is much simplier and actually can be implemented.

**Comment by whitequark** [comment]
@Evil-Spirit let's start with the simplest thing, just non-parametric display, and then do the complex one if it's really useful.

**Comment by Evil-Spirit** [comment]
@whitequark,
We can use regular 3d grid with fixed step (cubes) or Monte-Carlo approach for performing this kind of integraion.

**Comment by whitequark** [comment]
@Evil-Spirit I trust you to make the right choice. I think a live display that updates when dragging is useful, so that probably should affect the decision.

**Comment by Evil-Spirit** [comment]
@whitequark, No problems here. There is no need to perform numerical integration, we can exactly calculate center of mass of triangle mesh like we done it for volume! http://e-maxx.ru/algo/gravity_center

**Comment by whitequark** [comment]
OK. How expensive is that?

**Comment by Evil-Spirit** [comment]
@whitequark, exactly just like volume calculation.

**Comment by Evil-Spirit** [comment]
@whitequark, implemented here
We can also change volume calculation to simplier one.

**Comment by Evil-Spirit** [comment]
@whitequark, one more time

**Comment by Evil-Spirit** [comment]
@whitequark, actually I have no idea how to test it.

**Comment by whitequark** [comment]
@Evil-Spirit Hm, I want a different UI. Basically recompute it after every regeneration, show a bright dot in the center of the screen, and write the exact coordinates. This constraint is not really useful, without more in-depth solver support I'd have to get the center of mass to the center of rotation manually, which is fine, just make it more convenient.

**Comment by Evil-Spirit** [comment]
@whitequark,
So, you don't need it actually to be as datum point. Just visualization with ability to see coordinates? Can we just introduce checkbox "show mass center of solid model" inside text window?

**Comment by Evil-Spirit** [comment]
@whitequark,OK. What about correctness? Can you suggest samples/method of testing?

**Comment by whitequark** [comment]
@Evil-Spirit I would run some quick checks with shapes where one can calculate it by hand. I've done that in high school but has since forgot everything, hope you haven't..

**Comment by Evil-Spirit** [comment]
@whitequark, updated here

**Comment by Evil-Spirit** [comment]
@whitequark, Now it is more useful
![2017-01-19 00 14 32](https://cloud.githubusercontent.com/assets/1980537/22074856/6487aa94-dddc-11e6-898e-c8dc8f275aa3.png)

**Comment by whitequark** [comment]
Merged
