### ISSUE TITLE
selection of entity from request for dragging doesn't work for circles

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#162]
To reproduce:
  * draw a circle
  * extrude into a cylinder
  * try to change radius

**Comment by Evil-Spirit** [comment]
@whitequark, I've also figured out this when worked on not hovering of the pending...

**Comment by Evil-Spirit** [comment]
@whitequark, fixed here

**Comment by whitequark** [comment]
Merged in master, thanks
