### ISSUE TITLE
"Show Degrees of Freedom" highlights should be drawn over the mesh

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#163]
Otherwise it is easy to miss some of them. I think both the cyan dot and the green point should be overlaid.

**Comment by Evil-Spirit** [comment]
@whitequark, did you mean something like this?
![2017-01-20 10 02 25](https://cloud.githubusercontent.com/assets/1980537/22134164/a910f0aa-def7-11e6-937b-b0f1f1649936.png)

**Comment by whitequark** [comment]
@Evil-Spirit yes

**Comment by whitequark** [comment]
Fixed in master
