### ISSUE TITLE
make arc-center relation "explorable"

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#165]
Now that we can follow the relation between items and constraints, it would be nice if one could do the same for arcs and their center point. (The same would apply for circles, and possibly other items with "special" points.)

Right now, the center point is shown in the text window just as "POINT", without indication that it is the center of an arc. It would be nice if one could 1) tell that it is special, e.g., by calling it "CENTER POINT" or such, or maybe displaying a center-of-arc constraint (if that makes sense), and 2) reach the point from the arc and vice versa, much like we can now reach items through the constraints that connect them.

**Comment by wpwrak** [comment]
I forget an even more common case: the endpoints of lines.

**Comment by Evil-Spirit** [comment]
@whitequark, implemented here

**Comment by wpwrak** [comment]
Thanks ! Here's a fix for a little typo:
https://github.com/wpwrak/solvespace/commit/782a5bbbe61c0a1e5326d55218de33e6a7682f26

I also found this extra semicolon, which already existed before #165. I'm not sure if this is a safe change, though, or if something may depend on that typo:
https://github.com/wpwrak/solvespace/commit/a77cedbfd8dedd147fb59ebf9af936f4259ff31b

**Comment by Evil-Spirit** [comment]
@wpwrak, thank you :) We've found this semicolon a long time ago, but I forgot to fix it.

**Comment by wpwrak** [comment]
By the way, along the lines of explorability, how about something like this ? https://github.com/wpwrak/solvespace/commit/41e55b3d79f7d2df61fb9db0b494ff09a37d6add
(My ultimate goal in this quest of mine is to be able to perform the deletion in #182 without losing any groups, and this should bring me a little closer to being able to rearrange the dependencies.)

**Comment by whitequark** [comment]
FWIW I haven't merged the patch because the UI work in it is horrible. It's completely inconsistent with the rest of text window stuff.

**Comment by Evil-Spirit** [comment]
@whitequark, what do you mean?

**Comment by ruevs** [comment]
I agree with @whitequark that the proposed implementation was too intrusive and inconsistent with the style of the UI code for the test window. Here https://github.com/solvespace/solvespace/pull/1182 is a clean implementation with minimal intrusiveness.

Whether the style of the UI code is nice or not is another question. I'm split on this...

**Comment by Symbian9** [comment]
> I agree with `@whitequark`

@ruevs, just a reminder, `@whitequark` asked to not cast (mention/trigger) she in SolveSpace related threads anymore.

**Comment by ruevs** [comment]
OK thanks.
