### ISSUE TITLE
refresh file from the CLI

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#166]
Scenario: part A is assembled from part B, and B in turn is assembled from part C, each in its own .slvs file.
After changing c.slvs, b.slvs has to be updated (loaded and saved) before the changes become visible in A.

Supposedly, resolving all such dependencies properly would require all of https://github.com/solvespace/solvespace/issues/80 i.e., a lot of work.

However, it would seem that, as a work-around, one could just express such dependencies in a (manually created and maintained) Makefile and do the updates manually. The Makefile would ensure that no update is missed. To automate this a bit more, it would be useful to have the ability to load a .slvs file, picking up any changes in parts it directly depends on, and then save the updated version.

**Comment by whitequark** [comment]
Done in master, command "regenerate".
