### ISSUE TITLE
constraints with parameter don't working for solver library

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#172]
### Expected behavior

Param should be generated and stored inside Constraint just like for Entity.

### Actual behavior

Param for Constraint is generated just for SolveSpace and no any way to specify it inside solver library

**Comment by Evil-Spirit** [comment]
@whitequark, look here

**Comment by Evil-Spirit** [comment]
@whitequark, updated here

**Comment by whitequark** [comment]
Fixed in master.
