### ISSUE TITLE
if a constraint is selected, prioritize it for starting a drag

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#174]
Lately, I'm having a lot of difficulties dragging distances. Selecting them is fine. I'm not entirely sure if it's because I unlearned some movement that happens to work better, or simply because my designs are getting more crowded.

When trying to drag a distance, I typically aim first for the text. If that doesn't work, I try to get the line(s) to the item being sized.

Perhaps the dragging function could, when deciding what to do with the drag movement, give preference to the item already selected.

**Comment by whitequark** [comment]
@wpwrak do you have any sketch where this is reproducible? Please also post a screenshot with position/zoom settings that reproduce the issue.

**Comment by wpwrak** [comment]
Here is one:
http://downloads.qi-hardware.com/people/werner/slvs/drag-diam-hard.png
The cursor (alas, xwd can't show it) is over the center of the circle-with-slash. Pressing the left button and dragging does nothing.

The .slvs is simple enough:
http://downloads.qi-hardware.com/people/werner/slvs/drag-diam-hard.slvs

**Comment by whitequark** [comment]
confirmed

**Comment by Evil-Spirit** [comment]
https://github.com/Evil-Spirit/solvespace-master/commit/3c8cc2e3cf22aad8546da4682938077df08e7361

**Comment by baryluk** [comment]
Same here. I have a line-distance constrain selected, but I can't drag it, because it is overlapping with line behind it I guess. It happens even if the constrain is a reference value.

I am using git master 16c5fa6889202f2059b52c4a89599910541dd1a0

**Comment by baryluk** [comment]
@Evil-Spirit I can confirm that the patch from https://github.com/Evil-Spirit/solvespace-master/commit/3c8cc2e3cf22aad8546da4682938077df08e7361 fixes the issue.

I do not know if it is the correct solution, but it does fixes this particular problem for me.

The patch is not really in mergable state tho. It should just remove the commented code, not comment it out. :D Or fix the logic there, otherwise it looks a bit more like a hack.

**Comment by phkahler** [comment]
IMHO that patch is no good. It eliminates the ability to drag entities from prior groups. Normally if you extrude a rectangle you can push or pull the "new" end to change the length, while dragging points or lines of the original rectangle can change the width or height. The patch eliminates the option for the later - resizing the underlying sketch from the extrusion group.

**Comment by phkahler** [comment]
BTW if it's the same this is really easy to reproduce. Draw a circle, press "d" and type in 10. The diameter will be positioned right in the middle of the circle and will be really hard to move. It highlights correctly when hovered, but often will refuse to drag. Is worse with small circles, hence typing 10 for diameter on default view.

**Comment by phkahler** [comment]
Can anyone confirm the fix in PR #672  fixes this on Windows and OSX? It's good on Linux.

**Comment by nabijaczleweli** [comment]
Confirmed on Windows.

**Comment by phkahler** [comment]
@nabijaczleweli Thanks!
