### ISSUE TITLE
"Unselect hovered" is broken

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#179]
It just never appears anymore.

**Comment by Evil-Spirit** [comment]
@whitequark, this works for me

**Comment by whitequark** [comment]
@Evil-Spirit Try this:
  1. New file
  2. Draw a rect
  3. Click on top line
  4. Hover over top line and right-click

**Comment by whitequark** [comment]
@Evil-Spirit Oh... I've just realized "Unselect Hovered" doesn't appear unless more than one entity is selected. Nevermind.

cc @wpwrak

**Comment by wpwrak** [comment]
Hmm, but even if selecting two lines of the rect, I don't see any "Unselect Hovered", just "Unselect All":
![no-unselect-hovered](https://cloud.githubusercontent.com/assets/1292352/22531579/a452b44a-e8c0-11e6-803a-16e5de608cae.png)

**Comment by whitequark** [comment]
@wpwrak Are you really hovering the top line? The menu seems quite far from it.

**Comment by wpwrak** [comment]
Yes, the line pales with fear as the mouse pointer approaches. Alas, it turns regular red again when right-clicking, so one can't see that in the screenshot.

By the way, for this type of debugging, it may be useful to have an option somewhere (could be on the command line), to make SolveSpace draw a cursor (maybe X-shaped), so that it is included in the screenshot.

**Comment by whitequark** [comment]
> By the way, for this type of debugging, it may be useful to have an option somewhere (could be on the command line), to make SolveSpace draw a cursor (maybe X-shaped), so that it is included in the screenshot.

This is really the responsibility of your screenshot program. Both GNOME and KDE provide such an option, for one.

**Comment by wpwrak** [comment]
Sigh, all that modernism (using xwd here) ... here we have one with cursor, courtesy of "screengrab":
![no-unselect-hovered-cursor](https://cloud.githubusercontent.com/assets/1292352/22533553/87bbee84-e8cd-11e6-9ca9-4ee635812ff5.png)

**Comment by whitequark** [comment]
@wpwrak can you please use gdb to trace GraphicsWidget::{on_motion_notify_event,on_button_press_event,on_button_release_event} calls?

**Comment by whitequark** [comment]
@wpwrak can you still reproduce this?

**Comment by whitequark** [comment]
No response in two years, closing.
