### ISSUE TITLE
nanovg (rendering lib)

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#180]
### Expected behavior
Antialiased canvas representation
* https://github.com/memononen/nanovg

### Actual behavior
For non-retina display current rendering engine not give antiallise

**Comment by whitequark** [comment]
Your suggestions are really not helpful. Why do you think a proper solution to an issue with antialiasing is to completely replace our rendering backend? And moreover, the display scale factor makes absolutely no difference to the rendering pipeline--the platform-independent code is not even aware of this.

If you have a specific issue with antialiasing, you are welcome to post an issue that confirms it, with screenshots.
