### ISSUE TITLE
Exported DXF files are unreadable by QCad, A360, DraftSight

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#187]
See this thread: http://solvespace.com/forum.pl?action=viewthread&parent=1741.
I suspect 99d6f1f is the cause but don't understand why.

**Comment by Evil-Spirit** [comment]
@whitequark, may be this can help... https://github.com/Evil-Spirit/libdxfrw/commit/f3f38c723d1e333e871b5f1a7360a26aa41f81ec

**Comment by Evil-Spirit** [comment]
@whitequark, with inkscape still the problem.. I can't find where dxf import source of inkscape. This can help.

**Comment by whitequark** [comment]
@Evil-Spirit It's a bunch of disgusting Python code here: https://github.com/inkscape/inkscape/blob/bzr-original/share/extensions/dxf_input.py

**Comment by whitequark** [comment]
@Evil-Spirit I merged your fix, except I don't mark the POLYLINE as 3d if every point has Z exactly at zero. This still doesn't work with Inkscape, probably because its DXF import is badly written. We have SVG export anyway, so I don't consider this a priority.

**Comment by whitequark** [comment]
This fixed DraftSight and QCad, so I believe that's the root cause. Let's backport this to 2.x...

**Comment by whitequark** [comment]
Apparently still some problems in QCad... http://solvespace.com/forum.pl?action=viewthread&parent=1741

**Comment by Evil-Spirit** [comment]
@whitequark, I can't reproduce it for QCad. Probably, not the same version or somthing else. I have BircsCAD, NanoCAD, DWG TrueView, LibreCAD, QCad, Inkspace installed and perform testing with them...

**Comment by whitequark** [comment]
@Evil-Spirit Can you confirm that export works properly with everything except Inkscape??

**Comment by Evil-Spirit** [comment]
@whitequark, OK I am testing with the last master now... Wait 10 minutes.

**Comment by Evil-Spirit** [comment]
@whitequark, All is working except Inkscape.
`1 ENTITIES of type POLYLINE encountered and ignored. Please try to convert to Release 13 format using QCad.`

**Comment by whitequark** [comment]
Which version of QCad are you using?

**Comment by Evil-Spirit** [comment]
@whitequark, 3.13 free version

**Comment by Evil-Spirit** [comment]
@whitequark, may be I should try install commercial trial...

**Comment by whitequark** [comment]
@Evil-Spirit in Qcad 3.16.4 (trial) actually I don't get a rectangle at all.

**Comment by Evil-Spirit** [comment]
@whitequark, I have no this problem in windows. Can you attach dxf?

**Comment by Evil-Spirit** [comment]
![2017-02-06 16 31 39](https://cloud.githubusercontent.com/assets/1980537/22641561/d337a1cc-ec89-11e6-89d2-9574d31c39df.png)

**Comment by whitequark** [comment]
@Evil-Spirit Oh, interesting. I found that Qcad misreads SolveSpace's DXF files, but *only* when the paid addon is activated.

As for a file, just draw a single rectangle, that was enough to me.

**Comment by Evil-Spirit** [comment]
@whitequark, So you are meaning what this can be just QCad bug?

**Comment by whitequark** [comment]
Maybe... Teigha is produced by ODA, which includes Autodesk. Can you try https://www.opendesign.com/guestfiles/TeighaFileConverter ?

**Comment by Evil-Spirit** [comment]
Teigha is used by BricsCAD and nanoCAD. They are open files smoothly...

**Comment by whitequark** [comment]
OK, then it's a QCad bug.
