### ISSUE TITLE
Exported DXF files are not readable for RDWorks

### ISSUE THREAD

**Issue by Leichtbier** [solvespace/solvespace#188]
Since SolveSpace 2.1 I'm no longer able to use the exported DXF files with RDWorks (a software for my laser cutter).

You can get the software here:
[http://www.thunderlaser.com/download/down/RDWorksV8.rar](url)

I had the same problem with inkscape, but that seems to be fixed. My current workaround is to save as svg and than convert to dxf.
Solvespace is a realy nice programm fore laser cutting and a even nicer with this functionality ^^

**Comment by Evil-Spirit** [comment]
@Leichtbier, I have tried this and have no problem to import dxf in RDWorks.
But with Inkspace still the trouble... You can also look here https://github.com/solvespace/solvespace/issues/187

**Comment by Evil-Spirit** [comment]
@Leichtbier, can you attach slvs example and way to reproduce bug?

**Comment by Evil-Spirit** [comment]
![2017-02-04 23 53 10](https://cloud.githubusercontent.com/assets/1980537/22620022/249a313e-eb35-11e6-8a55-7b635a53806c.png)

**Comment by whitequark** [comment]
@Leichtbier ping?

**Comment by Leichtbier** [comment]
Pong ^^ I've tryed it yesterday with the newest version of RDWorks and now it works again. Thank you for soliving my problem.
