### ISSUE TITLE
libgtkmm-3.0-dev dependency

### ISSUE THREAD

**Issue by holocronweaver** [solvespace/solvespace#190]
When building on Ubuntu 16.04, in addition to the dependency packages listed on the README, I also needed `libgtkmm-3.0-dev` to satisfy CMake. Probably should add it to the list?

**Comment by whitequark** [comment]
Um.
![screenshot_20170206_101944](https://cloud.githubusercontent.com/assets/54771/22643312/cca28f18-ec55-11e6-90fe-cb2f59cc1133.png)

**Comment by holocronweaver** [comment]
Ah, it wasn't caught in my c/p. My bad.
