### ISSUE TITLE
custom style on comment causes occlusion

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#192]
solvespace master (1871efa), plus local changes (non-interfering)

Comments are normally not occluded by solids. However, if setting a custom style, they are - and you can't even turn it off.

Reproduce:
- create rectangular solid: File > New, R, extrude
- add comment somewhere in space
- rotate things and observe that the comment is always visible, also when behind the solid
- select comment and assign new style

Occlusion is now applied to the comment. This is independent from the occlusion setting (rightmost icon in text window).

![style-occlusion](https://cloud.githubusercontent.com/assets/1292352/22727855/e6f76338-edb9-11e6-9a34-7efeaa4b17c3.png)

Expected behaviour: either always show comments (like measurements or when using the default style), or apply the occlusion setting.

**Comment by whitequark** [comment]
This is a regression in 3.0; 2.x used to draw comments, even with custom style, over all other geometry.

**Comment by Evil-Spirit** [comment]
@whitequark, fixed here

**Comment by whitequark** [comment]
Fixed in master.
