### ISSUE TITLE
deletion does not report point reuse

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#196]
When deleting items, there is no warning if this removes points directly (i.e., not through a constraint) referenced in later groups.

solvespacer master (f29d9d7)

- New
- draw a random line
- create new group with its workplane anchored at a point that's not on that line (e.g., the origin)
- draw a circle centered at one of the line's endpoints
- we now have one DOF
- go back to the first group (g002-sketch-in-plane)
- delete the line, no warning
- go back to the circle (g003-sketch-in-plane)
- we now have three DOF

This is part of a larger cluster of issues of SolveSpace not always indicating clearly dependencies caused by point reuse.

**Comment by whitequark** [comment]
This is working as intended; solvespace explicitly ignores trivial constraints (generate.cpp:335) since otherwise deleting any request would result in the warning.
