### ISSUE TITLE
neither "In Workplane" nor "Anywhere in 3d"

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#198]
#197 has a nihilistic counterpart that is easier to reproduce:

- New
- assemble oled13.slvs (probably works with any assembly)
- select Sketch > In Workplane (which is already marked as selected)
- click away the complaint
- open Sketch > and behold ...

![nihilistic-workplane](https://cloud.githubusercontent.com/assets/1292352/22837567/ffe98fbe-ef9f-11e6-92ec-02da3b3af686.png)

**Comment by whitequark** [comment]
Same underlying issue as #197.
