### ISSUE TITLE
why does lathe produce three DOF ?

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#202]
"New group rotating active sketch" aka "lathe" produces a group with three DOF. I tried to pull and twist, but nothing seems to be willing to move. So what are these three DOF ?

I asked @whitequark on #solvespace, and they didn't have an answer either.

**Comment by whitequark** [comment]
@Evil-Spirit any ideas?

**Comment by Evil-Spirit** [comment]
@whitequark revolution axis direction parameters is created when generating lathe group... I probably made this like it was made for extrusion group but now it is obvious what this is not the right solution because we can't drive some parameters of the previous group...

**Comment by Evil-Spirit** [comment]
@whitequark, This is probably bug, so we have to remake this in correct way.

**Comment by Evil-Spirit** [comment]
@whitequark, fixed here

**Comment by wpwrak** [comment]
Works great here. This was the last step to achieving the 0 DOF goal for my design :) Thanks !

**Comment by Evil-Spirit** [comment]
@wpwrak, Thank YOU, because your bugreports are the best and you provide a lot of useful information :) I hope you will keep going because this makes the project better!

**Comment by whitequark** [comment]
I second what @Evil-Spirit says.

**Comment by whitequark** [comment]
Fixed in master.
