### ISSUE TITLE
choice of active group when saving has puzzling effect on assemblies

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#205]
When saving a design when a group other than the last one is activated, items in the groups following it are not available in assemblies. I think this is not intended, and it's rather confusing.

Using solvespace/master (e6ed36) with various recent fixes and improvement from @Evil-Spirit and myself.

First, make a simple design with more than one group:

- File > New
- draw a line at roughly 45 degrees
- create a new group, with workplane parallel to default
- draw a rectangle through the endpoints of the line
- File > Save (as a.slvs)

Then assemble it:

- File > New
- assemble a.slvs
- the screen should look like this:
![activate-vs-assembly-good](https://cloud.githubusercontent.com/assets/1292352/23023464/7c5d83dc-f434-11e6-98a9-3d8f0ac9904f.png)

Now change the active group:

- File > Open a.slvs
- activate g002
- File > Save

Assemble again (or reload, etc.). The screen now looks like this:
![activate-vs-assembly-bad](https://cloud.githubusercontent.com/assets/1292352/23023489/9af51e36-f434-11e6-92ca-e6f9109be88b.png)

Detecting the problem is quite hard since loading a.slvs (to look for incorrect settings) yields this perfectly normal-looking result:
![activate-vs-assembly-gotcha](https://cloud.githubusercontent.com/assets/1292352/23023541/e0c5463e-f434-11e6-885e-4ad7ac8ab34b.png)

**Comment by whitequark** [comment]
No, this is expected. It works in exactly the same way as hiding groups then saving and linking the file. It will work this way until #80.

**Comment by wpwrak** [comment]
Nice rationalizing ;-) But it doesn't work the same: if you hide groups through "show", etc., this information is preserved when you load the file, so you can make the connection between "show" and availability of items in an assembly fairly easily. But if you hide them through activation, this is hidden by SolveSpace activating the last group when loading the file.

So when the user looks at a file with that problem, they see a state that looks identical to one that does not have the problem. And it's hard to guess that activation (which one would think of as simply an act of selecting, much like, say, picking a sheet in a spreadsheet, with the non-availability of later groups being merely a side-effect) has this "magic" consequence.

E.g., it took me about a month to figure this out. Before I was able to connect the dots, my mental image was that assembling is "lossy", suspecting that this information loss somehow be linked to extrusion.

**Comment by whitequark** [comment]
@wpwrak Regardless of whether you have a good argument I don't think this can be fixed before #80...
