### ISSUE TITLE
Creation of TTF and image requests uses wrong points

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#208]
The text window prompts first for "top left corner" then "bottom left corner" but neither of those is actually dragged.

**Comment by Evil-Spirit** [comment]
@whitequark , updated here. Because of solver way to solve equations the diagonal point is stay at the same place, so I decided to change  dragged point and rewrite the text. What should I do with translations?

**Comment by whitequark** [comment]
Fixed in c9397ea. Thank you.
