### ISSUE TITLE
Text boxes are garbled during editing

### ISSUE THREAD

**Issue by jsmaniac** [solvespace/solvespace#213]
### System information

SolveSpace version: (e.g. 3.0~911c67b2)

Operating system: NixOS 16.09 with custom up-to-date package from https://github.com/jsmaniac/nixpkgs/commit/d6f925d7c1ce29c2099e10dcbdb10628c1c63be1

### Expected behavior

What should have happened?

Text display shouldn't be garbled while editing it

### Actual behavior

Initially:
![initially](https://cloud.githubusercontent.com/assets/299872/24053241/b5023834-0b38-11e7-9c26-c22323c58b07.png)

After clicking "change" (all fine):

![after-clicking-change](https://cloud.githubusercontent.com/assets/299872/24053253/be1927de-0b38-11e7-84fa-a7a390bb1eb3.png)

After typing Hello (garbled display as soon as a key is pressed):
![after-pressing-enter](https://cloud.githubusercontent.com/assets/299872/24053275/cf857162-0b38-11e7-95ce-621fa5cb6e5e.png)

After pressing Enter (display is back to normal, editing did work):
![after-typing-hello](https://cloud.githubusercontent.com/assets/299872/24053262/c8a183cc-0b38-11e7-935b-3126c14133a3.png)

### Additional information

Likely to be relevant library versions:

* fltk-1.3.3
* cairo-1.14.6
* mesa-12.0.4
* freetype-2.6.5
* fontconfig-2.11.1

**Comment by whitequark** [comment]
> fltk-1.3.3

FLTK? SolveSpace uses GTK. Anyway, the problem you're observing is related to the theme you're using, and is the same as https://github.com/solvespace/solvespace/issues/184. Try installing a GTK theme.

**Comment by jsmaniac** [comment]
I had updated an existing recipe for my OS, and solvespace 2 used FLTK. I should remove it from the dependencies.

Thanks for the pointer (I'm using Enlightenment 0.16, and it's not the first time I've seen missing stuff due to the lack of a GTK theme).

**Comment by whitequark** [comment]
> I had updated an existing recipe for my OS, and solvespace 2 used FLTK. I should remove it from the dependencies.

Actually, no SolveSpace release used FLTK. There was a brief time when the open-sourced code had an FLTK implementation, but it was essentially unusable.

**Comment by whitequark** [comment]
Incidentally, this is now fixed properly in master.

**Comment by jsmaniac** [comment]
Sorry about the delay, I tested the latest (827f54f) commit on master, and the fix works perfectly. Thanks!
