### ISSUE TITLE
A better way to extrude contours derived from another contour

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#222]
This [Twitter thread](https://twitter.com/FioraAeterna/status/849621919938650113) describes the problem quite well.

**Comment by Evil-Spirit** [comment]
@whitequark, Is this about drawing over the existant sketch like here https://www.youtube.com/watch?v=doxckvfLUKQ?

**Comment by Evil-Spirit** [comment]
@whitequark 3:29
