### ISSUE TITLE
Dispaly area of closed polygons

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#228]
This https://github.com/Evil-Spirit/solvespace-master/commit/21a8ebe6f5431bb61c9c2a4d9a173bad81028a67 commit introduces showing closed polygon areas. This is useful for some architectural plans or building modeling.

![2017-04-06 20 04 04](https://cloud.githubusercontent.com/assets/1980537/24755412/4e63b48c-1b04-11e7-9c00-0740de4be266.png)

**Comment by whitequark** [comment]
Looks good to me.

**Comment by whitequark** [comment]
Merged in master.
