### ISSUE TITLE
Circle is not visible when radius is negative

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#229]
![2017-04-06 20 25 59](https://cloud.githubusercontent.com/assets/1980537/24756292/60912b00-1b07-11e7-9250-038e011d1846.png)

**Comment by whitequark** [comment]
I don't think this is a bug. We allow all kinds of degenerate constraints, like line segments with length 0, and so on. It seems odd to prohibit those in some cases (like when specified explicitly) but not others (when they're inferred from other constraints).

**Comment by Evil-Spirit** [comment]
@whitequark but this must show circle curve at least

**Comment by whitequark** [comment]
Wait. How did you even manage to make a circle with negative radius?

**Comment by Evil-Spirit** [comment]
I made two pt-on-circle and drag them in some unusal way

**Comment by whitequark** [comment]
Oh, this is basically the same problem as constraint chirality, except applied to a circle.

**Comment by whitequark** [comment]
We should probably rather fix this on the solver level, so that this is not possible.

**Comment by Evil-Spirit** [comment]
@whitequark yes, the equation for pt-on-circle can be rewritten
`AddEq(l, du->Square()->Plus(dv->Square())->Sqrt()->Minus(r), 0);`

**Comment by Evil-Spirit** [comment]
instead of 
`AddEq(l, ((du->Square())->Plus(dv->Square()))->Minus(r->Square()), 0);`

**Comment by whitequark** [comment]
Fixed in master.
