### ISSUE TITLE
Using paste transform with scale -1 does not flip arcs

### ISSUE THREAD

**Issue by Helios747** [solvespace/solvespace#234]
### System information

SolveSpace version: 3.0~5d7b428

Ubuntu 16.10 x64

### Expected behavior

Arc should have been flipped like this

[flipped arc
](http://i.imgur.com/pI3PLDn.png)
### Actual behavior

[No flip](http://i.imgur.com/WOp8qFd.png)

### Additional information

[arc_flip_bug.zip](https://github.com/solvespace/solvespace/files/915262/arc_flip_bug.zip)

**Comment by whitequark** [comment]
Fixed in e5259d7.
