### ISSUE TITLE
Font oops, 

### ISSUE THREAD

**Issue by romeojulietthotel** [solvespace/solvespace#243]
### System information

SolveSpace version: git v2.3

Operating system: Linux

### Expected behavior

What should have happened?
No oops.

What actually happened?

Was trying out the text feature and it oopsed.

### Additional information

freetype: cannot set character size: invalid pixel size
oops at line 261, file /b/b/solvespace/src/ttf.cpp

**Comment by whitequark** [comment]
That's not git master. The line 61 of ttf.cpp in master does not have a call to `oops`. What is the exact git revision you're using?

**Comment by romeojulietthotel** [comment]
I oopsed, I had switched to v2.3. I updated the issue.

**Comment by romeojulietthotel** [comment]
git master 3.0~50789079

```
line 349, function AspectRatio:
Assertion 'Expected font face to be loaded' failed: 
((fontFace != NULL) == false)
```

I was trying the different fonts and when selecting a font I got that.

**Comment by whitequark** [comment]
Which font? Also, post all messages, not just the crash.

**Comment by romeojulietthotel** [comment]
There is more than one font that causes the assert. Here's one:
clR6x12.pcf a.k.a. Clean

**Comment by whitequark** [comment]
Well, how do I obtain this font?

**Comment by romeojulietthotel** [comment]
Depends on your os but on linux it's in a font package.

**Comment by whitequark** [comment]
If you expect me to fix this, please provide the font.

**Comment by romeojulietthotel** [comment]
Ok, for what linux distro?

**Comment by whitequark** [comment]
I run Debian. You could also just provide the file.

**Comment by romeojulietthotel** [comment]
https://packages.debian.org/jessie/all/xfonts-base/filelist

**Comment by romeojulietthotel** [comment]
>If you expect me to fix this,

FWIW I don't expect anything. I try to offer help. Maybe you are suffering from those people that seem to think they are entitled. That's a trap I see maintainers fall into and it's not fair to the maintainer.

It takes time to file reports and it takes time to fix them. It also takes time to learn an application. I am doing what I can. Thanks for your efforts. Together we make the app better.

**Comment by whitequark** [comment]
Okay, I have that package installed on my system, and I have `/usr/share/fonts/X11/misc/clR6x12.pcf.gz`. I cannot select it from the font list though, how did you achieve that? It seems that on my machine fontconfig does not return pcf fonts for some reason.

**Comment by whitequark** [comment]
I found some other fonts that exhibit the same issue (they all start with "STIX" on my machine; not sure what are these fonts), and it is fixed as of 280d5b90.

**Comment by romeojulietthotel** [comment]
FWIW, I think fc-cache has to be run for new fonts. But I'd expect that to happen on install.

**Comment by romeojulietthotel** [comment]
This does not fix the issue.

**Comment by whitequark** [comment]
Are you sure you've rebuilt the binaries? What is the complete content of messages printed to stdout?

**Comment by romeojulietthotel** [comment]
Error now:
 ```
line 350, function AspectRatio:
Assertion 'Expected font face to be loaded' failed: ((fontFace != NULL) == false)

```

**Comment by whitequark** [comment]
What is the complete content of messages printed to stdout? You've only posted the error, not the preceding messages...

**Comment by whitequark** [comment]
> FWIW, I think fc-cache has to be run for new fonts.

I've tried rerunning fc-cache and it does nothing to make that font available for use.
