### ISSUE TITLE
Feature Request: Rotate camera around Up axis

### ISSUE THREAD

**Issue by tilya2014** [solvespace/solvespace#244]
In most of 3d editors user can fix camera to rotate around one axis. Can somebody add this option to solvespace. I've changed this in my sources and its working, but I think that should be optional. 

Version: 3.0~7544d016
solvespace-core/mouse.cpp line 133
```
        ....
        Vector up = Vector::From(0,0,1);
        if(!(shiftDown || ctrlDown)) {
            double s = 0.3*(PI/180)*scale; // degrees per pixel
	    projRight = orig.projRight.RotatedAbout(up, -s*dx);
            projUp = orig.projUp.RotatedAbout(orig.projRight, s*dy);
           ....

```

**Comment by whitequark** [comment]
Is this the same as #123?

**Comment by tilya2014** [comment]
Yes it is. I didn't notice. Thanks
