### ISSUE TITLE
background color of property window

### ISSUE THREAD

**Issue by tgirod** [solvespace/solvespace#247]
Property window's background is black, same as main window's background. Without a border around the property window, it is hard to distinguish the two windows from each others.

![capture d ecran de 2017-04-29 09-49-00](https://cloud.githubusercontent.com/assets/130746/25553965/e4ee18ba-2cc1-11e7-8092-e9fadd7be30b.png)

As a result, I often find myself clicking on the property window when trying to move the view around, which is annoying.

Adding a small border around the property window would help, or maybe changing the background color ...

**Comment by whitequark** [comment]
> Adding a small border around the property window would help

On Linux, this is the responsibility of the window manager. In my case, the window manager, i3, draws a nice thick border:
![screenshot_20170429_080433](https://cloud.githubusercontent.com/assets/54771/25554033/cf33883e-2cb2-11e7-8814-cb24ec8db994.png)

Therefore I suggest you configure your window manager to do the same. I don't know what DE that is or how does one configure it that way.

**Comment by tgirod** [comment]
fair enough !
