### ISSUE TITLE
weird behaviour with imported dxf

### ISSUE THREAD

**Issue by tgirod** [solvespace/solvespace#253]
### System information

SolveSpace version:  2.3~7c1ca460

Operating system: archlinux

### All is fine ...

I'm importing a vectorized (dxf) tree. The shape has nice closed contours and everything is fine.

![fine](https://cloud.githubusercontent.com/assets/130746/25723075/dcb2109e-3116-11e7-9a17-ddb4afe48e13.png)

### But then ...

Now, if I add a rectangle around this shape, I should get the negative shape, right ? But this is what I get instead.

![bug](https://cloud.githubusercontent.com/assets/130746/25722958/577448c0-3116-11e7-9134-cac685ef4ad9.png)

It makes no sense to me. Here is the culprit.

[arbre.slvs](https://github.com/solvespace/solvespace/files/977430/arbre.txt)

**Comment by whitequark** [comment]
That's because the style of the inner lines is different from the style of the rectangle (as we import DXF styles as they are). I'm not sure what's best to do here...

**Comment by tgirod** [comment]
OK, I've just discovered the existence of styles in SolveSpace 👍 

Knowing this, it was trivial to solve the problem by selecting everything and removing assigned style. Thanks !
