### ISSUE TITLE
Emulate right mouse button on OSX

### ISSUE THREAD

**Issue by damian0815** [solvespace/solvespace#254]
Solvespace is awkward to use on an OSX laptop without an external mouse because of the requirement for right-clicking to perform certain operations.

Solvespace should offer right-mouse-button emulation, for example by interpreting Ctrl-Click as Right click.

**Comment by whitequark** [comment]
Would [this](https://github.com/solvespace/solvespace/issues/68) solve your problem?

**Comment by whitequark** [comment]
ping?

**Comment by damian0815** [comment]
I think so. In the meantime I have discovered that a two-finger click+drag works like a right-click+drag based on the way I have my system configured.
