### ISSUE TITLE
Remove hard coded text in order to allow translation

### ISSUE THREAD

**Issue by patrovite** [solvespace/solvespace#258]
### System information

SolveSpace version: 3.0....
Operating system: XUbuntu 16.04LTS

### Expected behavior

With French translation all the text must be French.

### Actual behavior

After the French translation has been finished texts in the property browser are still in english

**Comment by whitequark** [comment]
Yes, the much needed property browser rendering rework...

**Comment by patrovite** [comment]
Are you planning to do a global rework on the property browser or you only want to work on the hard coded text? If it's the second choice, I can help you.

**Comment by whitequark** [comment]
The former. There are more bugs like https://github.com/solvespace/solvespace/issues/92 and https://github.com/solvespace/solvespace/issues/250 and others maybe...
