### ISSUE TITLE
README.md - XCode has to be installed via AppStore; it requires a free Apple ID but the Developer Version works too

### ISSUE THREAD

**Issue by ss0git** [solvespace/solvespace#269]
### System information

Operating system: macOS

### Expected behavior

XCode has to be installed via AppStore; it requires a free Apple ID.

### Actual behavior

Xcode can also be installed from a Developer Account too - https://developer.apple.com/download/

### Additional information

After you drag it to Applications you have to open it and go to Preferences - Locations - Command Line Tools and select you Xcode version from there. You should be ok now.

**Comment by whitequark** [comment]
0b79dc277e86f536736669e273576738e290d76a
