### ISSUE TITLE
Min/Max constraints for angle

### ISSUE THREAD

**Issue by foror** [solvespace/solvespace#273]
SolveSpace doesn't have collision physics, but it can be simulated by minimum and maximum constraints at angle.

**Comment by Evil-Spirit** [comment]
Actually, this must be performed for valA of the constraints with dimension values.

**Comment by Symbian9** [comment]
This feature requested already
* https://github.com/solvespace/solvespace/issues/81

**Comment by whitequark** [comment]
Closing as duplicate

**Comment by Evil-Spirit** [comment]
@foror, Solved here https://github.com/solvespace/solvespace/issues/81
