### ISSUE TITLE
Wrong detection of redundant constraint #2

### ISSUE THREAD

**Issue by alxv-su** [solvespace/solvespace#274]
### System information

SolveSpace version: 2.3~

Operating system: Linux Mint Debian Edition 2 Betsy (using repos from Debian Jessie)

### Expected behavior

Program should solve sketch correctly with any distance value.

### Actual behavior

Solve failed if distance greater than 2645 (see screenshots).

### Additional information

Screenshots:
![bug](https://user-images.githubusercontent.com/11207565/28577378-af407d6c-7167-11e7-900c-88d0a8117f97.png)
![ok](https://user-images.githubusercontent.com/11207565/28577383-b1cb4436-7167-11e7-8057-d53404aa8953.png)
Problematic files: [bug-distance.zip](https://github.com/solvespace/solvespace/files/1173487/bug-distance.zip)

**Comment by whitequark** [comment]
This is already fixed in the `master` branch.

**Comment by whitequark** [comment]
(Even if it wasn't, integrating the code in #225 would fix bugs of this sort as well.)
