### ISSUE TITLE
[FEATURE] Eradicate single button message boxes

### ISSUE THREAD

**Issue by tioteath** [solvespace/solvespace#293]
### System information

SolveSpace version: (impossible to copy-paste from Help → About...)

Operating system: Windows 10
### Expected behavior

Error message should be displayed as a tool-tip (or alike) for few seconds and then disappear. No user interaction required.  Message should be non-blocking. I.e. whole app functionality should be available while the message is on display.

### Actual behavior

A LOT of single button message boxes. Very annoying! Was acceptable 15 years ago, looks weird now days.

**Comment by whitequark** [comment]
Duplicate of #90
