### ISSUE TITLE
Adding a constraint identical to an existing one should be no-op instead of unsat

### ISSUE THREAD

**Issue by azonenberg** [solvespace/solvespace#301]
As of now, when you add a horizontal, vertical, etc constraint to a line, and one already exists, the solver declares the design unsatisfiable. The user's intention was probably to make that line go in the direction it's already in, so adding a second identical constraint should be a legal no-op (keep the existing constraint and don't add a new one).

**Comment by Evil-Spirit** [comment]
This is very resonable and we can do the same for other types of solver errors. We can intorduce optional checkbox: Solver silent mode enabled by default (easy for new users).
1. Redundant constraint without value label -> remove immediate with error msgbox
2. Redundant constraint with value label -> add it like reference (actually implemented)
3. Didn't converge while adding constraint -> remove immediate with error msgbox
4. Didn't converge while dragging -> just undo to pervious valid position

**Comment by whitequark** [comment]
Fixed in 406c55e8.

Instead of just being a no-op, I select the existing constraint, so that you can see feedback.
