### ISSUE TITLE
Lathe difference broken

### ISSUE THREAD

**Issue by jockbert** [solvespace/solvespace#32]
Using **Group rotating on active sketch** (Shift+L) together with using solid model as **difference** seem to be broken.

Way to reproduce:
1. Extrude a rectangle to a box.
2. Sketch e.g. a circle on one of the box sides.
3. Group rotate circle sketch (Shift+L) and use difference.

I'm using SolveSpace version 2.1~dce90646 on Linux Mint 17.3. 

![failed lathe](https://cloud.githubusercontent.com/assets/3252671/17516223/68af88a4-5e3d-11e6-8536-23dea6d39bc1.png)
[failed lathe.slvs.zip](https://github.com/solvespace/solvespace/files/408873/failed.lathe.slvs.zip)

_BTW: Thanks for the effort to provide a free and usable 3D CAD program for Linux (too). The best alternative, OpenSCAD, only works for some use cases. Truly appreciated._

**Comment by whitequark** [comment]
This is a known limitation with the SolveSpace NURBS backend. There are no plans to improve the backend for now. Check the "Force NURBS surfaces to triangle mesh" option in the group properties every time this issue arises, as a workaround.

**Comment by whitequark** [comment]
Generally, you can achieve some success with getting the NURBS operation to proceed by making sure the NURBS surfaces do not coincide with each other. I.e. in this case, try making your torus's center slighly off the edge of the rectangle. This is, of course, inconvenient to do.

**Comment by ruevs** [comment]
@whitequark would you please label this 'NURBS' so I can find it easier some day in the future.

**Comment by whitequark** [comment]
done! feel free to send me any other issues to tag, I appreciate this

**Comment by phkahler** [comment]
This is actually fixed now.

**Comment by ruevs** [comment]
Fixed on 2020-10-09 22:10:22 in commit d72eba8039c52f5e8d3ab36ec2d8a7598dfd578b
Pull request https://github.com/solvespace/solvespace/pull/733

I am adding this comment just so that things are cross-referenced.
