### ISSUE TITLE
"Split at Point" as special case of "Split at Intersection"

### ISSUE THREAD

**Issue by ghoss** [solvespace/solvespace#321]
I have extended `SplitLinesOrCurves()` in [modify.cpp](https://github.com/ghoss/solvespace/blob/master/src/modify.cpp) in [my fork](https://github.com/ghoss/solvespace) so that splitting is no longer restricted to intersecting lines/curves only.

A split can now also be performed at a point constrained to the line/curve (i.e. a datum point, mid point, or the endpoint of another line/curve with a coincident constraint). The action will not be performed if the point actually lies outside of the endpoints of the line/curve to be split.

Therefore, cases like these will now work:

![Imgur](https://i.imgur.com/i6oy6dt.jpg)

**Comment by whitequark** [comment]
Thanks, I'll take a look!

**Comment by whitequark** [comment]
Thank you for your contribution, and welcome. The SolveSpace project has a Contributor License Agreement; in order for me to be able to merge your changes, please sign it at https://cla-assistant.io/solvespace/solvespace. It will take only a small amount of your time.

**Comment by ghoss** [comment]
@whitequark Done!

**Comment by whitequark** [comment]
Merged in master, thanks. I had to clean up code style and fix a few bugs, e.g. splitting a circle or arc at point caused an assertion failure.
