### ISSUE TITLE
Don't restore windows to nonexistent monitors

### ISSUE THREAD

**Issue by alesnovak** [solvespace/solvespace#329]
### System information

SolveSpace version: (2.3~7c1ca460)

Operating system: (win10)

### Expected behavior

What should have happened?
Property Browser be visible
### Actual behavior
No Property Browser
What actually happened?
After program installation the Property Browser was there
### Additional information
The only difference between installation and present:
-Win10 update
-Java update
-Using notebook without external monitor
For bugs, please attach a savefile that shows the problematic behavior.
You can attach `.slvs` files by archiving them into a `.zip` first.

**Comment by asantoni** [comment]
Does it re-appear if you hit tab?

**Comment by alesnovak** [comment]
Thanks Albert. 
But also hitting tab Browser wont appear.

**Comment by whitequark** [comment]
I believe the cause is that the property browser appears, but on the external monitor. Try erasing the key `HKCU/Software/SolveSpace` in regedit.

**Comment by alesnovak** [comment]
Thanks whitequark. You were right, erasing the key in regedit the Browser is back again on my notebook display. What will happen when I plug in the external monitor again (in 2 weeks when at home)?

**Comment by whitequark** [comment]
@alesnovak Can you please recheck with a recent version (e.g. [this](https://ci.appveyor.com/api/buildjobs/5xs7a8hpapr29kg6/artifacts/build%2Fbin%2FDebug%2Fsolvespace.exe) binary) and say if the problem is fixed for you? I've adjusted some of the code responsible for positioning windows, but I'm not sure if those changes were enough.

**Comment by alesnovak** [comment]
Dear, thanks a lot for attention!

But your suggestion "erasing the key HKCU/Software/SolveSpace in 
regedit" solved the problem.

Ales

------ Original Message ------

**Comment by whitequark** [comment]
OK, if you or someone else encounters this issue again, I'll reopen it.
