### ISSUE TITLE
bug in: textwin.cpp

### ISSUE THREAD

**Issue by cherwey** [solvespace/solvespace#333]
bug: textwin.cpp
line 271: fmt++

changto
 
utf8_iterator it3(fmt);
		it3++;
		fmt = it3.ptr();// ++;

solvespace.h
class utf8_iterator
{
...
const char* ptr() const;
}
util.cpp
const char* SolveSpace::utf8_iterator::ptr() const
{
	return p;
}

**Comment by whitequark** [comment]
Applied in master, thanks!
