### ISSUE TITLE
xcode-select: error: tool 'ibtool' requires Xcode

### ISSUE THREAD

**Issue by Foadsf** [solvespace/solvespace#335]
#334 ## System information

SolveSpace version: cloned the current github repo

Operating system: macOS High Sierra Version 10.13.5

### Expected behavior

I have both xcode command line and GNU compilers installed so I expect the make file to use them for compiling. 

### Actual behavior
but it gives the error below:

> xcode-select: error: tool 'ibtool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> make[2]: *** [bin/solvespace.app/Contents/Resources/MainMenu.nib] Error 1
> make[1]: *** [res/CMakeFiles/resources.dir/all] Error 2
> make: *** [all] Error 2

### Additional information
Xcode is a couple of gigabytes and not everybody wants to use the actual Xcode. please change the make file in away to use xcode command line, GNU or clang/LLVM compilers.

**Comment by whitequark** [comment]
> Xcode is a couple of gigabytes and not everybody wants to use the actual Xcode

So... macOS is many more gigabytes and a royal pain to develop for, yet I support it for no other reason than a wish to produce high-quality software--I don't actually use macOS myself. If you know a way to replace that nib without requiring a full Xcode installation then I'll gladly merge it, otherwise I don't think I am willing to spend time on this.

**Comment by Foadsf** [comment]
I installed Xcode but got the same issue. 
You may consider that the main users of SolveSpace and other Free and OpenSource CAD softwares are the Unix users who don't have the fancy windows ones.

**Comment by whitequark** [comment]
I think that you need to switch to your Xcode installation using `xcode-select`, i.e. `xcode-select -switch /Applications/Xcode.app` (or wherever it's installed).

**Comment by Foadsf** [comment]
awesome. ran `sudo xcode-select -switch /Applications/Xcode.app` and then it compiled like a charm. Thanks a lot.
