### ISSUE TITLE
SolveSpace & Linkage

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#34]
Look on this opensource mechanical simulator code
* https://github.com/rectorsquid/Linkage
* http://blog.rectorsquid.com/linkage-mechanism-designer-and-simulator/

Maybe we can use some code or logic from it for better simulation?

* http://solvespace.com/forum?action=viewthread&parent=1414

**Comment by Symbian9** [comment]
https://github.com/rectorsquid/Linkage/issues/6

**Comment by whitequark** [comment]
I don't think there is code to be shared. An importer/exporter would make sense but I have no plans of implementing one.
