### ISSUE TITLE
Increase dimension line offset from text

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#340]
### System information

SolveSpace version: 3.0~8426992f

Operating system: Debian 9 "Stretch"

### Expected behavior

Offset from dimension value text to dimension line.

### Actual behavior

Currently horizontal offset equal *1 px*, that is too close.

In same time vertical offset equal *3 px*.

### Additional information

![pic1](http://pasteall.org/pic/show.php?id=26803740277750b87da345fe25b89575)

![pic2](http://pasteall.org/pic/show.php?id=913c5594581f044213ea55c10ea47036)

![pic3](http://pasteall.org/pic/show.php?id=b838dc1b8c95e7484ec523cb9084f085)

![pic4](http://pasteall.org/pic/show.php?id=d034c157d0740895b69471955f715d3c)

**Comment by Evil-Spirit** [comment]
Also probably we should get rid of REF. Just use ISO ANSI GOST or some other approach.

**Comment by whitequark** [comment]
ISO does not specify parametric sketches, so it's fine that we depart from ISO where parametricity is required.

**Comment by Evil-Spirit** [comment]
I mean, drawings have common approach to specify reference dimensions. for ex. in GOST  "*" is used:
http://gk-drawing.ru/images/size-inquiry-01.jpg
![image](https://user-images.githubusercontent.com/1980537/43377952-f91a78da-93ed-11e8-98be-c30331a4cc96.png)

**Comment by whitequark** [comment]
@Evil-Spirit Oh, I didn't know that. Thanks.

**Comment by Symbian9** [comment]
> in GOST "*" is used

Depending on used font, "*" should be also in `<sup>` position.

- `X*`: X*
- `X<sup>*</sup>`: X<sup>*</sup>

**Comment by Symbian9** [comment]
> Fixed in eda294e, thanks for the report.

It's look like *Angle* constraint text still look buggy:

![pic1](http://i.imgur.com/hfTEbdd.png)

Can you fix it too?

**Comment by whitequark** [comment]
Fixed in 25b6eba.
