### ISSUE TITLE
Angle constraint ignore digits after decimal point global settings

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#341]
### System information

SolveSpace version: 3.0~8426992f

Operating system: Debian 9 "Stretch"

### Expected behavior

*Angle* constraint should use global "digits after decimal point" settings. Otherwise need option to set it separately.

### Actual behavior

Currently *Angle* constraint has fixed 2 digits after decimal point (i.e., `XX.XX°`).

### Additional information

![pic1](http://pasteall.org/pic/show.php?id=26803740277750b87da345fe25b89575)

![pic2](http://pasteall.org/pic/show.php?id=36f67a8bd6513e8b4bfbf0e124fd65ed)

**Comment by whitequark** [comment]
No. The current behavior is intentional. There are essentially no cases where you want more than two digits after decimal point when constraining angles, so the extra digits would simply clutter up screen space.

**Comment by Evil-Spirit** [comment]
@whitequark can't agree with you. There are cases where you need more digits to display.

**Comment by whitequark** [comment]
@Evil-Spirit OK, you are right, there is a use case presented in #98. I will reopen that issue.
