### ISSUE TITLE
Importing dxf as 3d is annoying

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#345]
When I importing flat 2d drawing it imported as 3d construction. This is most annoying and useless behaviour. User should choose manually how to import such drawings.

**Comment by whitequark** [comment]
If it's imported as 3d construction, it wasn't flat. If you select all and press G, do you get a "not all coplanar" sketch error?

**Comment by whitequark** [comment]
No response in a year, closing.

**Comment by Evil-Spirit** [comment]
That's because I am so lazy
