### ISSUE TITLE
Some colors previews shown as black on color selector window

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#346]
### System information

SolveSpace version: 3.0~2b4c484d

Operating system: Debian 9 "Stretch"

### Expected behavior

All colors icons (previews) should be shown correctly on color selector window.

### Actual behavior

Some colors icons (previews) shown incorrectly (as black) on color selector window.

### Additional information

![pic1](http://i.imgur.com/Iswxft0.png)

![pic2](http://i.imgur.com/HptrWTP.png)

![pic3](http://i.imgur.com/pmMy7oi.png)

**Comment by whitequark** [comment]
Ah, a very tricky bug. Thanks for the report. Fixed in 42bc7efa.
