### ISSUE TITLE
Question: has someone compiled solverspace in Raspberry Pi?

### ISSUE THREAD

**Issue by ochoadavid** [solvespace/solvespace#350]
I want to use solverspace as a design software for a 3D printing workshop and I wonder if someone has experience compiling solverspace in this platform.

Thanks in advance.
David Ochoa

**Comment by whitequark** [comment]
I don't remember anyone reporting success offhand, but there's no reason it shouldn't work. Use the master branch.

**Comment by ochoadavid** [comment]
Thanks, I will try and report back for future reference.

**Comment by Kenzu** [comment]
Solvespace is in the debian repos as armhf https://packages.debian.org/stretch/solvespace so try and install it.

**Comment by ochoadavid** [comment]
Hi, sorry for the delay. Thanks @Kenzu, indeed it is. I just installed it and it works. 

Great.
