### ISSUE TITLE
Sketch GUI stops rendering after a few seconds

### ISSUE THREAD

**Issue by cyber-murmel** [solvespace/solvespace#362]
### System information

SolveSpace version 3.0~258545a3.

```zsh
marble@archlinux ~ % yaourt -Syua
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
  wxpython-gtk2 : Orphan
 Foreign packages: \ 131 / 131
No database errors have been found!
marble@archlinux ~ % uname -a
Linux archlinux 4.18.14-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 13 13:42:37 UTC 2018 x86_64 GNU/Linux
marble@archlinux ~ % dwm -v
dwm-6.1
```
dwm with no patches

### Expected behavior

Sketch GUI keeps rendering.

### Actual behavior
Sketch GUI freezes rendering after a few seconds / actions, but still reacts to clicks and other interactions (Property Browser still shows which tool is active etc.)

Sketch GUI get's re-rendered when window get's resized.

**Comment by whitequark** [comment]
Similar to https://github.com/solvespace/solvespace/issues/358.

**Comment by cyber-murmel** [comment]
Okay.
Sorry, I'm not well experiences yet with the customs in collaborative software development.
Do I now pass `LIBGL_ALWAYS_SOFTWARE=true` to the `make` process?

**Comment by cyber-murmel** [comment]
Ah, Thanks :-)
