### ISSUE TITLE
solvespace-cli --chord-tol command line option is misspelled as --chord-ol

### ISSUE THREAD

**Issue by sdfgeoff** [solvespace/solvespace#364]
In current master, the --chord-tol option for setting chord tolerance is misspelled when parsing, but not in the documentation. This means people reading the documentation won't be able to use the --chord-tol option!

In file `entrycli.cpp` line 147:

```
 if(argn + 1 < args.size() && (args[argn] == "--chord-ol" ||
                                      args[argn] == "-t")) {
```

**Comment by whitequark** [comment]
Fixed in 52c4178, thanks!
