### ISSUE TITLE
Xcode: Playground execution failed 

### ISSUE THREAD

**Issue by softechnoconrajat** [solvespace/solvespace#369]
Playground execution failed:

error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x14eee).
The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation.

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x14eee)
  * frame #0: 0x0000000000014eee
    frame #1: 0x0000000123c284b2 PlaygroundLogger`playground_logger_initialize + 18
    frame #2: 0x00000001235ba23d $__lldb_expr2`main at playground1-901e96..swift:8
    frame #3: 0x000000010dadc5f0 MyPlayground`linkResources + 304
    frame #4: 0x000000010f71262c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    frame #5: 0x000000010f711de0 CoreFoundation`__CFRunLoopDoBlocks + 336
    frame #6: 0x000000010f70c654 CoreFoundation`__CFRunLoopRun + 1284
    frame #7: 0x000000010f70be11 CoreFoundation`CFRunLoopRunSpecific + 625
    frame #8: 0x00000001173191dd GraphicsServices`GSEventRunModal + 62
    frame #9: 0x000000011371281d UIKitCore`UIApplicationMain + 140
    frame #10: 0x000000010dadc6bd MyPlayground`main + 205
    frame #11: 0x0000000110e5a575 libdyld.dylib`start + 1

**Comment by aancha** [comment]
How you resolved this issue?
