### ISSUE TITLE
HighDPI works incorrect on Win10_64bit with 200% scaling

### ISSUE THREAD

**Issue by konsultaner** [solvespace/solvespace#373]
### System information

SolveSpace version: 2.3~7c1ca460

Operating system: Win10 64bit

### Expected behavior

I should see the workspace in HighDPI and my mousepointer should have no offset.

### Actual behavior

HighDPI works incorrect on Win10_64bit with 200% scaling.

### Additional information

![image](https://user-images.githubusercontent.com/2699538/51084457-2fd40480-172a-11e9-80d5-87ce1ea9f5cf.png)

**Comment by whitequark** [comment]
There is no High-DPI support in 2.x versions. High-DPI is only present in the 3.x versions; you can find nightly builds [here](https://ci.appveyor.com/project/whitequark/solvespace).

**Comment by konsultaner** [comment]
now it works :)
