### ISSUE TITLE
Color fringes on mesh boundary when drawing of back faces is turned on

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#377]
### System information

SolveSpace version: `3.0.0~git.1012373`

Operating system: Debian 9.x stable (Stretch, x86_64)

### Expected behavior

No color fringes on mesh edges.

### Actual behavior

SolveSpace renders red fringes on mesh boundary as a result of back faces being shown on top of rear faces.

![pic.1](https://i.imgur.com/MYQjqR4.png)

**Comment by whitequark** [comment]
So. I can reproduce this, but both your analysis and your suggested solution are completely irrelevant. In the future, please restrict yourself to reporting the *presentation* of a bug, and not your suggested fix, since that would avoid wasting time for us both.

**Comment by whitequark** [comment]
I've fixed this for the OpenGL 3 renderer in e383b7f. @Evil-Spirit Do you recall why you added the `glPolygonOffset` call? It seems to result in Z-fighting between front and back faces, and removing it has no ill effect.

**Comment by Evil-Spirit** [comment]
@whitequark no, it was a very long time ago. Can't remember.
