### ISSUE TITLE
feature request: toggle visibility of construction elements

### ISSUE THREAD

**Issue by notnot** [solvespace/solvespace#382]
First of all, thanks for developing this great software. I am quite charmed by it. 

When making some more complex designs, construction elements are often handy, but they can sometimes obscure the view on the actual parts too much. Would be handy if one could toggle their visibility.

**Comment by whitequark** [comment]
I agree this would be a useful enhancement.

**Comment by Symbian9** [comment]
+1. I also need this feature.

**Comment by whitequark** [comment]
Done in 53fee95.
