### ISSUE TITLE
Tool tips shown when mouse far away from instrument panel

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#385]
### System information

SolveSpace version: 3.0~9d1601e

Operating system: Debian 9.x

### Expected behavior

Tool tips should not be shown if mouse cursor placed in workspace.

### Actual behavior

Tool tips still shown when mouse cursor far away from instrument panel.

### Additional information

![pic.1](https://i.imgur.com/6jZ9qd6.png)

![pic.2](https://i.imgur.com/W8PDwXx.png)

**Comment by whitequark** [comment]
Fixed in 3296474c15.
