### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by starsolaris** [solvespace/solvespace#388]
### System information

SolveSpace version: 3.0~83a0a517; (build from https://ci.appveyor.com/project/whitequark/solvespace/build/artifacts)

Operating system: Windows 10

### Expected behavior

SolveSpace should close

### Actual behavior

SolveSpace crashed with error message:
File C:\projects\solvespace\src\platform\guiwin.cpp, line 459, function SolveSpace::Platform::MenuBarImplWin32: Win32 API call failed: DestroyMenu(hMenuBar).
Error: Неверный дескриптор меню. 
("Invalid Menu Handle" in English)

**Comment by whitequark** [comment]
Looks like:

> If the specified window is a parent or owner window, DestroyWindow automatically destroys the associated child or owned windows when it destroys the parent or owner window. The function first destroys child or owned windows, and then it destroys the parent or owner window.

So there's probably a sequencing issue between destroying the window and its menu bar.

**Comment by whitequark** [comment]
Fixed in a460cf4.
