### ISSUE TITLE
ERROR: media-gfx/solvespace-9999::booboo failed (configure phase)

### ISSUE THREAD

**Issue by usern1983** [solvespace/solvespace#391]
### System information

SolveSpace version: (git)

Operating system: (CLDM,gentoo-like[calculate-linux.org])

[build.log](https://github.com/solvespace/solvespace/files/3043726/build.log)

**Comment by whitequark** [comment]
You should file this bug against your Linux distribution. In any case, the problem is that not all necessary submodules are checked out (you need `extlib/flatbuffers` and `extlib/q3d` as well).
