### ISSUE TITLE
Fillet method shown on video

### ISSUE THREAD

**Issue by JohnHyslop** [solvespace/solvespace#393]
SolveSpace version: ( 2.0 & 2.3 )

Operating system: ( Windows 10 )

Drew the angle bracket sketch and
Selected the point where the 2 lines intersect, pressed the arc icon and it didn't create an arc as it did in the tutorial video.i had to break the lines and draw the arc manually and set tangent and parallel and vertical contraints to make this example.
Am I doing something wrong?
Love the software great job
Cheers
John

**Comment by mkyral** [comment]
I don't know how on 2.0 or 2.3, but on 3.0dev it works. What tutorial you refers to?

**Comment by JohnHyslop** [comment]
I was selecting the wrong icon..I was selecting arc . apologies to all..
Cheers
John
