### ISSUE TITLE
Distribute SolveSpace in a Flatpak

### ISSUE THREAD

**Issue by LeandroStanger** [solvespace/solvespace#402]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by whitequark** [comment]
Fixed in 0b7b8a4.

Note that FlatHub app submission guidelines state that only a released version may be pushed to FlatHub. There is no ETA on the next release of SolveSpace. Therefore, there is no ETA for FlatHub availability.

**Comment by mdirolf** [comment]
Just wondering if you'd be able to push to flathub now that 3.0 is out? Thanks!

**Comment by ruevs** [comment]
@rpavlik started working on it last month https://github.com/solvespace/solvespace/pull/1026

**Comment by mdirolf** [comment]
Thanks @ruevs!
