### ISSUE TITLE
DXF export does not work if filename has spaces in path

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#41]
http://solvespace.com/forum.pl?action=viewthread&parent=1549; should not be hard to fix.

@Evil-Spirit I told you that libdxfrw's file save routine should not be used... now you see why.

**Comment by Evil-Spirit** [comment]
@whitequark, ok I will fix it.

**Comment by whitequark** [comment]
@Evil-Spirit I think that just needs another constructor that lets us pass FILE* and then ssfopen

**Comment by Symbian9** [comment]
As for me, better way do not use spaces in file and folder naming and replace them with "_" symbol never.

**Comment by Evil-Spirit** [comment]
Probably fixed (I don't have such problem with spaces)
But for unicode file names it works better.
https://github.com/Evil-Spirit/libdxfrw/commits/wide-file-names
https://github.com/Evil-Spirit/solvespace/commits/fix-dxf-path

**Comment by whitequark** [comment]
@Evil-Spirit No, this is not a proper fix. *Never* use std::wstring except on Windows when interacting with WinAPI functions. See http://utf8everywhere.org/ for explanation.

**Comment by Evil-Spirit** [comment]
@whitequark,
Is there any way to make work ifstream with utf8?

**Comment by whitequark** [comment]
@Evil-Spirit No. Make it a string stream or something, I guess. That would anyway be handy for if we don't have a filesystem.

**Comment by Evil-Spirit** [comment]
fixed again
https://github.com/Evil-Spirit/libdxfrw/commits/wide-file-names
https://github.com/Evil-Spirit/solvespace/commits/fix-dxf-path

**Comment by whitequark** [comment]
Wow, std::fstream is a portability disaster. No portable (i.e. that works with MinGW) way at all to open a fstream with a wide path...

Fixed in master and 2.x.
