### ISSUE TITLE
Fedora copr is down

### ISSUE THREAD

**Issue by asdf23** [solvespace/solvespace#411]
### System information

SolveSpace version: None

Operating system: Fedora 29

### Expected behavior

Installation success

### Actual behavior

Installation was unsuccessful. Copr files are missing? Not sure. 

dnf copr enable dschubert/solvespace
dnf install solvespace

=
Failed to synchronize cache for repo 'dschubert-solvespace'
Copr repo for neofetch owned by sysek                             776  B/s | 341  B     00:00    
Failed to synchronize cache for repo 'sysek-neofetch'
Ignoring repositories: dschubert-solvespace, sysek-neofetch

**Comment by whitequark** [comment]
There is nothing I can do about this because I do not maintain the packages in Fedora. Please complain to the maintainer(s) of the Fedora packages instead (probably dschubert).
