### ISSUE TITLE
Request to move coordinate axes from under the toolbar

### ISSUE THREAD

**Issue by philtipping** [solvespace/solvespace#450]
### System information

SolveSpace version: 3.0~02d7f0c0

Operating system: lubuntu 18.04 on Dell Vostro laptop

### Additional information
Minor cosmetic request. The coordinate axes at the bottom-left of the main screen are partially hidden by the toolbar. There is room on my screen layout to move them lower, or maybe move the toolbar higher - see screenshot, but if this causes problems, a shortcut key for toggling the toolbar on/off would be a compromise. I know the axes are replicated in the centre but these can become difficult to select with a complicated diagram.
Thank you.
![solvepace-request](https://user-images.githubusercontent.com/45852590/61123204-a5cbe500-a49b-11e9-9baf-2b663370ed74.jpg)

**Comment by whitequark** [comment]
Commit 02a9a1b9 moves the axes to the right if the window is not tall enough.
![Screenshot_20190712_110955](https://user-images.githubusercontent.com/54771/61124107-947fda00-a495-11e9-9b71-9f1ad47b3063.png)

**Comment by whitequark** [comment]
By the way there is a `View` → `Show Toolbar` option.

**Comment by philtipping** [comment]
Perfect thanks. 
btw View,Toolbar is what I'm using now but this just seemed cumbersome when you're used to using shortcuts :)
