### ISSUE TITLE
SolveSpacePy with PyQt5 GUI

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#46]
SolveSpace rewrited with Python3?!
* https://github.com/40323230/Pyslvs-PyQt5
* https://github.com/40323230/python-solvespace

![SolveSpacePy GUI](https://raw.githubusercontent.com/coursemdetw/project_site_files/gh-pages/files/2016spring/g2/Python_solvespace/0928_02.jpg)

**Comment by whitequark** [comment]
No? That's just the solver, hooked to some domain-specific applets. Pretty much working as intended.
