### ISSUE TITLE
Allow export flat closed sketches as flat faces in 3D mesh

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#48]
Please, allow export "sketch-in-plane" as flat double sided faces in mesh format.

**Comment by whitequark** [comment]
What's the use case?

**Comment by Symbian9** [comment]
It would be usefull for sheeting details, were extruding no needed

Like glass in windows.
I will post some screenshot soon.

**Comment by whitequark** [comment]
Note that such zero-volume meshes are not valid, and are likely to cause all sorts of breakage in other software.

**Comment by Symbian9** [comment]
As for me, target application for editing exported mesh is Blender.
And Blender has no any issues with meshes, that include flat faces.

Also, i don't know any 3D editor that has issues with flat planes.

**Comment by whitequark** [comment]
I thought about this and I don't see a need for a dedicated feature. You can constrain the top face to the bottom face (e.g. select any point from the bottom face, top face, and constrain coincident) and then export the result.

**Comment by whitequark** [comment]
Note that this will, as I've said earlier, result in a mesh with naked edges. I don't think it's a good idea to have a feature dedicated to exporting invalid meshes.
