### ISSUE TITLE
Transfer snap ownership to solvespace organization

### ISSUE THREAD

**Issue by ppd1990** [solvespace/solvespace#482]
With https://github.com/solvespace/solvespace/pull/436 being almost ready for merging, I propose the following steps regarding the publishing of the snap:

- [x] Create a ```solvespace ``` account on snapcraft.io
This gives the solvespace snap store listing an official touch and at some point in the future, it can be verified by the store and appear with a little badge or checkmark.
- [x] I request to transfer ownership of the snap to the newly created account on the snapcraft forum: https://forum.snapcraft.io/c/store-requests
- [x] If necessary, the snap's administration can be shared with other accounts. A shared secret is not necessary. The link for that would be https://dashboard.snapcraft.io/snaps/solvespace/collaboration/

**Comment by whitequark** [comment]
@jwesthues Could you create an account on snapcraft.io for SolveSpace and add me as a collaborator?

**Comment by jwesthues** [comment]
Cool, `solvespace` account created. Let me know when the transfer is complete, and I'll add you (and my own personal account, and whoever else we should have) as collaborators.

**Comment by ppd1990** [comment]
The transfer request was filed here:
https://forum.snapcraft.io/t/please-transfer-solvespace-to-solvespace-account/14342

**Comment by ppd1990** [comment]
@jwesthues Have you been contacted by someone from the Snap Store? I presume they'll require your OK first. You could probably also claim the `solvespace` name from your account. That'll get the ball rolling a little faster, I think.

**Comment by jwesthues** [comment]
No contact yet. I'm traveling now, but will try claiming it if no action by my return Sunday.

**Comment by jwesthues** [comment]
No contact yet, sent the claim today.

**Comment by ppd1990** [comment]
Nothing yet. Will poke the store admins some more...

**Comment by ppd1990** [comment]
Poking was successful. I've been contacted already and have confirmed the transfer request. @jwesthues You should you have mail from Canonical

**Comment by ppd1990** [comment]
The transfer has been completed. Please note that I am still (by default) an active collaborator of the snap. So don't forget to remove me if necessary.

**Comment by jwesthues** [comment]
I got the transfer, added @whitequark as a collaborator, left @ppd1990 just in case. Thanks, and let me know if any other action required.

**Comment by whitequark** [comment]
@jwesthues It looks like I can't access the snap--can you recheck?

**Comment by ppd1990** [comment]
@whitequark Your invite is still pending. You need to respond to the email

**Comment by whitequark** [comment]
Thanks, that worked.

**Comment by whitequark** [comment]
> The transfer has been completed. Please note that I am still (by default) an active collaborator of the snap. So don't forget to remove me if necessary.

I've removed you to minimize potential risk of compromise in the future. Thank you for your work on bringing this together!

**Comment by ppd1990** [comment]
Thanks for reviewing. I'll PR some readme changes to guide users to the snap store soon.
