### ISSUE TITLE
Snap Travis integration

### ISSUE THREAD

**Issue by ppd1990** [solvespace/solvespace#483]
As outlined in https://github.com/solvespace/solvespace/pull/436 we'd like  to have build on commit and also release to the edge channel.

## Using ```snapcraft remote-build```

The current plan involves using ```snapcraft remote-build``` to build for all possible architectures. This feature is still in beta @ https://github.com/snapcore/snapcraft/tree/remote-build and will receive further simplifications, so I propose waiting for that to be properly finished.

A sample implementation is here: https://github.com/ppd1990/solvespace-travis

## Using docker

If that does not work out so well for any reason, we can still use docker to build for Travis' native architectures https://github.com/solvespace/solvespace/pull/436#issuecomment-502370983

Cross-builds for other architectures should be possible with qemu, but I haven't looked into that enough.

Multiarch support for docker: https://github.com/multiarch/qemu-user-static
Travis with Docker and QEMU: https://developer.ibm.com/linuxonpower/2017/07/28/travis-multi-architecture-ci-workflow/

## Architectures to support

It wouldn't hurt to define what architectures we'd like to build for. ```amd64``` and ```i386```for sure, ```armhf``` and ```arm64``` make sense too for a desktop application.

**Comment by ppd1990** [comment]
And here we go: https://forum.snapcraft.io/t/call-for-testing-snapcraft-3-9/13944

Snapcraft 3.9 is pre-released and includes remote-build support. Let's do it.

**Comment by whitequark** [comment]
Sounds good. Let me know once it becomes stable.

**Comment by ppd1990** [comment]
Certainly. We're going to need a solvespace launchpad account for remote builds though. I'll test with mine in the meantime

**Comment by ppd1990** [comment]
Is there a particular reason for ```dist: trusty```? The Travis snap addon requires xenial or above and I'd rather use that if possible.

**Comment by whitequark** [comment]
I don't recall if there was. It should be fine to upgrade to Xenial.

**Comment by ppd1990** [comment]
This was implemented by: 
1. a60d4df
2. d5351c4
3. 2dcd81d

Snaps are being built and deployed correctly: https://travis-ci.org/solvespace/solvespace/jobs/640723069

I consider this completed.

**Comment by whitequark** [comment]
Is this process supposed to upload 4 separate releases, each supporting 1 architecture? Seems suboptimal.

**Comment by ppd1990** [comment]
The revision is a strictly increasing integer per project and applies to all uploaded snaps. So yes, it is indeed meant to be that way.

See `qelectrotech`'s revision matrix for example, which uses Canonical's "zero-config" https://snapcraft.io/build service:

![Screenshot from 2020-01-23 15-29-37](https://user-images.githubusercontent.com/6652223/72993429-aa336c00-3df5-11ea-873c-90623eba0686.png)

**Comment by whitequark** [comment]
We're all done here!
