### ISSUE TITLE
Fail compile

### ISSUE THREAD

**Issue by piotrb3d** [solvespace/solvespace#500]
### System information

SolveSpace version: 3.0
Operating system: Windows 7

Everything exactly as directed for building for Windows

file: Toolchain-mingw64.cmake

set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER "C:/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/x86_64-w64-mingw32-gcc.exe")
set(CMAKE_CXX_COMPILER "C:/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/x86_64-w64-mingw32-g++.exe")
set(CMAKE_RC_COMPILER "C:/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/windres.exe")

set(CMAKE_FIND_ROOT_PATH "c:/users/piotr/solvespace")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(ENV{PKG_CONFIG_LIBDIR} "c:/users/piotr/solvespace/extlib")

> in window console cmake 3.16.0 rc1:
.....
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
.....
CMake Warning at CMakeLists.txt:251 (message):
  Gettext not found, translations will not be updated
....
Benchmarking disabled in debug builds.
Configuring done
Generating done

No compiling to solvespace.exe

What am I doing wrong ?
Thank you for the hint

**Comment by whitequark** [comment]
You are following the instructions for cross-compilation from Linux to Windows. You need to follow the instructions for [a native Windows build](https://github.com/solvespace/solvespace#building-on-windows).
