### ISSUE TITLE
Export background color as paper color

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#525]
### System information

- SolveSpace version: `3.0~690f87c`
- Operating system: Debian 9.x stretch (x86_64)

### Expected behavior

Add option in *«Property Browser > configuration > export background color»* for 2D view export to PDF, SVG, etc.

- [ ] export background color

Additionally, if this option would be disabled exported PNG image (via *«Export Image»* or if render it via `solvespace-cli`) background should be transparent.

For `solvespace-cli` add options `--bg-color on` / `--bg-color off`.

### Actual behavior

If export to PDF or SVG paper color always is white (transparent).

Actually only «Export Image» or render to PNG using `solvespace-cli` always use background color.

### Additional information

For bugs, please attach a savefile that shows the problematic behavior.
You can attach `.slvs` files by archiving them into a `.zip` first.

**Comment by phkahler** [comment]
Does #568 mean we can close this?
