### ISSUE TITLE
SolveSpace 3.0 icon improvements

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#526]
### System information

-  SolveSpace version: `3.0~690f87c`
-  Operating system: Debian 9.x stretch (x86_64)

### Expected behavior

Propose to improve *SolveSpace* `3.0` icon (according SolveSpace render)

- add grey dot for "connected points"
- replace transparent background with opaque black 
- invert "line segments" color from black to white
- remove shade under "constraint perpendicular" icon

![pic.1](https://i.imgur.com/9JQAWnO.png)

### Actual behavior

Actual *SolveSpace* `3.0` icon include shade under "constraint perpendicular" icon (as you can see on `solvespace-48x48.png`, this shadow also missed few pixels on the bottom-right leg)

- https://github.com/solvespace/solvespace/blob/master/res/freedesktop/solvespace-48x48.png
  ![png icon](https://i.imgur.com/GM4k7B1.png)

Also, its SVG version has incorrect order for "green dot" and "line segments" shapes

- https://github.com/solvespace/solvespace/blob/master/res/freedesktop/solvespace-scalable.svg
  ![svg icon](https://i.imgur.com/irchcAn.png)

### Additional information

Proposed `solvespace-scalable.svg`

- https://gist.github.com/Symbian9/5f8dad142045cd374d585acfac0d4cdd

**Comment by whitequark** [comment]
An icon is a symbol. It does not have to look exactly like a screenshot.

I've fixed the Z-order issue in SVG in 69baf524.

**Comment by Symbian9** [comment]
BTW, Position of shade under "constraint perpendicular" icon on PNG version differ from SVG.
