### ISSUE TITLE
LibreOffice cant open generated PDF

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#53]
LibreOffice has possibility to open and edit PDF format.

But when I try open any PDF's, generated by SolveSpace, LO fail on import.

**Comment by whitequark** [comment]
How are you importing it exactly?

**Comment by Symbian9** [comment]
1) run LibreOffice
2) "File -> Open -> PDF-Portable Document Format (Draw)"
3) select PDF generated by SolveSpace and press OK

RESULT:
> General Error
General input/output error.

**Comment by whitequark** [comment]
Which libreoffice version? Mine doesn't have PDF there..

**Comment by Symbian9** [comment]
LibreOffice 5.0.3.2 and LibreOffice 5.2.1.2
Result same for both.

**Comment by whitequark** [comment]
I have 5.2.2.2.0+ and there is no PDF in the list of supported formats. Perhaps it was removed because it was buggy?

**Comment by Symbian9** [comment]
Look deeply! There are no release notes about  remove of PDF import support, so think, 5.2.2.2 also include it.
Anyway, you can try "File -> Open -> All files -> (select pdf from SolveSpace)"

Also I can open other PDF's using installed LibreOffice.

LibreOffice 5.0.3.2 and LibreOffice 5.2.1.2
Result same for both.

Maybe proble in SolveSpace output - PDF-1.1 format

Why you not use PDF-1.4 or PDF/A-1a specifications? Both they opened in LibreOffice.

**Comment by whitequark** [comment]
> Anyway, you can try "File -> Open -> All files -> (select pdf from SolveSpace)"

That just opens the PDF as text.

> Maybe problem in SolveSpace output - PDF-1.1 format?!

Maybe. But everything else I've tried so far can open these. Maybe @bofh453 knows what's wrong with SolveSpace's PDFs...

**Comment by Symbian9** [comment]
http://www.technorms.com/26572/edit-save-pdf-libreoffice-openoffice

**Comment by whitequark** [comment]
Yeah, I don't need guidance to navigate a menu. Pretty sure this got removed.

**Comment by whitequark** [comment]
Ah, confusingly, this is an extension--I had to install `libreoffice-pdfimport` and now I can reproduce this.

**Comment by Symbian9** [comment]
So can you detect is it problem of SolveSpace PDF export or LibreOffice PDF import extension now?

**Comment by whitequark** [comment]
I have no idea because LibreOffice PDF import doesn't have any debug output that would indicate what the message is. I suggest reporting this against the LibreOffice PDF import plugin, and if they come back explaining exactly how our PDF export is broken, I'll fix it.

Meanwhile, just use SVG. I don't know why you bothered with importing PDF in the first place.
