### ISSUE TITLE
"Edit newly added dimensions" tries to allow editing auto-reference dimensions

### ISSUE THREAD

**Issue by rpavlik** [solvespace/solvespace#536]
### System information

SolveSpace version: 3.0~64c0f62b

Operating system: Debian Buster

### Expected behavior

I turned on "Edit newly added dimensions" because it's a great workflow improvement.

When adding a distance constraint on an already fully-constrained sketch, I'd expect it to not let me edit it, since solvespace will automatically mark such a constraint as "REF"

### Actual behavior

It lets you "edit" it, though the edits have no effect.

### Additional information

![Peek 2019-12-20 11-02](https://user-images.githubusercontent.com/61129/71366465-9fbc5300-2567-11ea-8256-b620161c111a.gif)

![Peek 2019-12-23 09-42](https://user-images.githubusercontent.com/61129/71366763-9b446a00-2568-11ea-8c26-68b28c05a354.gif)

Here's the model for the second one, 
[example.zip](https://github.com/solvespace/solvespace/files/3995464/example.zip)

**Comment by vespakoen** [comment]
I added that functionality and didn't think of this case.
I will try to make a PR when I've got some time on my hands

**Comment by whitequark** [comment]
Thanks for following up!

**Comment by rpavlik** [comment]
Looks fixed since https://github.com/solvespace/solvespace/commit/3ed1719de2dc6e0525c94de78353d076623e46e4, thanks!
