### ISSUE TITLE
Weird rendering of solid difference

### ISSUE THREAD

**Issue by baryluk** [solvespace/solvespace#540]
### System information

Compiled at commit 16c5fa6889202f2059b52c4a89599910541dd1a0

Operating system: Debian testing, amd64

### Expected behavior

What should have happened?

I had a lathe operation, plus 2 extra extrusions (one with 3x time rotating symmetry) acting as a difference.

At the end I wanted to see a crossection, so I did another sketch, extruded it, and used as a difference.

I expected to have a solid model, not hollow one, with some red marks on the edges. There are some other red marks, that I don't know what they are, and some edges (45 deg ones) do not have the red edges.

No idea what is going on.

### Actual behavior

![adapter-plate-section-4](https://user-images.githubusercontent.com/110322/72269274-33d78280-361b-11ea-85a8-8dd28d79a909.png)

![adpate-plate-section-iso](https://user-images.githubusercontent.com/110322/72269435-7b5e0e80-361b-11ea-967b-aacc9b09af9e.png)

Project file:  [adapter-plate.tar.gz](https://github.com/solvespace/solvespace/files/4054379/adapter-plate.tar.gz)

**Comment by baryluk** [comment]
I just tried using https://github.com/phkahler/solvespace/tree/nurbs branch, and result is the same or even worse:

![adpate-plate-section-2](https://user-images.githubusercontent.com/110322/72271074-240d6d80-361e-11ea-9917-ce2778735e5c.png)

**Comment by whitequark** [comment]
Classic NURBS issue. Force triangle mesh for now.

**Comment by baryluk** [comment]
@whitequark  Indeed that helped:

![adapter-plate-g00b-extrude-force-triangle-mesh](https://user-images.githubusercontent.com/110322/72272438-85364080-3620-11ea-890e-3e59a16c81ed.png)

How will that affect STEP 3D export?

**Comment by whitequark** [comment]
You wouldn't be able to export rational surfaces after this, only triangle meshes; in particular IIRC exported STEP files will just be empty and you'll have to use STL.

**Comment by baryluk** [comment]
@whitequark That sucks. :/ What if I keep the model with this red things / errors and export then to STEP? Is the red thing due to rendering issue, or the model itself is broken due to intersection problems?

**Comment by whitequark** [comment]
The model itself is broken. If you *really* need NURBS surfaces, try making the intersection not "cut across the seam". E.g. if you have a difference cutting exactly 1/4 of a circle, try moving it away by 0.1 mm or something.

**Comment by baryluk** [comment]
@whitequark Thanks a lot.
