### ISSUE TITLE
Export 2D view to OpenDocument Graphics (*.odg)

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#55]
Add OpenDocument exporter, as it is international open specification standart.
* https://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html

**Comment by whitequark** [comment]
This is completely pointless. SVG is a part of OpenDocument, and we can export SVG. Any tool that accepts OpenDocument will also accept SVG.
