### ISSUE TITLE
Allow move enhancment from previouse group if it not hard constrained

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#56]
Currently, if in new plane make connecting between line end from current and point (that not constrained in any manner) from previouse group its impossible drag line from current group.
But if select end of line, that constrained to point from previouse group, its possible move it. 

Use case will publish soon with screenshot.

**Comment by whitequark** [comment]
I have no idea what are you describing in this issue. A screenshot would probably help.

**Comment by Symbian9** [comment]
@whitequark, look this http://solvespace.com/forum?action=viewthread&parent=1609

**Comment by whitequark** [comment]
Fixed in master.
