### ISSUE TITLE
Add missing constraints to toolbar

### ISSUE THREAD

**Issue by Timmmm** [solvespace/solvespace#570]
SolveSpace version: 3.0~645353cb
Operating system: Windows 10

Some constraints are not in the toolbar, which makes them not very discoverable. I think they should all be added. As far as I can see the missing ones are:

* Length Ratio
* Length Difference
* At midpoint
* Lock point where dragged
* Comment

(Also maybe rename "Lock point where dragged" to "Current position"? Assuming that's what it does.)

**Comment by whitequark** [comment]
I think they're fine as it is for two reasons:

  1. if we make the toolbar even taller, it will get cropped by the window on smaller screen resolutions, which is even worse;
  2. menus literally exist for discoverability.

**Comment by whitequark** [comment]
What I think would be far more useful is implementing #121.
