### ISSUE TITLE
Optimize PNG images 

### ISSUE THREAD

**Issue by ruevs** [solvespace/solvespace#597]
Maybe this should be merged in?
https://github.com/zhiyaluo/solvespace/pull/1
https://github.com/zhiyaluo/solvespace/pull/1/commits/818dcaf799f524e683a0fd3f25c6df688dc65bc8

**Comment by whitequark** [comment]
Definitely not as-is, because the `/test` images are generated and shouldn't be treated as assets. The `/res` images can be, but the gains are minimal; I think I already ran optipng on them some time ago.

**Comment by ruevs** [comment]
Oh I forgot about the `/test` sorry. So `/res` is reduced from 22.03kb to 13.7kb not bad as a percentage, but not worth it.
