### ISSUE TITLE
Opening via Finder displays an error related to a -psn parameter

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#602]
See https://github.com/solvespace/solvespace/issues/398#issuecomment-612759454 and https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder.

**Comment by stiff** [comment]
Now that you've reminded me about this, I realised that it's trivial to test it: just run from terminal, not from finder. And I can confirm that running from terminal without command line arguments app opens without any alerts.

So probably handling `psn` argument like here: https://github.com/freeorion/freeorion/blob/0165590532701ac6e38e2872105566eeac2f84d8/util/OptionsDB.cpp#L718 is enough.

**Comment by whitequark** [comment]
Yep, already done.
