### ISSUE TITLE
Unusual definition of isnan() and its implications

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#603]
Commit ea6db67c7 added an unusual `isnan` macro:

```c++
#define isnan(x) (((x) != (x)) || (x > 1e11) || (x < -1e11))
```

Commit 8bc322eb4 adds a preprocessor guard that *looks* like it would cause the `isnan` function from `math.h` to be preferred, but doesn't actually do that on many platforms, e.g. glibc:

```c++
#ifndef isnan
#   define isnan(x) (((x) != (x)) || (x > 1e11) || (x < -1e11))
#endif
```

@jwesthues I'm not really sure what's the intent here--is it to check for NaN and infinity, or is it really a comparison with `VERY_POSITIVE` and `VERY_NEGATIVE`? Regardless, we need a better name for the function that doesn't clash with `math.h`, and to get rid of the misleading preprocessor junk.

**Comment by jwesthues** [comment]
Yeah, clearly not good. This is used for stuff like testing whether numerical algorithms converged to anything reasonable, so actual standard `isnan()` is definitely not what we want--we definitely want to return true for ±Inf, and for implausibly large or small normal numbers too. I'd keep the definition but rename, to `IsReasonable()` or something.
