### ISSUE TITLE
RFC: Migrate CI to GitHub Actions?

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#618]
I've set up GitHub Actions for a different project and was pleasantly surprised by how well they work. This has some significant potential benefits for us, including:
  * Unifying the build configuration for Windows, Linux and macOS (strictly speaking we could do this on Travis or AppVeyor just as well);
  * Uploading artifacts for each build on all platforms, not just on Windows, simplifying the life of macOS and to lesser degree Linux users;
  * Significantly faster builds, since all of our submodules already live on GitHub and checkouts are a significant contributor to AppVeyor build times;
  * Better build sequencing, such as not building Snap packages if tests fail on Windows (which may indicate a Windows-specific problem, but quite often points to a generic problem that goes undetected on Linux build bots);

Any opinions or objections?

The main direct benefit is having artifact uploads, which Travis just doesn't provide at all. A potential alternative would be to use AppVeyor for everything, but I found GitHub Actions a lot less frustrating to work with than AppVeyor overall.

cc @ppd since this will impact Snap builds

**Comment by Symbian9** [comment]
FTR, GitHub's actions artifacts (as I know) could not be downloaded by not logged users (e.g. there  are no anonymous downloading for artifacts). I may be wrong.

**Comment by whitequark** [comment]
You are correct (I think they do it to avoid excessive bandwidth costs). This isn't a huge problem though since we can publish a rolling "nightly" pre-release, like [wasmtime does](https://github.com/bytecodealliance/wasmtime/blob/master/.github/workflows/main.yml#L500-L509).

**Comment by ppd** [comment]
There's an upstream action for snapcraft: https://github.com/snapcore/action-build and it seems like arm64 and amd64 are both supported.

So this seems like a good idea, snap-wise.

**Comment by phkahler** [comment]
@whitequark  you had mentioned that the current build are debug anyway, so not suitable for general use. Would this change include producing release builds?

Either way, if it makes life easier I say do it.

**Comment by whitequark** [comment]
> Would this change include producing release builds?

We could far more easily set it up so that e.g. after debug builds succeed and go through testing, there is another round of release builds that are uploaded for general use.

**Comment by ppd** [comment]
I must correct my statement regarding arm64 support: the only way to build on arm64 seems to self-host runners. Github-hosted runners are only amd64 as far as I can see (https://github.community/t/does-github-actions-support-multiple-os-architectures/16526).

**Comment by phkahler** [comment]
Closing because it looks like we're going with Travis for now.

**Comment by ppd** [comment]
We can come back to this if necessary. Travis has its own problems, but it's a) there and b) has brittle arm64 support as a USP.
