### ISSUE TITLE
2d export to PDF - corrupt line styles and fonts

### ISSUE THREAD

**Issue by rootfoo** [solvespace/solvespace#633]
### System information
SolveSpace version: 3.0~0da4a6b7;
Operating system: Ubuntu 18.04

### Expected behavior
Export 2d View to PDF 

### Actual behavior
* Fonts for letters and numbers with closed contours export in constraint color (e.g. 0, 6, B, ...)
* Line style colors do not export properly when changed 
* Constraints assume dashed line style and color if applied to non-contour lines 

### Additional information
Two examples attached.

[examples.zip](https://github.com/solvespace/solvespace/files/4807325/examples.zip)

**Comment by Symbian9** [comment]
Suggest this is duplication of https://github.com/solvespace/solvespace/issues/518
