### ISSUE TITLE
DXF export problems

### ISSUE THREAD

**Issue by ionapostol** [solvespace/solvespace#636]
Hi,
My name is Ion Apostol and I downloaded your software which is great but...

I use Windows 10 laptop i7 7700HQ , 8Gb ram,  2x 256 SSD drive , 1050Ti nVidia 4Gb.
Solvespace v 2.3~7c1ca460

### Expected behavior
I tried both version 2.0 and 2.3 .
In v2.0 I exported a square with 50mm by 50mm and when I opened in eDrawings PRO from Dassault Systems the square was 1270mm by 1270mm.

In v2.3 the dxf export ...export only dimension lines the square is invisible.
I see that is an old problem. Is there a fix ?
 
PS: I tried v2.2 later and I noticed that when I export dxf  the 50 by 50 square is not visible but is there  . If I use measure tool on eDrawings and hover over one side of my square the line is there and can be measured ...and is 50mm long !

PPS:
I noticed in v2.3 if I change the colour of square line from white to magenta or else the exported dxf square apears !!!

[test.zip](https://github.com/solvespace/solvespace/files/4809848/test.zip)

**Comment by phkahler** [comment]
Does this dxf file have the correct dimentions in eDrawings PRO?  I don't have access to it.
[test_export.zip](https://github.com/solvespace/solvespace/files/4810677/test_export.zip)

This was created with current master branch.

**Comment by ionapostol** [comment]
Yes, from what I noticed is only a matter of colour of drawing. If is white is nit visible on exported dxf file ,but if I change colour to anything else then the line is visible in dxf file.

**Comment by phkahler** [comment]
Is eDrawings PRO using a white background?  Is this just a white-on-white issue?

**Comment by ionapostol** [comment]
No, I put one image with screenshot of eDrawings but I think the problem is on my side because now no matter if I change the colour I cannot see the square in eDrawings. I see only the dimension lines. Is strange because if I open the dxf file with  Lazycam for example the square is there and I can work with that file.
Unfortunatelly I cannot reinstall eDrawings because is part of Solidworks.( I will but in a distant future)
[dxf square white lines.zip](https://github.com/solvespace/solvespace/files/4814858/dxf.square.white.lines.zip)

**Comment by phkahler** [comment]
Closing as requested by the OP who also seems to have solved their problem according to a post in the forum.
