### ISSUE TITLE
"area of closed contours" entetities use only "mm²"

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#639]
### System information

SolveSpace version: `3.0~d238f985`

Operating system: Debian 10 buster

### Expected behavior

`area` ("show area of closed contours") should fully follow SI prefixes: `mm²`/`cm²`/`m²``km²`/ etc.

### Actual behavior

`area` entities hardcoded to only show only value in `mm²` SI prefix format:

![pic.1](https://i.imgur.com/D3ZqXUP.png)

**Comment by whitequark** [comment]
Thanks for the report.

**Comment by Symbian9** [comment]
Thanks for fix.
