### ISSUE TITLE
Property Browser window mouse cursor behaviour

### ISSUE THREAD

**Issue by virtualritz** [solvespace/solvespace#64]
On OS X, when hovering over the edges/corners of the Property Window, the mouse cursor does not change to a resize icon. Only when the user starts to drag does the cursor update.

Note: this works as expected on the sketch window.

**Comment by whitequark** [comment]
Yep. I have no idea why that happens.

**Comment by whitequark** [comment]
Fixed in master and 2.x (as a part of an unrelated fix).
