### ISSUE TITLE
Unwanted red edges

### ISSUE THREAD

**Issue by phkahler** [solvespace/solvespace#666]
### System information

SolveSpace version: 3.0~fd2dfe87

Operating system: Fedora 31

### Expected behavior

Model should display with no red edges.

### Actual behavior

Model has red edges, or even stray red segments.

### Additional information
When the 8 circles cut into the center hole or sometimes the outer ring, these red edges appear. Analyze indicates no naked edges. I'm opening this issue to document it before submitting a PR that was not intended to fix it but does.

![Red_Edges](https://user-images.githubusercontent.com/14852918/89134931-34703180-d4f7-11ea-90d0-15a44b5e34c1.png)

**Comment by phkahler** [comment]
Looking through the text window I see several "can't find a ray that doesn't hit on edge!" messages. They go away with the patch.

**Comment by ruevs** [comment]
Please attach the model.

**Comment by phkahler** [comment]
[A_wheel.zip](https://github.com/solvespace/solvespace/files/5016551/A_wheel.zip)

Remember, random numbers are a platform dependent implementation so you may not see this problem on Windows. OTOH it is very easy to get multiple failures on my setup.
