### ISSUE TITLE
Modal error dialog box should respond to OK as well as escape

### ISSUE THREAD

**Issue by d235j** [solvespace/solvespace#67]
The modal error dialog box that appears when attempting to set up an invalid constraint should respond to OK (with the button highlighted) as well as escape.

Longer term maybe it would be better to eliminate modal dialog boxes completely, but rather refuse to perform the operation and provide visual feedback that lasts a few seconds.

**Comment by whitequark** [comment]
This doesn't appear to be possible; focusing the button explicitly lets me dismiss it with spacebar but not Return. How about switching the key equivalent from Escape to Return? Doesn't seem like I can do much here without reimplementing half of NSAlert.

**Comment by whitequark** [comment]
Fixed in master and 2.x as described above.
