### ISSUE TITLE
Build broken on Windows via VC++

### ISSUE THREAD

**Issue by sherief** [solvespace/solvespace#674]
### System information

SolveSpace version: f952991

Operating system: Windows 10 x64

### Expected behavior

Building with Visual Studio should be possible from CMake file

### Actual behavior

The generated project file for zlibstatic defines ASMINF and ASMV, but it doesn't assemble and link inffasx64.asm or gvmat64.asm, leading to undefined symbols for inflate_fast(), longest_match(), and others

### Additional information

N/A

**Comment by whitequark** [comment]
Which Visual Studio version?

**Comment by sherief** [comment]
Community 2019 Version 16.7.0

**Comment by ruevs** [comment]
I build with VS 2019 with no problems all the time...

**Comment by ruevs** [comment]
@sherief were you able to compile?

**Comment by ruevs** [comment]
> @sherief were you able to compile?

Write here if you still have problems. Closing.
