### ISSUE TITLE
Coincident edges show as "Naked Edges"

### ISSUE THREAD

**Issue by phkahler** [solvespace/solvespace#696]
### System information

SolveSpace version: 3.0~d8f5a8da

Operating system: Fedora 32

### Expected behavior

Make a sketch with 2 rectangles with one point coincident. Extrude. Analyze->Show Naked Edges

There should be no naked edges.

### Actual behavior

The coincident edges are shown red and there are 4 naked edges found.

### Additional information

You get similar behaviour even if the 2 extrusions are from different sketches as shown here
![Coincident_edges](https://user-images.githubusercontent.com/14852918/92966263-35c14200-f445-11ea-895a-1b8d5301efab.png)

This is similar to the second problem reported in issue #303. It is also loosely related to issue #171.

**Comment by phkahler** [comment]
My recent PR to fix this causes the following model to show zero naked edges at default CT settings. I never figured out why this sketch has any bad edges, or if it's actually misreporting them. Either way it doesn't make sense that the fix for this issue would affect it.
[gear90.zip](https://github.com/solvespace/solvespace/files/5213303/gear90.zip)

**Comment by phkahler** [comment]
The gear90.slvs is still having issues, so I don't think this fix is hiding anything. Everything else I've looked at seems fine too.

**Comment by ruevs** [comment]
@phkahler tag this "mesh" please.
