### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [solvespace/solvespace#703]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “List::Clear”](https://github.com/solvespace/solvespace/blob/d3da2c8b22d8f84e84adcce329e3b97a6a063e10/src/dsc.h#L286 "Update candidate").

**Comment by phkahler** [comment]
Any effort to change List or IdList should first have a look at PRs #429 and #433, and also the following experiment which apparently has profound performance implications: https://github.com/Evil-Spirit/solvespace-master/commits/id-list-indexing
