### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [solvespace/solvespace#704]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [SolveSpaceUI class](https://github.com/solvespace/solvespace/blob/668fe6f493eb96e9b4add37b6dbe9b82070cd9cc/src/solvespace.h#L798)
- [SMesh::Simplify()](https://github.com/solvespace/solvespace/blob/e74185b63940b4b977cc2f36cc8aeb15d79ac6dc/src/mesh.cpp#L99)

**Comment by Christoph-D** [comment]
solvespace does not use exceptions: https://github.com/solvespace/solvespace/blob/master/CONTRIBUTING.md#exceptions
So purely from an exception safety point of view this change is unnecessary.

unique_ptr might still be useful for simplicity.
