### ISSUE TITLE
Figure out gender of whitequark

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#729]
> And I just learned that Whitequark is "she"

@whitequark I don't know it is better to say them or not... @whitequark is a new kind of gender. Quantum one! Schrödinger talked about cat, but he don't say about gender of the cat. So, now there should be quantum experiment called "Whitequark's gender" as like "Schrödinger's cat". You can think whitequark is man or woman, but only asking ![shim](https://user-images.githubusercontent.com/1980537/94887467-e8ddf380-0465-11eb-8bf6-2c2f2be8ad52.gif) can let wave function to collapse!

_Originally posted by @Evil-Spirit in https://github.com/solvespace/solvespace/issues/716#issuecomment-702511994_

**Comment by whitequark** [comment]
What the fuck?
