### ISSUE TITLE
Horizontal/vertical constraint labels are off

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#74]
![2637](https://cloud.githubusercontent.com/assets/54771/19372478/00433dd6-91ac-11e6-84ec-e9021a088834.png)
Repro: https://github.com/whitequark/solvespace/files/329983/top.zip

This is a regression from 2.2 to 3.0, caused by Canvas changes most likely.

**Comment by whitequark** [comment]
This is a weird bug because it seems to happen in some workplanes but not others.

**Comment by whitequark** [comment]
@Evil-Spirit Can you look into this?

**Comment by Evil-Spirit** [comment]
@whitequark, Ok, I will fix it

**Comment by Evil-Spirit** [comment]
fixed https://github.com/Evil-Spirit/solvespace/commit/a3f9a4efc2e47127ac08a73a30fd50face125486

**Comment by whitequark** [comment]
Fixed in master, thanks
