### ISSUE TITLE
migrate to travis-ci.com before 31-12-2020

### ISSUE THREAD

**Issue by ppd** [solvespace/solvespace#744]
Travis-ci.org will shut down on 31-12-2020: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

Migrating to travis-ci.com is easy, free and also gives us a more robust (in my tests) arm64 target: arm64-graviton2 in a VM instead of an LXD-container.

Migration howto: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by ppd** [comment]
So I can't get the arm64 builds on LXD to fail any more, which is good. Sometimes it truncates the log, which is obviously bad. However, arm64 on VM is coming to bionic images, and that env seems to be more stable regarding log truncation.

It seems already a lot better than the arm64 arch on travis-ci.org, and it will surely improve in the future (either we move to focal images, or they bring VM support to bionic images). :tada:

**Comment by phkahler** [comment]
Better to move sooner, not later. Did your access to Travis get worked out?

**Comment by ppd** [comment]
Are you thinking of the snapcraft collaboration problem? I think that has to wait till after the weekend. 

I've just migrated my fork to travis-ci.com to play around with the new arm64 options.

**Comment by ppd** [comment]
@phkahler If you do the migration (log in & click migrate), I can push the switch to `arm64-graviton2`.

**Comment by ppd** [comment]
Alright. I think we're almost set for the migration if we so desire.

Required steps:

1. As I'm not an owner (or admin in Travis lingo) of the SolveSpace organization, I need @phkahler to push a button for use:
At https://travis-ci.com/organizations/solvespace/migrate click `Sign up for the beta`, add `SolveSpace` in the drop-down box and click `Join the beta`.
2. We (I) transfer the `solvespace` repository to travis-ci.com. All secrets should migrate automatically.
3. Rejoice and throw some confetti.

**Comment by phkahler** [comment]
That shoud be a GO.

**Comment by ppd** [comment]
Oh no. I promised too much. Seem like you need to go all the way: 
![ohno](https://user-images.githubusercontent.com/6652223/96507089-fa424080-1258-11eb-8807-a5ddb1f3fcd9.png)

**Comment by phkahler** [comment]
Would have been nice if they popped that up before :-) should be good now.

**Comment by ppd** [comment]
Perfect. Looks good and builds. All secrets seem to be there. If it doesn't explode in our faces in the next few days, this can be closed.
