### ISSUE TITLE
Update the Reference Manual for 3.0

### ISSUE THREAD

**Issue by phkahler** [solvespace/solvespace#777]
We need to update the changelog, reference manual: http://solvespace.com/ref.pl  and any other documentation we may have.

* [x] Update the section of chord tolerance, it's outdated and wrong.
* [x] Constraints section may need more on automatic constraints.
more...

**Comment by ruevs** [comment]
Expand the "Extrude" section to explain how to do slanted ones:
https://github.com/solvespace/solvespace/issues/628#issuecomment-641768927
https://github.com/solvespace/solvespace/issues/453#issuecomment-642508274
https://github.com/solvespace/solvespace/issues/453#issuecomment-642574190

**Comment by phkahler** [comment]
Also got the extrude section update and added revolve and helix.
Download page update as well. PR is in the solvespace-web repository.

**Comment by phkahler** [comment]
Closing, as this is pending a PR on the other repo.
