### ISSUE TITLE
Font List not fully scrollable in Sketch Curves from Text

### ISSUE THREAD

**Issue by masonhensley** [solvespace/solvespace#779]
Hello! Very awesome project, I'm in the early stages of replicating some classic car parts via laser cutting. I was able to design the parts with solvespace. This wasn't a biggie for me, but thought that it might be helpful to others who end up a little confused regarding font selection for Curves from Text. 

### System information
SolveSpace version: 3.0 (3.0~34328c97)

Operating system: OSX

### Expected behavior

When selecting a font text, I should be able to alphabetically scroll through the entire system font list.

### Actual behavior
Font list stops scrolling in the M's, which prevents accessing "stencil" fonts towards the end of the alphabetized list

### Additional information

![image](https://user-images.githubusercontent.com/534165/97117259-d9ef0780-16d8-11eb-9834-04899917447a.png)

**Comment by phkahler** [comment]
Can not reproduce on Linux so giving this the macOS lablel.

**Comment by ruevs** [comment]
Works on Windows as well.

**Comment by vespakoen** [comment]
I am on macOS `10.15.5` and it is working fine over here as well.

<img width="416" alt="Screenshot 2020-10-26 at 09 39 33" src="https://user-images.githubusercontent.com/876117/97150949-29801280-176f-11eb-82b5-a44af5fd3fcf.png">

- Can you check if it is also not working with the latest edge release from here:
https://github.com/solvespace/solvespace/releases/download/edge/SolveSpace.dmg

- What is you macOS version?

**Comment by phkahler** [comment]
I can not reproduce this from an edge build:  3.0~3694c9b3   on macOS Sierra 10.12.6

@masonhensley   do you have an unusually large number of fonts on your system? All I can think of is that there's some artificial limit on how many are shown in SolveSpace?

**Comment by vespakoen** [comment]
Or maybe on a non-retina display? Looks like this could be related:

<img width="608" alt="Screenshot 2020-10-26 at 17 20 16" src="https://user-images.githubusercontent.com/876117/97200268-49382a80-17b1-11eb-8b48-e71e69505879.png">

https://github.com/solvespace/solvespace/commit/f324477

**Comment by phkahler** [comment]
@vespakoen  you may be onto something.  Mine does not have a retina display and does not have the problem.

**Comment by phkahler** [comment]
@masonhensley does it change in any noticeable way if you resize the text window?  I guess if you're checking, does it always fail to scroll to the bottom, or just on the font selection screen? click on "configuration" from the home screen for a fairly long text window to test.

**Comment by vespakoen** [comment]
> @vespakoen you may be onto something. Mine does not have a retina display and does not have the problem.

I actually do have a retina display so that's probably not it...

**Comment by masonhensley** [comment]
Apologies for the delayed response.

Other info that might be helpful:
- 1394 fonts installed on my system, can't figure out a good way to calculate how far into the list it's going. I basically have the system defaults and all the google fonts cached locally. (bold, italics, etc versions of a font each count independently towards the font count)
- running 4k screens on a mac mini (one horizontal, one vertical) 
- scaling the display has no impact on the list length visible (first screenshot)

- @phkahler - no, even if I try to stretch out the control panel on a vertically oriented 4k monitor, it still maxes out (sorry for obnoxiously long screenshot below)

![image](https://user-images.githubusercontent.com/534165/97936291-11992780-1d49-11eb-9804-09e0dbe004d9.png)


![image](https://user-images.githubusercontent.com/534165/97936099-86b82d00-1d48-11eb-9a3a-b19f4bd47967.png)

**Comment by phkahler** [comment]
@masonhensley  Thank you for the response. Knowing you have a LOT of fonts, I have been able to reproduce this on my system by having it add each font to the list 10 times (and not remove duplicates). With that change mine scrolls to somewhere in the "n" range and stops.

**Comment by phkahler** [comment]
And there is the problem:
```
class TextWindow {
public:
    enum {
        MAX_COLS = 100,
        MIN_COLS = 45,
        MAX_ROWS = 2000
    };
```

Raising it to 5000 rows will fix the current problem but it will come back if someone has even more fonts. I'm not sure what's reasonable to do here. @ruevs? @ppd?

The text window seems to use several bytes per character. Making it 10000 rows would only take about 1Meg but that just seems like a hack.

**Comment by ruevs** [comment]
Yes it uses

```C++
uint32_t text[MAX_ROWS][MAX_COLS];

 struct {
        char            fg;
        char            bg;
        RgbaColor       bgRgb;
        int             link;
        uint32_t        data;
        LinkFunction   *f;
        LinkFunction   *h;
}       meta[MAX_ROWS][MAX_COLS];

int top[MAX_ROWS]; // in half-line units, or -1 for unused
```

I like this hard limit and would say we should just do `MAX_ROWS = 5000`.
A person with 4900+ fonts will complain again in a few years if ever ;-) For all other text windows I think our other performance bottlenecks will kill us long before the 5000 line limit (e.g. groups, constraints etc.).

**Comment by ppd** [comment]
So the user's expectation would always be to display all fonts. I just looked and I have 3100 fonts installed with just a careless extra `fonts-noto` install and some extras pulled in here and there by other packages. I've never gone "font hunting". So a pragmatic choice would be to increase to 5000 and print a little warning in case there are too many fonts.

**Comment by ruevs** [comment]
And I have 164 :-D
