### ISSUE TITLE
Property Browser scroll bar returns to top

### ISSUE THREAD

**Issue by kk6mrp** [solvespace/solvespace#782]
### System information

SolveSpace version: Edge 3.0~3694c9b3

Operating system: Windows 10

### Expected behavior

Scroll bar should stay in the position it was moved to.

### Actual behavior

Scroll bar and window returns to top of screen.

### Additional information

![property browser](https://user-images.githubusercontent.com/9358855/97201481-be830b80-176f-11eb-8f36-4f744650ef9a.gif)

**Comment by ruevs** [comment]
It stopped working here:

f324477dd06c15022670a4486bf83be3abbf48b5 is the first bad commit
commit f324477dd06c15022670a4486bf83be3abbf48b5
Author: whitequark
Date:   Thu Jul 12 19:29:44 2018 +0000

    Implement a platform abstraction for windows.

**Comment by ruevs** [comment]
@phkahler @ppd @vespakoen this is fixed here https://github.com/solvespace/solvespace/pull/783 please test on Linux and macOS since this should affect all platforms.

**Comment by phkahler** [comment]
@ruevs  I understand the need to test the fix on all platforms, but why did you tag the issue with the non-windows platforms?

**Comment by ruevs** [comment]
> @ruevs I understand the need to test the fix on all platforms, but why did you tag the issue with the non-windows platforms?

From reading the code it appears to me that the problem should have affected all platforms. If moving the scrollbar with the mouse works on Linux and macOS before https://github.com/solvespace/solvespace/pull/783 then for sure remove the tags.

**Comment by kk6mrp** [comment]
This does fix the issue for me
