### ISSUE TITLE
Donation options

### ISSUE THREAD

**Issue by baryluk** [solvespace/solvespace#788]
Is it possible to support financially developement of solvespace?

I can start with 100$ donation if that helps.

**Comment by ruevs** [comment]
This has been discussed in the past. Most recently last month.
https://github.com/solvespace/solvespace/issues/716
https://github.com/solvespace/solvespace/issues/265

**Comment by baryluk** [comment]
I see. Thanks

**Comment by andrewchambers** [comment]
You guys really are hamstringing yourselves by not accepting gifts/donations and linking people to confusing and dead threads when people try to give you money.
