### ISSUE TITLE
Perform generation in background

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#79]
Ideally, generation would happen as follows: every time there is a change to the sketch, the sketch is copied, and a new background thread is spun up, which starts regenerating the sketch. The GUI is fully responsive during this. Once the background thread finishes, the sketch is moved back, in place of the one already owned by the GUI thread. If a new modification is made while the sketch is being regenerated, the thread is cancelled and a new one is spun up.

Unresolved questions: how do we handle incremental regeneration of e.g. a last group in a sketch with 40 groups, with a large mesh? This is potentially a lot of triangle copying. We could share some data but have to be really careful about it.

Depends on #78 (since right now there is only one Sketch ever).

**Comment by phkahler** [comment]
Given the complexity of this and the significant performance gains that have been made in recent years, I think it's time to close this issue.
