### ISSUE TITLE
"Rotate" constraint for rotated elements

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#83]
Propose make new constraint for rotating elements instead of angle.

Rotating must be defined as revolutions (3600°/360°=10 rev.).

Angle must be limited to [0°,360°].

There no need use 2000° angle for rotate, instead we must use revolutions (as engines use aka RPM).

P.S. Angle more than 360° only could be usefull for "Screw" constraint, but it's another story.

**Comment by whitequark** [comment]
Please describe a specific use case in which this would be useful, and why it cannot be easily done today.

**Comment by Symbian9** [comment]
Angle must be used if there no more than one revolution (360°).
Where you need angle 361° or more?
Instead for simulating rotated elements in kinematics.

Currently SolveSpace cant use more than 180°.

**Comment by whitequark** [comment]
![2639](https://cloud.githubusercontent.com/assets/54771/19376129/91b944e0-91ca-11e6-82fc-5fdfe30e372c.png)

**Comment by Symbian9** [comment]
@whitequark, step dimension of angle give "pendulum" if try step angle , for example, from 100 to 250. Every 180 it well reverse direction!

**Comment by jwesthues** [comment]
With angles in [0,360), the solver would step across, and you could loop arbitrarily many times. That's something that could potentially be done, with some backwards-compatibility issues. [0,360] is not.
