### ISSUE TITLE
Enhancement: partial bounded constraints

### ISSUE THREAD

**Issue by 0x0203** [solvespace/solvespace#862]
When making assemblies for mechanical devices, it might be helpful to still allow some degrees of freedom, but to put bounds on them to restrict the range of motion of the assembly. For example, putting a partial dimensional constraint on a line such that its length could be anywhere in the range [x,y] (or x, +/- y), or bounding the angle between two lines between x and y degrees. 

Feel free to close if this isn't feasible/practical given the structure/design philosophy of the code, or if the same can already be achieved in other ways.

**Comment by kk6mrp** [comment]
Are you referring to this: https://github.com/solvespace/solvespace/issues/81?

**Comment by 0x0203** [comment]
Ah, many thanks. Looks like people are already on it.

**Comment by phkahler** [comment]
I wouldn't say they're on it. That was a long time ago and it's still not in. :-(

**Comment by 0x0203** [comment]
True enough. Until 3.0 gets the final stamp of approval though, I'm okay waiting. After that, hopefully it can be revisited.
