### ISSUE TITLE
"Draw triangle back faces in red" draws all faces in red when in workplane

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace#89]

**Comment by whitequark** [comment]
http://solvespace.com/forum.pl?action=viewthread&parent=1663

**Comment by whitequark** [comment]
@Evil-Spirit Can you look into this? I recall you saying there was some problem with mesh transparency.

**Comment by Evil-Spirit** [comment]
@whitequark, should I do it for master?

**Comment by whitequark** [comment]
@Evil-Spirit wait, I think I misremember, and that was a different issue... so let's postpone after GL2 merge.

**Comment by Evil-Spirit** [comment]
@whitequark, ok.

**Comment by whitequark** [comment]
Fixed in master
