### ISSUE TITLE
CI / Travis integration / auto-stats

### ISSUE THREAD

**Issue by twitchyliquid64** [solvespace/solvespace#9]
Any reason there isnt CI setup ATM?
If not, I might try setting on up.

**Comment by whitequark** [comment]
There is... https://travis-ci.org/solvespace/solvespace https://ci.appveyor.com/project/whitequark/solvespace

**Comment by twitchyliquid64** [comment]
Kek, might wanna get these ones going then

https://docs.travis-ci.com/user/status-images/ etc

**Comment by whitequark** [comment]
I don't see any point in those. They seem to be cargo-culted around open-source projects despite not providing any useful information. As a user of the project there is absolutely no reason for you to care about CI and as a contributor, how often do you look at those badges in README? Do you ever?

**Comment by twitchyliquid64** [comment]
Disagree. The badge itself provides credability that the project follows TDD and has some kind of indicative QA around the state of the build.

**Comment by whitequark** [comment]
See, you are making an excellent example. SolveSpace doesn't even *have tests*. All that the CI being green is currently demonstrating is that the packages can be built.

**Comment by twitchyliquid64** [comment]
Oh. Welp.

**Comment by whitequark** [comment]
(SolveSpace has tests now.)
