### ISSUE TITLE
Export 2D View as SVG does not correctly export dimension constraints of model

### ISSUE THREAD

**Issue by DeanCording** [solvespace/solvespace#904]
### System information

- **SolveSpace version:** 3.0~222c80e4
- **Operating system:** Kubuntu 20.10

### Expected behavior

Exported SVG 2D view should render dimension constraints the same as displayed in Solvespace when opened in another SVG application such as Inkscape.

![side](https://user-images.githubusercontent.com/251170/105268775-80ff1480-5bde-11eb-998f-2c7749f1d146.png)

### Actual behavior
Dimension constraints are rendered as a mix of styles.

![side-svg](https://user-images.githubusercontent.com/251170/105269512-cc65f280-5bdf-11eb-9355-2e252c441581.png)

Both labels and lines of dimension constraints are displayed using dashed lines.  As a result, the text of the labels is very hard to read.  However, some characters in some text labels are rendered using the correct style.

### Additional information

Looking at the actual SVG data, the structure of the SVG file is a complete mess.  Some elements as have their own section but most are just lumped into a single path.

My use case for this is to use Solvespace to produce diagrams for parts that I can export as SVG and import them into our standard manufacturing documents.  Not only is the exported SVG unusable as exported, its lack of proper structure makes it impossible to edit in an SVG editor link Inkspace.

**Comment by ruevs** [comment]
Related issues:
https://github.com/solvespace/solvespace/issues/518
https://github.com/solvespace/solvespace/issues/541

**Comment by robnee** [comment]
> Looking at the actual SVG data, the structure of the SVG file is a complete mess. Some elements as have their own section but most are just lumped into a single path.

The code was incorrectly assigning styles to sets of closed loops instead of each loop individually producing the very long paths with everything styled as the first loop in the set.

**Comment by ruevs** [comment]
I can confirm. #518 and #541 are fixed.
