### ISSUE TITLE
[QUESTION] Is it possible kind of extrude from one shape to another?

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [solvespace/solvespace#909]
Lets assume simple case that I would like to have circle on one end and square on the other end of "extrusion". Is it possible in solvespace?

**Comment by phkahler** [comment]
Currently this is not possible.  I'm hoping to increase the number of extrusion types in the coming year, but all of the ones I've got in mind involve simple transformations of the base sketch - resizing, rotating, but no shape shifting.  Maybe it wouldn't be too hard to add lofting where the "new" end of an extrusion has the same types of entities as the base, but their control points could be moved within a plane. But no, you can't do that now.
