### ISSUE TITLE
"Variadic" constrain equal

### ISSUE THREAD

**Issue by rpavlik** [solvespace/solvespace#921]
This is a feature requests for post-3.0. It would be really slick if I could select more than 2 items and hit q to constrain them all equal. This is an operation I wish I had quite frequently, as I'll often need repeated features that I don't step/repeat, etc. but want same size. Or, equal clearance from edges created by dimensioning construction lines, etc. Sometimes I'll even go ahead and select them all and try it, before realizing that oops, yeah that's an error.  (I'm also never sure how the "chain of constraints' makes a difference: Is it better to constraint each of B=A, C=A, D=A, or is it numerically fine to say A=B, B=C, C=D? In the case where I'll always want all those things equal and won't break that chain for some other reason.)

**Comment by ruevs** [comment]
There are two pull requests https://github.com/solvespace/solvespace/pull/530 https://github.com/solvespace/solvespace/pull/836
And an issues https://github.com/solvespace/solvespace/issues/573 about this already ;-)

Obviously a popular idea, definitely post 3.0

**Comment by phkahler** [comment]
Very soon after 3.0 so we have lots of time to get it right. But remember we try not to break existing sketches, which can happen while tweaking implementation details.

I really want this feature too.

**Comment by rpavlik** [comment]
oops, sorry for the dupe, I can close this if it's well captured elsewhere. I would just implement it as UI, constrain all to be equal to the first, but that's just me.
