### ISSUE TITLE
Mimalloc snuck in a -march=native on ARM

### ISSUE THREAD

**Issue by rpavlik** [solvespace/solvespace#934]
### System information

- **SolveSpace version:** 3.0~rc2
- **Operating system:** e.g. Debian testing

Debian's great QA automations found a `-march=native` in the build log on arm: turns out mimalloc put that in there. Filing this issue here because I had to work around it in the Debian package for SolveSpace, but it's really a mimalloc bug. `-march=native` should be a user choice.

https://qa.debian.org/bls/packages/s/solvespace.html
![image](https://user-images.githubusercontent.com/61129/107692827-f3f62b00-6c72-11eb-948c-71a90dee006f.png)

**Comment by ruevs** [comment]
@rpavlik It disappeared? Did the build already take this https://github.com/microsoft/mimalloc/pull/362 into account?

**Comment by rpavlik** [comment]
Ah, nifty - that's why I screenshot it. Somebody kindly sponsored my package update that patched it out:
![image](https://user-images.githubusercontent.com/61129/107806990-27958b80-6d2d-11eb-8d44-31b520b0a44b.png)

**Comment by rpavlik** [comment]
That said, I totally don't understand the other two warnings on that page.

**Comment by robnee** [comment]
This seems relevant to the hidden flags warning

https://manpages.debian.org/testing/blhc/blhc.1.en.html

**Comment by phkahler** [comment]
@rpavlik  I finally bumped to their latest dev-slice since there's been no updates in a month.
