### ISSUE TITLE
Property browser dissapeared

### ISSUE THREAD

**Issue by giannissc** [solvespace/solvespace#938]
I would like to inform you of a rather weird bug I have found. Sometimes when you work on an external monitor with solvespace the next time you use solvespace without a monitor the property browser is "trapped" into an imaginary monitor. The only way to make it reappper is if you connect it again to a monitor drag both windows to the laptop monitor and disconnect from there on.

I am using Windows 10 (don't know if that helps)

I willing to help any way I can to fix this.

Thanks you for your good work :)

**Comment by ruevs** [comment]
Or delete these registry keys:
```
HKEY_CURRENT_USER\Software\SolveSpace\
TextWindow_Bottom
TextWindow_Left
TextWindow_Right
TextWindow_Top
TextWindow_Maximized
```

Or if you are on an old version (2.3) `TextWnd_*`

**Comment by ruevs** [comment]
At least on Windows there is code that tries to handle this situation:

https://github.com/solvespace/solvespace/blob/04e872a61fbf1492b5425c0cc674d3a10998496b/src/platform/guiwin.cpp#L1220

So it is interesting how it happened. Can you consistently reproduce it?

**Comment by ruevs** [comment]
Fixed.
