### ISSUE TITLE
Crash when using symmetric constrains on two points

### ISSUE THREAD

**Issue by olt** [solvespace/solvespace#94]
SolveSpace 2.2 (official binaries on Mac OS X 10.10) crashes when I create a symmetric constraint with only two points. I can reproduce this with a new sketch, create a rectangle, select two points and call symmetric.

**Comment by whitequark** [comment]
Sigh... I've missed that commit in the 2.x branch somehow.

**Comment by whitequark** [comment]
Fixed in 2.x. I'll look into cutting another release in a few days, if nothing else comes up.
