### ISSUE TITLE
Erroneous zoom behaviour upon graphical window size/position change

### ISSUE THREAD

**Issue by ritvikRC** [solvespace/solvespace#941]
### System information

- **SolveSpace version:** 3.0~bcb8cd2c
- **Operating system:** Windows 7 (64 bit)

I have a Windows 7 system (64 bit) with dual monitor setup. In dual monitor setup, we can set 1 monitor as the main monitor & the second as secondary. 

### Expected behavior

Solvespace has this nice zoom behavior wherein when you zoom using the mouse wheel, it zooms into the area of the view that the mouse pointer is at. This "Zoom on mouse position" feature works well when the graphical window is maximized & inside my main(primary) monitor (graphical window in maximized mode & fully in the main monitor). 

### Actual behavior

But when I move the graphical window to the secondary monitor(graphical window in maximized mode & fully in the secondary monitor), This "Zoom on mouse position" does not work well. It zooms into a different region of the sketch.
It seems even if I change the graphical window size while it is still in the main monitor, this "Zoom on mouse position" does not work well.

It would be good if this "Zoom on mouse position" worked even after changes in graphical window size/position.

**Comment by ruevs** [comment]
The revision you are using (bcb8cd2c) is too old - from 2020-11-18 ;-) 
This was fixed four commits later in 5137da295a on 2020-11-22.
The original issue is here https://github.com/solvespace/solvespace/issues/806 and the pull request here https://github.com/solvespace/solvespace/pull/815

Please try with the "Edge" version from here https://github.com/solvespace/solvespace/releases

**Comment by ritvikRC** [comment]
Thanks
