### ISSUE TITLE
Cancel editing Dimension using ESCape key

### ISSUE THREAD

**Issue by gnbl** [solvespace/solvespace#958]
This is SolveSpace version 3.0~36719c62 on Windows 10.

As editing dimensions uses the keyboard, it would be nice (and even expected) to be able to cancel editing by hitting the escape key, the same way return/enter "submits" the new value.

**Comment by robnee** [comment]
I can reproduce this on Win 10 as well.  On Linux Esc cancels the edit as expected.  Seems like a bug on Windows.
