### ISSUE TITLE
Test failure with -march=x86-64-v3

### ISSUE THREAD

**Issue by rpavlik** [solvespace/solvespace#966]
From debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983952

Build/test log is 
[solvespace_3.0.rc2+repack1-3_unstable_gcc10-v3.log](https://github.com/solvespace/solvespace/files/6185769/solvespace_3.0.rc2%2Brepack1-3_unstable_gcc10-v3.log)

Looks like here's the issue: one very small reproducibility issue:

```
test/constraint/equal_angle/test.cpp:5: FAILED: render doesn't match reference; 1 (0.00%) pixels differ
```

**Comment by phkahler** [comment]
@rpavlik  Any idea why that test fails? Could the image created from xx86-64-v3 be usable to pass the test in all cases?

I've got a Zen (2400G) chip, but my GCC is not new enough to pass that option for answering these questions myself. I don't usually do Fedora Beta releases, but maybe I should update to 34Beta for this. Actually I haven't confirmed v3 is OK on zen1, all the info pairs specific instructions with the arch, not specific versions of chips.

**Comment by rpavlik** [comment]
Not sure, this was an automated filing by the gcc maintainer in Debian.

**Comment by phkahler** [comment]
I can reproduce it, but I can't see the difference in the test image. BTW the arch change gives it a notable performance boost on Zen. I'll look at the issue and measure performance more this weekend.

**Comment by ruevs** [comment]
Probably this problem https://github.com/solvespace/solvespace/issues/565#issuecomment-603364397
@whitequark Mar 24, 2020 :
> Using nonstandard 80 bit floating point numbers is exactly the cause of the problem @nabijaczleweli is facing here. They're rounded differently than what the tests are expecting and so the test fixtures don't match.

So does the "xx86-64-v3" target use any new math hardware/instructions?

@phkahler can you attach the PNG from the failing test please? [Winmerge ](https://winmerge.org/) can compare PNGs visually - which is very convenient, I'll try to see where the difference is.

**Comment by phkahler** [comment]
> So does the "x86-64-v3" target use any new math hardware/instructions?

It brings AVX and AVX2, so some new fused multiply-add instructions is all I see that might change things like rounding.

I'll post the PNGs later. I thought of it right after I deleted the failing one...

BTW in my day job I found that letting angles go greater than 2PI causes sin() and cos() accuracy to drop quite a bit at least on Intel hardware. I was producing variable frequency sine waves by adding dt*omega at each time step and things got bad until I added code to wrap around at 2PI. I need to check if Helix wraps around - I don't think it does.

**Comment by phkahler** [comment]
@ruevs 
Here is the original test image
![normal](https://user-images.githubusercontent.com/14852918/112702126-dff43a80-8e68-11eb-8f73-52bb0fc6f632.png)

And here is the one produced under march=x86-64-v3
![x86-64-v3](https://user-images.githubusercontent.com/14852918/112702107-ceab2e00-8e68-11eb-9665-2136fe858c4f.png)

**Comment by ruevs** [comment]
There is a one pixel difference in the length of the horizontal line of the right angle constraint:
![Diff](https://user-images.githubusercontent.com/15338069/112702937-d3d6a000-8e9d-11eb-8e20-c44419d74758.png)
Here the area is marked with a square:
![DiffSpot](https://user-images.githubusercontent.com/15338069/112703018-231cd080-8e9e-11eb-8742-9d2b0fd7ad04.png)
![ZoomIn](https://user-images.githubusercontent.com/15338069/112703149-8e66a280-8e9e-11eb-980c-cd7ec8f1b2ab.png)

**Comment by phkahler** [comment]
@ruevs I don't know why there are so many variants of this test in the folder. I could try some silly things like just moving the geometry around a little and seeing if I can find a variation that passes on both architectures. It seems to be a fluke since all the other tests pass.
