### ISSUE TITLE
Should we fork mimalloc?

### ISSUE THREAD

**Issue by phkahler** [solvespace/solvespace#969]
There are 3 commits to mimalloc that we really need in SolveSpace. The lead maintainer indicated just over a month ago that he'd make a new release "this week" but it's been a month and his github activity has dropped off the last few months. Should we fork it and tag the latest version on the dev-slice branch (which works for us AFAICT) so we can get our version 3 out?

**Comment by ruevs** [comment]
Why not simply point the external to the specific commit that works for us for now?

**Comment by phkahler** [comment]
> Why not simply point the external to the specific commit that works for us for now?

Can we do that without it having a tag? Should we? it's not even on their main branch.

**Comment by ruevs** [comment]
> > Why not simply point the external to the specific commit that works for us for now?
> 
> Can we do that without it having a tag? Should we? it's not even on their main branch.

- Can we do that?
Of course we can - it is trivial.
https://www.git-scm.com/docs/gitsubmodules#_workflow_for_a_third_party_library

>since submodules are fixed to an arbitrary version, the other project can be independently developed without affecting the superproject, allowing the superproject project to fix itself to new versions only when desired.

- Should we do it?
Why not? Checking out a particular branch/revision on the submodule seems (to me) much simpler and cleaner than forking it. And when they release a version we "like" we just update the submodule.

**Comment by phkahler** [comment]
@ruevs can you point it to their dev-slice branch which is 200 commits ahead of master? I'm currently quarantined away from my dev box :-(

**Comment by ruevs** [comment]
> @ruevs can you point it to their dev-slice branch which is 200 commits ahead of master? I'm currently quarantined away from my dev box :-(
> Never mind.

Sorry just saw this now :-(
