### ISSUE TITLE
Angle and reference angle constraints ignore decimal precision setting

### ISSUE THREAD

**Issue by michthom** [solvespace/solvespace#98]
Setting the precision to > 2 digits doesn't affect angle dimensions/constraints - is this deliberate?

**Comment by whitequark** [comment]
Yes. The "digits after decimal" setting (actually there are two settings, one for millimeters and one for inches) only affects linear dimensions. It does not seem useful to have more than two digits printed for angles anyhow.

**Comment by michthom** [comment]
Fair enough - I'm helping to design a precision (vernier) protractor to measure 1/60 degree of arc, and >2 digits would be helpful but is far from necessary.

**Comment by whitequark** [comment]
Wish granted in ac7b82d7c.

**Comment by michthom** [comment]
High five! Thanks very much - an unexpected and delightful surprise.
