### ISSUE TITLE
Three Sphere Performance Bug

### ISSUE THREAD

**Issue by giannissc** [solvespace/solvespace#981]
I am posting here about a potential performance bug in solvespace. The issue is easy to reproduce. Just create a sphere and then create a translate group. This makes solvespace unusable for a few minutes. I don't this operation should trash performance so much. Just leaving it here so that you can investigate

**Comment by pjanx** [comment]
Would you attach a file that shows the problem?

**Comment by pjanx** [comment]
I can't reproduce this even with 500 spheres: [hundreds-of-translated-spheres.zip](https://github.com/solvespace/solvespace/files/6224401/hundreds-of-translated-spheres.zip)

**Comment by phkahler** [comment]
What version of SolveSpace?
What is your chord tolerance set to?

**Comment by giannissc** [comment]
I actually discovered what the problem is by seeing your example @pjanx. Instead of using half a circle for generating the sphere I used a full circle.

**Comment by giannissc** [comment]
Using half a circle is night and day in performance
