### ISSUE TITLE
Ambient 1.0 settings ignored on PDF and SVG export

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#986]
### System information

- **SolveSpace version:** `3.0~` https://github.com/solvespace/solvespace/commit/10ca307d986ab0c52faaab4fcaedb26bd42d1fd6
- **Operating system:** Debian 10 buster

### Expected behavior

Export of shaded triangles should depend on `ambient lighting` settings.

@robnee, See *"Flat colors render mode"* thread:

- https://github.com/solvespace/solvespace/issues/524

Special use-case: ***if*** `ambient lighting` set to `1.0` *shaded triangles should be exported as "flat color"*

![pic.0](https://i.imgur.com/udhoYTg.png)

### Actual behavior

Actually if set `ambient lighting` to `1.0` — triangles with same color value (according solid group color) are NOT rendered as in pure "flat colors" (see PDF and SVG in attached ZIP):

![pic.1](https://i.imgur.com/vhmOIyo.png)

In same time if *"File > Export Image..."* — it shown exactly as expected (see PNG file in attached ZIP):

![pic.2](https://i.imgur.com/hNJV6ho.png)

### Additional information

- [slvs-ambient-export.zip](https://github.com/solvespace/solvespace/files/6246731/slvs-ambient-export.zip)

**Comment by robnee** [comment]
@Symbian9 Just so I understand, if ambient light == 1.0 then don't compute the lighting and just use the group's solid color for all triangles?

**Comment by phkahler** [comment]
@robnee For on-screen rendering they are additive. You get flat coloring by setting ambient = 1.0 and set the other lights brightness to 0.0.   It's possible to use both and I don't recall any clamping if things get too bright (maybe should ;-)

**Comment by phkahler** [comment]
I should clarify that. It's ambient*(r,g,b) + c1*(r,g,b) + c2*(r,g,b)

Where (r,g,b) is the surface color, c1 and c2 are coefficients for light 1 and 2 which are simply the dot product of the light direction and the surface normal (snells law). Apparently I didn't add the ambient term to 2D export - nor did I know where that would go ;-)

**Comment by robnee** [comment]
Looks like the lighting value needs to be clamped prior to applying it to the rgb values.  

There is also a bug on the config screen for the ambient lighting which doesn't manifest for me on Linux but does on Windows.  It looks like the Printf is copied from the light direction but needs to have the arg for the light number removed.  This caused crazy behavior when I was testing with Windows.  I'll include in the PR.
