### ISSUE TITLE
2.2/download version on gh crashes when symmetric constraint added

### ISSUE THREAD

**Issue by ohsix** [solvespace/solvespace#99]
when i select the right most 2 vertices on the rectangle, and add symmetric constraint, solvepace crashes/exits on windows

i tested with linux on master but i can't spend time ruling it out atm.

[plasticsetup.slvs.zip](https://github.com/solvespace/solvespace/files/584545/plasticsetup.slvs.zip)

**Comment by whitequark** [comment]
Dupe of https://github.com/solvespace/solvespace/issues/94; leaving open until 2.3 is released.
