### ISSUE TITLE
Crash when using some unicode characters on-sketch

### ISSUE THREAD

**Issue by phkahler** [solvespace/solvespace#990]
### System information

- **SolveSpace version:** 3.0 RC2
- **Operating system:** Fedora

### Expected behavior

SolveSpace should not crash.

### Actual behavior

Paste certain unicode characters into a comment-constraint and it will crash.
Sample String:
未闭合轮廓，或样式不一致!

That was the original chinese translation for "not closed contour, or not all same style!"
The alternate comma is apparently the bad symbol as indicated in #984

### Additional information

We will fix 984 by changing the translation, but putting certain characters in a comment will still cause a crash, so I'm opening this issue.

**Comment by robnee** [comment]
@phkahler It looks like glyph for this character in the font is wrong:

```
[ff0c] ，
8.,1.41;8.;7.19,-1.41
```
